// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &acsFederationConfigurationDataSource{}
	_ datasource.DataSourceWithConfigure = &acsFederationConfigurationDataSource{}
)

type acsFederationConfigurationDataSource struct{ client *clients.Client }

// NewAcsFederationConfigurationDataSource looks up a AcsFederationConfiguration object (Get-AcsFederationConfiguration).
func NewAcsFederationConfigurationDataSource() datasource.DataSource {
	return &acsFederationConfigurationDataSource{}
}

func (d *acsFederationConfigurationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_acs_federation_configuration"
}

func (d *acsFederationConfigurationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing AcsFederationConfiguration object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"allowed_acs_resources":              schema.StringAttribute{Computed: true, Description: "Maps to the -AllowedAcsResources parameter."},
			"enable_acs_users":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableAcsUsers parameter."},
			"hide_banner_for_allowed_acs_users":  schema.BoolAttribute{Computed: true, Description: "Maps to the -HideBannerForAllowedAcsUsers parameter."},
			"label_for_allowed_acs_users":        schema.StringAttribute{Computed: true, Description: "Maps to the -LabelForAllowedAcsUsers parameter."},
			"require_acs_federation_for_meeting": schema.BoolAttribute{Computed: true, Description: "Maps to the -RequireAcsFederationForMeeting parameter."},
		},
	}
}

func (d *acsFederationConfigurationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *acsFederationConfigurationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data acsFederationConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsTeamsAcsFederationConfiguration(ctx, cs.GetCsTeamsAcsFederationConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-AcsFederationConfiguration failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("AcsFederationConfiguration not found", "no AcsFederationConfiguration object for identity "+identity)
		return
	}
	readAcsFederationConfiguration(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
