// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &appSetupPolicyResource{}
	_ resource.ResourceWithConfigure   = &appSetupPolicyResource{}
	_ resource.ResourceWithImportState = &appSetupPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &appSetupPolicyResource{}
)

type appSetupPolicyResource struct{ client *clients.Client }

// NewAppSetupPolicyResource manages the AppSetupPolicy object (New-AppSetupPolicy / Get-AppSetupPolicy / Set-AppSetupPolicy / Remove-AppSetupPolicy).
func NewAppSetupPolicyResource() resource.Resource { return &appSetupPolicyResource{} }

type appSetupPolicyModel struct {
	ID                          types.String `tfsdk:"id"`
	Identity                    types.String `tfsdk:"identity"`
	AdditionalCustomizationApps types.String `tfsdk:"additional_customization_apps"`
	AllowSideLoading            types.Bool   `tfsdk:"allow_side_loading"`
	AllowUserPinning            types.Bool   `tfsdk:"allow_user_pinning"`
	AppPresetList               types.String `tfsdk:"app_preset_list"`
	AppPresetMeetingList        types.String `tfsdk:"app_preset_meeting_list"`
	Description                 types.String `tfsdk:"description"`
	PinnedAppBarApps            types.String `tfsdk:"pinned_app_bar_apps"`
	PinnedCallingBarApps        types.String `tfsdk:"pinned_calling_bar_apps"`
	PinnedMessageBarApps        types.String `tfsdk:"pinned_message_bar_apps"`
}

func (r *appSetupPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_app_setup_policy"
}

func (r *appSetupPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the AppSetupPolicy policy via New-CsTeamsAppSetupPolicy / Get-CsTeamsAppSetupPolicy / Set-CsTeamsAppSetupPolicy / Remove-CsTeamsAppSetupPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                            schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                      schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"additional_customization_apps": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AdditionalCustomizationApps parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"allow_side_loading":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowSideLoading parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_user_pinning":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowUserPinning parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"app_preset_list":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AppPresetList parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"app_preset_meeting_list":       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AppPresetMeetingList parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"pinned_app_bar_apps":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PinnedAppBarApps parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"pinned_calling_bar_apps":       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PinnedCallingBarApps parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"pinned_message_bar_apps":       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PinnedMessageBarApps parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *appSetupPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *appSetupPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan appSetupPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config appSetupPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if plan.Identity.ValueString() == "Global" {
		sp := cs.SetCsTeamsAppSetupPolicyParams{}
		sp.Identity = plan.Identity.ValueString()
		if v := config.AdditionalCustomizationApps.ValueString(); v != "" {
			sp.AdditionalCustomizationApps = objectParam(v)
		}
		if !config.AllowSideLoading.IsNull() {
			sp.AllowSideLoading = plan.AllowSideLoading.ValueBoolPointer()
		}
		if !config.AllowUserPinning.IsNull() {
			sp.AllowUserPinning = plan.AllowUserPinning.ValueBoolPointer()
		}
		if v := config.AppPresetList.ValueString(); v != "" {
			sp.AppPresetList = objectParam(v)
		}
		if v := config.AppPresetMeetingList.ValueString(); v != "" {
			sp.AppPresetMeetingList = objectParam(v)
		}
		if !config.Description.IsNull() {
			sp.Description = plan.Description.ValueString()
		}
		if v := config.PinnedAppBarApps.ValueString(); v != "" {
			sp.PinnedAppBarApps = objectParam(v)
		}
		if v := config.PinnedCallingBarApps.ValueString(); v != "" {
			sp.PinnedCallingBarApps = objectParam(v)
		}
		if v := config.PinnedMessageBarApps.ValueString(); v != "" {
			sp.PinnedMessageBarApps = objectParam(v)
		}
		if resp.Diagnostics.HasError() {
			return
		}
		if _, err := r.client.CS.SetCsTeamsAppSetupPolicy(ctx, sp); err != nil {
			resp.Diagnostics.AddError("Set-AppSetupPolicy failed", err.Error())
			return
		}
		cfg := plan
		ident := plan.Identity.ValueString()
		if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
			if !resp.Diagnostics.HasError() {
				resp.Diagnostics.AddError("AppSetupPolicy not found", "identity Global does not exist and cannot be created")
			}
			return
		}
		r.reconcileState(&cfg, &plan)
		resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
		return
	}
	p := cs.NewCsTeamsAppSetupPolicyParams{}
	if v := config.AdditionalCustomizationApps.ValueString(); v != "" {
		p.AdditionalCustomizationApps = objectParam(v)
	}
	if !config.AllowSideLoading.IsNull() {
		p.AllowSideLoading = plan.AllowSideLoading.ValueBoolPointer()
	}
	if !config.AllowUserPinning.IsNull() {
		p.AllowUserPinning = plan.AllowUserPinning.ValueBoolPointer()
	}
	if v := config.AppPresetList.ValueString(); v != "" {
		p.AppPresetList = objectParam(v)
	}
	if v := config.AppPresetMeetingList.ValueString(); v != "" {
		p.AppPresetMeetingList = objectParam(v)
	}
	if !config.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if v := config.PinnedAppBarApps.ValueString(); v != "" {
		p.PinnedAppBarApps = objectParam(v)
	}
	if v := config.PinnedCallingBarApps.ValueString(); v != "" {
		p.PinnedCallingBarApps = objectParam(v)
	}
	if v := config.PinnedMessageBarApps.ValueString(); v != "" {
		p.PinnedMessageBarApps = objectParam(v)
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTeamsAppSetupPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-AppSetupPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-AppSetupPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readAppSetupPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *appSetupPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state appSetupPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *appSetupPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state appSetupPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsAppSetupPolicyParams{}
	sp.Identity = id
	if v := plan.AdditionalCustomizationApps.ValueString(); v != "" {
		sp.AdditionalCustomizationApps = objectParam(v)
	}
	if !plan.AllowSideLoading.Equal(state.AllowSideLoading) {
		sp.AllowSideLoading = plan.AllowSideLoading.ValueBoolPointer()
	}
	if !plan.AllowUserPinning.Equal(state.AllowUserPinning) {
		sp.AllowUserPinning = plan.AllowUserPinning.ValueBoolPointer()
	}
	if v := plan.AppPresetList.ValueString(); v != "" {
		sp.AppPresetList = objectParam(v)
	}
	if v := plan.AppPresetMeetingList.ValueString(); v != "" {
		sp.AppPresetMeetingList = objectParam(v)
	}
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if v := plan.PinnedAppBarApps.ValueString(); v != "" {
		sp.PinnedAppBarApps = objectParam(v)
	}
	if v := plan.PinnedCallingBarApps.ValueString(); v != "" {
		sp.PinnedCallingBarApps = objectParam(v)
	}
	if v := plan.PinnedMessageBarApps.ValueString(); v != "" {
		sp.PinnedMessageBarApps = objectParam(v)
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsAppSetupPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AppSetupPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Description": cfg.Description,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *appSetupPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state appSetupPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.identityOf(state) == "Global" {
		resp.Diagnostics.AddWarning("AppSetupPolicy Global not deleted", "The Global AppSetupPolicy is a built-in tenant singleton that cannot be removed. It has been dropped from Terraform state but remains unchanged in the tenant.")
		return
	}
	if _, err := r.client.CS.RemoveCsTeamsAppSetupPolicy(ctx, cs.RemoveCsTeamsAppSetupPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-AppSetupPolicy failed", err.Error())
		}
	}
}

func (r *appSetupPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *appSetupPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan appSetupPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity != "Global" {
		return
	}
	res, err := r.client.CS.GetCsTeamsAppSetupPolicy(ctx, cs.GetCsTeamsAppSetupPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur appSetupPolicyModel
	readAppSetupPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AdditionalCustomizationApps.IsUnknown() {
		plan.AdditionalCustomizationApps = cur.AdditionalCustomizationApps
	}
	if plan.AllowSideLoading.IsUnknown() {
		plan.AllowSideLoading = cur.AllowSideLoading
	}
	if plan.AllowUserPinning.IsUnknown() {
		plan.AllowUserPinning = cur.AllowUserPinning
	}
	if plan.AppPresetList.IsUnknown() {
		plan.AppPresetList = cur.AppPresetList
	}
	if plan.AppPresetMeetingList.IsUnknown() {
		plan.AppPresetMeetingList = cur.AppPresetMeetingList
	}
	if plan.Description.IsUnknown() {
		plan.Description = cur.Description
	}
	if plan.PinnedAppBarApps.IsUnknown() {
		plan.PinnedAppBarApps = cur.PinnedAppBarApps
	}
	if plan.PinnedCallingBarApps.IsUnknown() {
		plan.PinnedCallingBarApps = cur.PinnedCallingBarApps
	}
	if plan.PinnedMessageBarApps.IsUnknown() {
		plan.PinnedMessageBarApps = cur.PinnedMessageBarApps
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *appSetupPolicyResource) identityOf(m appSetupPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *appSetupPolicyResource) refresh(ctx context.Context, identity string, m *appSetupPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsAppSetupPolicy(ctx, cs.GetCsTeamsAppSetupPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-AppSetupPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readAppSetupPolicy(ctx, obj, m)
	return true
}

func readAppSetupPolicy(ctx context.Context, obj map[string]any, m *appSetupPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AdditionalCustomizationApps = types.StringValue(getObjectJSON(obj, "AdditionalCustomizationApps"))
	m.AllowSideLoading = types.BoolValue(getBool(obj, "AllowSideLoading"))
	m.AllowUserPinning = types.BoolValue(getBool(obj, "AllowUserPinning"))
	m.AppPresetList = types.StringValue(getObjectJSON(obj, "AppPresetList"))
	m.AppPresetMeetingList = types.StringValue(getObjectJSON(obj, "AppPresetMeetingList"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.PinnedAppBarApps = types.StringValue(getObjectJSON(obj, "PinnedAppBarApps"))
	m.PinnedCallingBarApps = types.StringValue(getObjectJSON(obj, "PinnedCallingBarApps"))
	m.PinnedMessageBarApps = types.StringValue(getObjectJSON(obj, "PinnedMessageBarApps"))
	_ = ctx
}

func (r *appSetupPolicyResource) reconcileState(cfg, read *appSetupPolicyModel) {
	read.AdditionalCustomizationApps = reconcile.KeepStr(cfg.AdditionalCustomizationApps, read.AdditionalCustomizationApps)
	read.AllowSideLoading = reconcile.KeepBool(cfg.AllowSideLoading, read.AllowSideLoading)
	read.AllowUserPinning = reconcile.KeepBool(cfg.AllowUserPinning, read.AllowUserPinning)
	read.AppPresetList = reconcile.KeepStr(cfg.AppPresetList, read.AppPresetList)
	read.AppPresetMeetingList = reconcile.KeepStr(cfg.AppPresetMeetingList, read.AppPresetMeetingList)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.PinnedAppBarApps = reconcile.KeepStr(cfg.PinnedAppBarApps, read.PinnedAppBarApps)
	read.PinnedCallingBarApps = reconcile.KeepStr(cfg.PinnedCallingBarApps, read.PinnedCallingBarApps)
	read.PinnedMessageBarApps = reconcile.KeepStr(cfg.PinnedMessageBarApps, read.PinnedMessageBarApps)
}
