// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &appSetupPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &appSetupPolicyListDataSource{}
)

type appSetupPolicyListDataSource struct{ client *clients.Client }

// NewAppSetupPolicyListDataSource lists every AppSetupPolicy object (Get-AppSetupPolicy).
func NewAppSetupPolicyListDataSource() datasource.DataSource { return &appSetupPolicyListDataSource{} }

type appSetupPolicyListModel struct {
	Items []appSetupPolicyModel `tfsdk:"app_setup_policies"`
}

func (d *appSetupPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_app_setup_policies"
}

func (d *appSetupPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every AppSetupPolicy object (Get-AppSetupPolicy).",
		Attributes: map[string]schema.Attribute{
			"app_setup_policies": schema.ListNestedAttribute{Computed: true, Description: "All AppSetupPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                            schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                      schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"additional_customization_apps": schema.StringAttribute{Computed: true, Description: "Maps to the -AdditionalCustomizationApps parameter."},
				"allow_side_loading":            schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowSideLoading parameter."},
				"allow_user_pinning":            schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowUserPinning parameter."},
				"app_preset_list":               schema.StringAttribute{Computed: true, Description: "Maps to the -AppPresetList parameter."},
				"app_preset_meeting_list":       schema.StringAttribute{Computed: true, Description: "Maps to the -AppPresetMeetingList parameter."},
				"description":                   schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
				"pinned_app_bar_apps":           schema.StringAttribute{Computed: true, Description: "Maps to the -PinnedAppBarApps parameter."},
				"pinned_calling_bar_apps":       schema.StringAttribute{Computed: true, Description: "Maps to the -PinnedCallingBarApps parameter."},
				"pinned_message_bar_apps":       schema.StringAttribute{Computed: true, Description: "Maps to the -PinnedMessageBarApps parameter."},
			}}},
		},
	}
}

func (d *appSetupPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *appSetupPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTeamsAppSetupPolicy(ctx, cs.GetCsTeamsAppSetupPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-AppSetupPolicy failed", err.Error())
		return
	}
	var data appSetupPolicyListModel
	for _, obj := range res.Value {
		var e appSetupPolicyModel
		readAppSetupPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
