// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &applicationAccessPolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &applicationAccessPolicyDataSource{}
)

type applicationAccessPolicyDataSource struct{ client *clients.Client }

// NewApplicationAccessPolicyDataSource looks up a ApplicationAccessPolicy object (Get-ApplicationAccessPolicy).
func NewApplicationAccessPolicyDataSource() datasource.DataSource {
	return &applicationAccessPolicyDataSource{}
}

func (d *applicationAccessPolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_access_policy"
}

func (d *applicationAccessPolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing ApplicationAccessPolicy object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":    schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"app_ids":     schema.StringAttribute{Computed: true, Description: "Maps to the -AppIds parameter."},
			"description": schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
		},
	}
}

func (d *applicationAccessPolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *applicationAccessPolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data applicationAccessPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsApplicationAccessPolicy(ctx, cs.GetCsApplicationAccessPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-ApplicationAccessPolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("ApplicationAccessPolicy not found", "no ApplicationAccessPolicy object for identity "+identity)
		return
	}
	readApplicationAccessPolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
