// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &bYODAndDesksPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &bYODAndDesksPolicyListDataSource{}
)

type bYODAndDesksPolicyListDataSource struct{ client *clients.Client }

// NewBYODAndDesksPolicyListDataSource lists every BYODAndDesksPolicy object (Get-BYODAndDesksPolicy).
func NewBYODAndDesksPolicyListDataSource() datasource.DataSource {
	return &bYODAndDesksPolicyListDataSource{}
}

type bYODAndDesksPolicyListModel struct {
	Items []bYODAndDesksPolicyModel `tfsdk:"byod_and_desks_policies"`
}

func (d *bYODAndDesksPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_byod_and_desks_policies"
}

func (d *bYODAndDesksPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every BYODAndDesksPolicy object (Get-BYODAndDesksPolicy).",
		Attributes: map[string]schema.Attribute{
			"byod_and_desks_policies": schema.ListNestedAttribute{Computed: true, Description: "All BYODAndDesksPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":               schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"device_data_collection": schema.StringAttribute{Computed: true, Description: "Maps to the -DeviceDataCollection parameter."},
			}}},
		},
	}
}

func (d *bYODAndDesksPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *bYODAndDesksPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTeamsBYODAndDesksPolicy(ctx, cs.GetCsTeamsBYODAndDesksPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-BYODAndDesksPolicy failed", err.Error())
		return
	}
	var data bYODAndDesksPolicyListModel
	for _, obj := range res.Value {
		var e bYODAndDesksPolicyModel
		readBYODAndDesksPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
