// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &callingPolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &callingPolicyDataSource{}
)

type callingPolicyDataSource struct{ client *clients.Client }

// NewCallingPolicyDataSource looks up a CallingPolicy object (Get-CallingPolicy).
func NewCallingPolicyDataSource() datasource.DataSource { return &callingPolicyDataSource{} }

func (d *callingPolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_calling_policy"
}

func (d *callingPolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing CallingPolicy object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"ai_interpreter":                     schema.StringAttribute{Computed: true, Description: "Maps to the -AIInterpreter parameter."},
			"allow_call_forwarding_to_phone":     schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCallForwardingToPhone parameter."},
			"allow_call_forwarding_to_user":      schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCallForwardingToUser parameter."},
			"allow_call_groups":                  schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCallGroups parameter."},
			"allow_call_redirect":                schema.StringAttribute{Computed: true, Description: "Maps to the -AllowCallRedirect parameter."},
			"allow_cloud_recording_for_calls":    schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCloudRecordingForCalls parameter."},
			"allow_delegation":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowDelegation parameter."},
			"allow_meeting_knowledge_generation": schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowMeetingKnowledgeGeneration parameter."},
			"allow_private_calling":              schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowPrivateCalling parameter."},
			"allow_sip_devices_calling":          schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowSIPDevicesCalling parameter."},
			"allow_transcription_for_calling":    schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowTranscriptionForCalling parameter."},
			"allow_voicemail":                    schema.StringAttribute{Computed: true, Description: "Maps to the -AllowVoicemail parameter."},
			"allow_web_pstn_calling":             schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowWebPSTNCalling parameter."},
			"auto_answer_enabled_type":           schema.StringAttribute{Computed: true, Description: "Maps to the -AutoAnswerEnabledType parameter."},
			"busy_on_busy_enabled_type":          schema.StringAttribute{Computed: true, Description: "Maps to the -BusyOnBusyEnabledType parameter."},
			"call_recording_expiration_days":     schema.Int64Attribute{Computed: true, Description: "Maps to the -CallRecordingExpirationDays parameter."},
			"calling_spend_user_limit":           schema.Int64Attribute{Computed: true, Description: "Maps to the -CallingSpendUserLimit parameter."},
			"copilot":                            schema.StringAttribute{Computed: true, Description: "Maps to the -Copilot parameter."},
			"description":                        schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"enable_recording_and_transcription_custom_message":     schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableRecordingAndTranscriptionCustomMessage parameter."},
			"enable_spend_limits":                                   schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableSpendLimits parameter."},
			"enable_web_pstn_media_bypass":                          schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableWebPstnMediaBypass parameter."},
			"explicit_recording_consent":                            schema.StringAttribute{Computed: true, Description: "Maps to the -ExplicitRecordingConsent parameter."},
			"inbound_federated_call_routing_treatment":              schema.StringAttribute{Computed: true, Description: "Maps to the -InboundFederatedCallRoutingTreatment parameter."},
			"inbound_pstn_call_routing_treatment":                   schema.StringAttribute{Computed: true, Description: "Maps to the -InboundPstnCallRoutingTreatment parameter."},
			"live_captions_enabled_type_for_calling":                schema.StringAttribute{Computed: true, Description: "Maps to the -LiveCaptionsEnabledTypeForCalling parameter."},
			"music_on_hold_enabled_type":                            schema.StringAttribute{Computed: true, Description: "Maps to the -MusicOnHoldEnabledType parameter."},
			"popout_app_path_for_incoming_pstn_calls":               schema.StringAttribute{Computed: true, Description: "Maps to the -PopoutAppPathForIncomingPstnCalls parameter."},
			"popout_for_incoming_pstn_calls":                        schema.StringAttribute{Computed: true, Description: "Maps to the -PopoutForIncomingPstnCalls parameter."},
			"prevent_compliance_recording":                          schema.StringAttribute{Computed: true, Description: "Maps to the -PreventComplianceRecording parameter."},
			"prevent_toll_bypass":                                   schema.BoolAttribute{Computed: true, Description: "Maps to the -PreventTollBypass parameter."},
			"real_time_text":                                        schema.StringAttribute{Computed: true, Description: "Maps to the -RealTimeText parameter."},
			"recording_and_transcription_audio_notification":        schema.StringAttribute{Computed: true, Description: "Maps to the -RecordingAndTranscriptionAudioNotification parameter."},
			"recording_and_transcription_custom_message_identifier": schema.StringAttribute{Computed: true, Description: "Maps to the -RecordingAndTranscriptionCustomMessageIdentifier parameter."},
			"report_call":                     schema.StringAttribute{Computed: true, Description: "Maps to the -ReportCall parameter."},
			"show_teams_calls_in_call_log":    schema.BoolAttribute{Computed: true, Description: "Maps to the -ShowTeamsCallsInCallLog parameter."},
			"spam_filtering_enabled_type":     schema.StringAttribute{Computed: true, Description: "Maps to the -SpamFilteringEnabledType parameter."},
			"voice_phishing_detection":        schema.StringAttribute{Computed: true, Description: "Maps to the -VoicePhishingDetection parameter."},
			"voice_simulation_in_interpreter": schema.StringAttribute{Computed: true, Description: "Maps to the -VoiceSimulationInInterpreter parameter."},
		},
	}
}

func (d *callingPolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *callingPolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data callingPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsTeamsCallingPolicy(ctx, cs.GetCsTeamsCallingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-CallingPolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("CallingPolicy not found", "no CallingPolicy object for identity "+identity)
		return
	}
	readCallingPolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
