// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &clientConfigurationResource{}
	_ resource.ResourceWithConfigure   = &clientConfigurationResource{}
	_ resource.ResourceWithImportState = &clientConfigurationResource{}
	_ resource.ResourceWithModifyPlan  = &clientConfigurationResource{}
)

type clientConfigurationResource struct{ client *clients.Client }

// NewClientConfigurationResource manages the ClientConfiguration configuration (Get-ClientConfiguration / Set-ClientConfiguration); it adopts the existing object and is not deleted on destroy.
func NewClientConfigurationResource() resource.Resource { return &clientConfigurationResource{} }

type clientConfigurationModel struct {
	ID                               types.String `tfsdk:"id"`
	Identity                         types.String `tfsdk:"identity"`
	AllowBox                         types.Bool   `tfsdk:"allow_box"`
	AllowDropBox                     types.Bool   `tfsdk:"allow_drop_box"`
	AllowEgnyte                      types.Bool   `tfsdk:"allow_egnyte"`
	AllowEmailIntoChannel            types.Bool   `tfsdk:"allow_email_into_channel"`
	AllowGoogleDrive                 types.Bool   `tfsdk:"allow_google_drive"`
	AllowGuestUser                   types.Bool   `tfsdk:"allow_guest_user"`
	AllowOrganizationTab             types.Bool   `tfsdk:"allow_organization_tab"`
	AllowResourceAccountSendMessage  types.Bool   `tfsdk:"allow_resource_account_send_message"`
	AllowRoleBasedChatPermissions    types.Bool   `tfsdk:"allow_role_based_chat_permissions"`
	AllowScopedPeopleSearchandAccess types.Bool   `tfsdk:"allow_scoped_people_searchand_access"`
	AllowShareFile                   types.Bool   `tfsdk:"allow_share_file"`
	AllowSkypeBusinessInterop        types.Bool   `tfsdk:"allow_skype_business_interop"`
	ContentPin                       types.String `tfsdk:"content_pin"`
	ExtendedWorkInfoInPeopleSearch   types.Bool   `tfsdk:"extended_work_info_in_people_search"`
	ResourceAccountContentAccess     types.String `tfsdk:"resource_account_content_access"`
	RestrictedSenderList             types.String `tfsdk:"restricted_sender_list"`
	UseUnifiedDomain                 types.String `tfsdk:"use_unified_domain"`
}

func (r *clientConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_client_configuration"
}

func (r *clientConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the ClientConfiguration configuration via Set-CsTeamsClientConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                                   schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                             schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"allow_box":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowBox parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_drop_box":                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowDropBox parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_egnyte":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowEgnyte parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_email_into_channel":             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowEmailIntoChannel parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_google_drive":                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowGoogleDrive parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_guest_user":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowGuestUser parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_organization_tab":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowOrganizationTab parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_resource_account_send_message":  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowResourceAccountSendMessage parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_role_based_chat_permissions":    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowRoleBasedChatPermissions parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_scoped_people_searchand_access": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowScopedPeopleSearchandAccess parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_share_file":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowShareFile parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_skype_business_interop":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowSkypeBusinessInterop parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"content_pin":                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ContentPin parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"extended_work_info_in_people_search":  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ExtendedWorkInfoInPeopleSearch parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"resource_account_content_access":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ResourceAccountContentAccess parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"restricted_sender_list":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RestrictedSenderList parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"use_unified_domain":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -UseUnifiedDomain parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *clientConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *clientConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan clientConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config clientConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsClientConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.AllowBox.IsNull() {
		sp.AllowBox = plan.AllowBox.ValueBoolPointer()
	}
	if !config.AllowDropBox.IsNull() {
		sp.AllowDropBox = plan.AllowDropBox.ValueBoolPointer()
	}
	if !config.AllowEgnyte.IsNull() {
		sp.AllowEgnyte = plan.AllowEgnyte.ValueBoolPointer()
	}
	if !config.AllowEmailIntoChannel.IsNull() {
		sp.AllowEmailIntoChannel = plan.AllowEmailIntoChannel.ValueBoolPointer()
	}
	if !config.AllowGoogleDrive.IsNull() {
		sp.AllowGoogleDrive = plan.AllowGoogleDrive.ValueBoolPointer()
	}
	if !config.AllowGuestUser.IsNull() {
		sp.AllowGuestUser = plan.AllowGuestUser.ValueBoolPointer()
	}
	if !config.AllowOrganizationTab.IsNull() {
		sp.AllowOrganizationTab = plan.AllowOrganizationTab.ValueBoolPointer()
	}
	if !config.AllowResourceAccountSendMessage.IsNull() {
		sp.AllowResourceAccountSendMessage = plan.AllowResourceAccountSendMessage.ValueBoolPointer()
	}
	if !config.AllowRoleBasedChatPermissions.IsNull() {
		sp.AllowRoleBasedChatPermissions = plan.AllowRoleBasedChatPermissions.ValueBoolPointer()
	}
	if !config.AllowScopedPeopleSearchandAccess.IsNull() {
		sp.AllowScopedPeopleSearchandAccess = plan.AllowScopedPeopleSearchandAccess.ValueBoolPointer()
	}
	if !config.AllowShareFile.IsNull() {
		sp.AllowShareFile = plan.AllowShareFile.ValueBoolPointer()
	}
	if !config.AllowSkypeBusinessInterop.IsNull() {
		sp.AllowSkypeBusinessInterop = plan.AllowSkypeBusinessInterop.ValueBoolPointer()
	}
	if !config.ContentPin.IsNull() {
		sp.ContentPin = plan.ContentPin.ValueString()
	}
	if !config.ExtendedWorkInfoInPeopleSearch.IsNull() {
		sp.ExtendedWorkInfoInPeopleSearch = plan.ExtendedWorkInfoInPeopleSearch.ValueBoolPointer()
	}
	if !config.ResourceAccountContentAccess.IsNull() {
		sp.ResourceAccountContentAccess = plan.ResourceAccountContentAccess.ValueString()
	}
	if !config.RestrictedSenderList.IsNull() {
		sp.RestrictedSenderList = plan.RestrictedSenderList.ValueString()
	}
	if !config.UseUnifiedDomain.IsNull() {
		sp.UseUnifiedDomain = plan.UseUnifiedDomain.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsClientConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ClientConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *clientConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state clientConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *clientConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state clientConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsClientConfigurationParams{}
	sp.Identity = id
	if !plan.AllowBox.Equal(state.AllowBox) {
		sp.AllowBox = plan.AllowBox.ValueBoolPointer()
	}
	if !plan.AllowDropBox.Equal(state.AllowDropBox) {
		sp.AllowDropBox = plan.AllowDropBox.ValueBoolPointer()
	}
	if !plan.AllowEgnyte.Equal(state.AllowEgnyte) {
		sp.AllowEgnyte = plan.AllowEgnyte.ValueBoolPointer()
	}
	if !plan.AllowEmailIntoChannel.Equal(state.AllowEmailIntoChannel) {
		sp.AllowEmailIntoChannel = plan.AllowEmailIntoChannel.ValueBoolPointer()
	}
	if !plan.AllowGoogleDrive.Equal(state.AllowGoogleDrive) {
		sp.AllowGoogleDrive = plan.AllowGoogleDrive.ValueBoolPointer()
	}
	if !plan.AllowGuestUser.Equal(state.AllowGuestUser) {
		sp.AllowGuestUser = plan.AllowGuestUser.ValueBoolPointer()
	}
	if !plan.AllowOrganizationTab.Equal(state.AllowOrganizationTab) {
		sp.AllowOrganizationTab = plan.AllowOrganizationTab.ValueBoolPointer()
	}
	if !plan.AllowResourceAccountSendMessage.Equal(state.AllowResourceAccountSendMessage) {
		sp.AllowResourceAccountSendMessage = plan.AllowResourceAccountSendMessage.ValueBoolPointer()
	}
	if !plan.AllowRoleBasedChatPermissions.Equal(state.AllowRoleBasedChatPermissions) {
		sp.AllowRoleBasedChatPermissions = plan.AllowRoleBasedChatPermissions.ValueBoolPointer()
	}
	if !plan.AllowScopedPeopleSearchandAccess.Equal(state.AllowScopedPeopleSearchandAccess) {
		sp.AllowScopedPeopleSearchandAccess = plan.AllowScopedPeopleSearchandAccess.ValueBoolPointer()
	}
	if !plan.AllowShareFile.Equal(state.AllowShareFile) {
		sp.AllowShareFile = plan.AllowShareFile.ValueBoolPointer()
	}
	if !plan.AllowSkypeBusinessInterop.Equal(state.AllowSkypeBusinessInterop) {
		sp.AllowSkypeBusinessInterop = plan.AllowSkypeBusinessInterop.ValueBoolPointer()
	}
	if !plan.ContentPin.Equal(state.ContentPin) {
		sp.ContentPin = plan.ContentPin.ValueString()
	}
	if !plan.ExtendedWorkInfoInPeopleSearch.Equal(state.ExtendedWorkInfoInPeopleSearch) {
		sp.ExtendedWorkInfoInPeopleSearch = plan.ExtendedWorkInfoInPeopleSearch.ValueBoolPointer()
	}
	if !plan.ResourceAccountContentAccess.Equal(state.ResourceAccountContentAccess) {
		sp.ResourceAccountContentAccess = plan.ResourceAccountContentAccess.ValueString()
	}
	if !plan.RestrictedSenderList.Equal(state.RestrictedSenderList) {
		sp.RestrictedSenderList = plan.RestrictedSenderList.ValueString()
	}
	if !plan.UseUnifiedDomain.Equal(state.UseUnifiedDomain) {
		sp.UseUnifiedDomain = plan.UseUnifiedDomain.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsClientConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ClientConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"ContentPin":                   cfg.ContentPin,
		"ResourceAccountContentAccess": cfg.ResourceAccountContentAccess,
		"RestrictedSenderList":         cfg.RestrictedSenderList,
		"UseUnifiedDomain":             cfg.UseUnifiedDomain,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *clientConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("ClientConfiguration configuration not deleted", "This resource manages an existing ClientConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *clientConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *clientConfigurationResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan clientConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.CS.GetCsTeamsClientConfiguration(ctx, cs.GetCsTeamsClientConfigurationParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur clientConfigurationModel
	readClientConfiguration(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AllowBox.IsUnknown() {
		plan.AllowBox = cur.AllowBox
	}
	if plan.AllowDropBox.IsUnknown() {
		plan.AllowDropBox = cur.AllowDropBox
	}
	if plan.AllowEgnyte.IsUnknown() {
		plan.AllowEgnyte = cur.AllowEgnyte
	}
	if plan.AllowEmailIntoChannel.IsUnknown() {
		plan.AllowEmailIntoChannel = cur.AllowEmailIntoChannel
	}
	if plan.AllowGoogleDrive.IsUnknown() {
		plan.AllowGoogleDrive = cur.AllowGoogleDrive
	}
	if plan.AllowGuestUser.IsUnknown() {
		plan.AllowGuestUser = cur.AllowGuestUser
	}
	if plan.AllowOrganizationTab.IsUnknown() {
		plan.AllowOrganizationTab = cur.AllowOrganizationTab
	}
	if plan.AllowResourceAccountSendMessage.IsUnknown() {
		plan.AllowResourceAccountSendMessage = cur.AllowResourceAccountSendMessage
	}
	if plan.AllowRoleBasedChatPermissions.IsUnknown() {
		plan.AllowRoleBasedChatPermissions = cur.AllowRoleBasedChatPermissions
	}
	if plan.AllowScopedPeopleSearchandAccess.IsUnknown() {
		plan.AllowScopedPeopleSearchandAccess = cur.AllowScopedPeopleSearchandAccess
	}
	if plan.AllowShareFile.IsUnknown() {
		plan.AllowShareFile = cur.AllowShareFile
	}
	if plan.AllowSkypeBusinessInterop.IsUnknown() {
		plan.AllowSkypeBusinessInterop = cur.AllowSkypeBusinessInterop
	}
	if plan.ContentPin.IsUnknown() {
		plan.ContentPin = cur.ContentPin
	}
	if plan.ExtendedWorkInfoInPeopleSearch.IsUnknown() {
		plan.ExtendedWorkInfoInPeopleSearch = cur.ExtendedWorkInfoInPeopleSearch
	}
	if plan.ResourceAccountContentAccess.IsUnknown() {
		plan.ResourceAccountContentAccess = cur.ResourceAccountContentAccess
	}
	if plan.RestrictedSenderList.IsUnknown() {
		plan.RestrictedSenderList = cur.RestrictedSenderList
	}
	if plan.UseUnifiedDomain.IsUnknown() {
		plan.UseUnifiedDomain = cur.UseUnifiedDomain
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *clientConfigurationResource) identityOf(m clientConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *clientConfigurationResource) refresh(ctx context.Context, identity string, m *clientConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsClientConfiguration(ctx, cs.GetCsTeamsClientConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ClientConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readClientConfiguration(ctx, obj, m)
	return true
}

func readClientConfiguration(ctx context.Context, obj map[string]any, m *clientConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AllowBox = types.BoolValue(getBool(obj, "AllowBox"))
	m.AllowDropBox = types.BoolValue(getBool(obj, "AllowDropBox"))
	m.AllowEgnyte = types.BoolValue(getBool(obj, "AllowEgnyte"))
	m.AllowEmailIntoChannel = types.BoolValue(getBool(obj, "AllowEmailIntoChannel"))
	m.AllowGoogleDrive = types.BoolValue(getBool(obj, "AllowGoogleDrive"))
	m.AllowGuestUser = types.BoolValue(getBool(obj, "AllowGuestUser"))
	m.AllowOrganizationTab = types.BoolValue(getBool(obj, "AllowOrganizationTab"))
	m.AllowResourceAccountSendMessage = types.BoolValue(getBool(obj, "AllowResourceAccountSendMessage"))
	m.AllowRoleBasedChatPermissions = types.BoolValue(getBool(obj, "AllowRoleBasedChatPermissions"))
	m.AllowScopedPeopleSearchandAccess = types.BoolValue(getBool(obj, "AllowScopedPeopleSearchandAccess"))
	m.AllowShareFile = types.BoolValue(getBool(obj, "AllowShareFile"))
	m.AllowSkypeBusinessInterop = types.BoolValue(getBool(obj, "AllowSkypeBusinessInterop"))
	m.ContentPin = types.StringValue(getString(obj, "ContentPin"))
	m.ExtendedWorkInfoInPeopleSearch = types.BoolValue(getBool(obj, "ExtendedWorkInfoInPeopleSearch"))
	m.ResourceAccountContentAccess = types.StringValue(getString(obj, "ResourceAccountContentAccess"))
	m.RestrictedSenderList = types.StringValue(getString(obj, "RestrictedSenderList"))
	m.UseUnifiedDomain = types.StringValue(getString(obj, "UseUnifiedDomain"))
	_ = ctx
}

func (r *clientConfigurationResource) reconcileState(cfg, read *clientConfigurationModel) {
	read.AllowBox = reconcile.KeepBool(cfg.AllowBox, read.AllowBox)
	read.AllowDropBox = reconcile.KeepBool(cfg.AllowDropBox, read.AllowDropBox)
	read.AllowEgnyte = reconcile.KeepBool(cfg.AllowEgnyte, read.AllowEgnyte)
	read.AllowEmailIntoChannel = reconcile.KeepBool(cfg.AllowEmailIntoChannel, read.AllowEmailIntoChannel)
	read.AllowGoogleDrive = reconcile.KeepBool(cfg.AllowGoogleDrive, read.AllowGoogleDrive)
	read.AllowGuestUser = reconcile.KeepBool(cfg.AllowGuestUser, read.AllowGuestUser)
	read.AllowOrganizationTab = reconcile.KeepBool(cfg.AllowOrganizationTab, read.AllowOrganizationTab)
	read.AllowResourceAccountSendMessage = reconcile.KeepBool(cfg.AllowResourceAccountSendMessage, read.AllowResourceAccountSendMessage)
	read.AllowRoleBasedChatPermissions = reconcile.KeepBool(cfg.AllowRoleBasedChatPermissions, read.AllowRoleBasedChatPermissions)
	read.AllowScopedPeopleSearchandAccess = reconcile.KeepBool(cfg.AllowScopedPeopleSearchandAccess, read.AllowScopedPeopleSearchandAccess)
	read.AllowShareFile = reconcile.KeepBool(cfg.AllowShareFile, read.AllowShareFile)
	read.AllowSkypeBusinessInterop = reconcile.KeepBool(cfg.AllowSkypeBusinessInterop, read.AllowSkypeBusinessInterop)
	read.ContentPin = reconcile.KeepStr(cfg.ContentPin, read.ContentPin)
	read.ExtendedWorkInfoInPeopleSearch = reconcile.KeepBool(cfg.ExtendedWorkInfoInPeopleSearch, read.ExtendedWorkInfoInPeopleSearch)
	read.ResourceAccountContentAccess = reconcile.KeepStr(cfg.ResourceAccountContentAccess, read.ResourceAccountContentAccess)
	read.RestrictedSenderList = reconcile.KeepStr(cfg.RestrictedSenderList, read.RestrictedSenderList)
	read.UseUnifiedDomain = reconcile.KeepStr(cfg.UseUnifiedDomain, read.UseUnifiedDomain)
}
