// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &clientConfigurationDataSource{}
	_ datasource.DataSourceWithConfigure = &clientConfigurationDataSource{}
)

type clientConfigurationDataSource struct{ client *clients.Client }

// NewClientConfigurationDataSource looks up a ClientConfiguration object (Get-ClientConfiguration).
func NewClientConfigurationDataSource() datasource.DataSource {
	return &clientConfigurationDataSource{}
}

func (d *clientConfigurationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_client_configuration"
}

func (d *clientConfigurationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing ClientConfiguration object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                   schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                             schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"allow_box":                            schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowBox parameter."},
			"allow_drop_box":                       schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowDropBox parameter."},
			"allow_egnyte":                         schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowEgnyte parameter."},
			"allow_email_into_channel":             schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowEmailIntoChannel parameter."},
			"allow_google_drive":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowGoogleDrive parameter."},
			"allow_guest_user":                     schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowGuestUser parameter."},
			"allow_organization_tab":               schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowOrganizationTab parameter."},
			"allow_resource_account_send_message":  schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowResourceAccountSendMessage parameter."},
			"allow_role_based_chat_permissions":    schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowRoleBasedChatPermissions parameter."},
			"allow_scoped_people_searchand_access": schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowScopedPeopleSearchandAccess parameter."},
			"allow_share_file":                     schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowShareFile parameter."},
			"allow_skype_business_interop":         schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowSkypeBusinessInterop parameter."},
			"content_pin":                          schema.StringAttribute{Computed: true, Description: "Maps to the -ContentPin parameter."},
			"extended_work_info_in_people_search":  schema.BoolAttribute{Computed: true, Description: "Maps to the -ExtendedWorkInfoInPeopleSearch parameter."},
			"resource_account_content_access":      schema.StringAttribute{Computed: true, Description: "Maps to the -ResourceAccountContentAccess parameter."},
			"restricted_sender_list":               schema.StringAttribute{Computed: true, Description: "Maps to the -RestrictedSenderList parameter."},
			"use_unified_domain":                   schema.StringAttribute{Computed: true, Description: "Maps to the -UseUnifiedDomain parameter."},
		},
	}
}

func (d *clientConfigurationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *clientConfigurationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data clientConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsTeamsClientConfiguration(ctx, cs.GetCsTeamsClientConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-ClientConfiguration failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("ClientConfiguration not found", "no ClientConfiguration object for identity "+identity)
		return
	}
	readClientConfiguration(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
