// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &cortanaPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &cortanaPolicyListDataSource{}
)

type cortanaPolicyListDataSource struct{ client *clients.Client }

// NewCortanaPolicyListDataSource lists every CortanaPolicy object (Get-CortanaPolicy).
func NewCortanaPolicyListDataSource() datasource.DataSource { return &cortanaPolicyListDataSource{} }

type cortanaPolicyListModel struct {
	Items []cortanaPolicyModel `tfsdk:"cortana_policies"`
}

func (d *cortanaPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cortana_policies"
}

func (d *cortanaPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every CortanaPolicy object (Get-CortanaPolicy).",
		Attributes: map[string]schema.Attribute{
			"cortana_policies": schema.ListNestedAttribute{Computed: true, Description: "All CortanaPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                                   schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                             schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"allow_cortana_ambient_listening":      schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCortanaAmbientListening parameter."},
				"allow_cortana_in_context_suggestions": schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCortanaInContextSuggestions parameter."},
				"allow_cortana_voice_invocation":       schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCortanaVoiceInvocation parameter."},
				"cortana_voice_invocation_mode":        schema.StringAttribute{Computed: true, Description: "Maps to the -CortanaVoiceInvocationMode parameter."},
				"description":                          schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			}}},
		},
	}
}

func (d *cortanaPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *cortanaPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTeamsCortanaPolicy(ctx, cs.GetCsTeamsCortanaPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-CortanaPolicy failed", err.Error())
		return
	}
	var data cortanaPolicyListModel
	for _, obj := range res.Value {
		var e cortanaPolicyModel
		readCortanaPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
