// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &educationConfigurationResource{}
	_ resource.ResourceWithConfigure   = &educationConfigurationResource{}
	_ resource.ResourceWithImportState = &educationConfigurationResource{}
)

type educationConfigurationResource struct{ client *clients.Client }

// NewEducationConfigurationResource manages the EducationConfiguration configuration (Get-EducationConfiguration / Set-EducationConfiguration); it adopts the existing object and is not deleted on destroy.
func NewEducationConfigurationResource() resource.Resource { return &educationConfigurationResource{} }

type educationConfigurationModel struct {
	ID                                   types.String `tfsdk:"id"`
	Identity                             types.String `tfsdk:"identity"`
	EduGenerativeAIEnhancements          types.String `tfsdk:"edu_generative_ai_enhancements"`
	ParentGuardianPreferredContactMethod types.String `tfsdk:"parent_guardian_preferred_contact_method"`
	UpdateParentInformation              types.String `tfsdk:"update_parent_information"`
}

func (r *educationConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_education_configuration"
}

func (r *educationConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the EducationConfiguration configuration via Set-CsTeamsEducationConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                             schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                       schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"edu_generative_ai_enhancements": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EduGenerativeAIEnhancements parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"parent_guardian_preferred_contact_method": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ParentGuardianPreferredContactMethod parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"update_parent_information":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -UpdateParentInformation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *educationConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *educationConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan educationConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsEducationConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if !plan.EduGenerativeAIEnhancements.IsUnknown() && !plan.EduGenerativeAIEnhancements.IsNull() {
		sp.EduGenerativeAIEnhancements = plan.EduGenerativeAIEnhancements.ValueString()
	}
	if !plan.ParentGuardianPreferredContactMethod.IsUnknown() && !plan.ParentGuardianPreferredContactMethod.IsNull() {
		sp.ParentGuardianPreferredContactMethod = plan.ParentGuardianPreferredContactMethod.ValueString()
	}
	if !plan.UpdateParentInformation.IsUnknown() && !plan.UpdateParentInformation.IsNull() {
		sp.UpdateParentInformation = plan.UpdateParentInformation.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsEducationConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-EducationConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *educationConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state educationConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *educationConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state educationConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsEducationConfigurationParams{}
	sp.Identity = id
	if !plan.EduGenerativeAIEnhancements.Equal(state.EduGenerativeAIEnhancements) {
		sp.EduGenerativeAIEnhancements = plan.EduGenerativeAIEnhancements.ValueString()
	}
	if !plan.ParentGuardianPreferredContactMethod.Equal(state.ParentGuardianPreferredContactMethod) {
		sp.ParentGuardianPreferredContactMethod = plan.ParentGuardianPreferredContactMethod.ValueString()
	}
	if !plan.UpdateParentInformation.Equal(state.UpdateParentInformation) {
		sp.UpdateParentInformation = plan.UpdateParentInformation.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsEducationConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-EducationConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"EduGenerativeAIEnhancements":          cfg.EduGenerativeAIEnhancements,
		"ParentGuardianPreferredContactMethod": cfg.ParentGuardianPreferredContactMethod,
		"UpdateParentInformation":              cfg.UpdateParentInformation,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *educationConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("EducationConfiguration configuration not deleted", "This resource manages an existing EducationConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *educationConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *educationConfigurationResource) identityOf(m educationConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *educationConfigurationResource) refresh(ctx context.Context, identity string, m *educationConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsEducationConfiguration(ctx, cs.GetCsTeamsEducationConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-EducationConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readEducationConfiguration(ctx, obj, m)
	return true
}

func readEducationConfiguration(ctx context.Context, obj map[string]any, m *educationConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.EduGenerativeAIEnhancements = types.StringValue(getString(obj, "EduGenerativeAIEnhancements"))
	m.ParentGuardianPreferredContactMethod = types.StringValue(getString(obj, "ParentGuardianPreferredContactMethod"))
	m.UpdateParentInformation = types.StringValue(getString(obj, "UpdateParentInformation"))
	_ = ctx
}

func (r *educationConfigurationResource) reconcileState(cfg, read *educationConfigurationModel) {
	read.EduGenerativeAIEnhancements = reconcile.KeepStr(cfg.EduGenerativeAIEnhancements, read.EduGenerativeAIEnhancements)
	read.ParentGuardianPreferredContactMethod = reconcile.KeepStr(cfg.ParentGuardianPreferredContactMethod, read.ParentGuardianPreferredContactMethod)
	read.UpdateParentInformation = reconcile.KeepStr(cfg.UpdateParentInformation, read.UpdateParentInformation)
}
