// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &emergencyCallingPolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &emergencyCallingPolicyDataSource{}
)

type emergencyCallingPolicyDataSource struct{ client *clients.Client }

// NewEmergencyCallingPolicyDataSource looks up a EmergencyCallingPolicy object (Get-EmergencyCallingPolicy).
func NewEmergencyCallingPolicyDataSource() datasource.DataSource {
	return &emergencyCallingPolicyDataSource{}
}

func (d *emergencyCallingPolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_emergency_calling_policy"
}

func (d *emergencyCallingPolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing EmergencyCallingPolicy object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                    schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"description":                           schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"enhanced_emergency_service_disclaimer": schema.StringAttribute{Computed: true, Description: "Maps to the -EnhancedEmergencyServiceDisclaimer parameter."},
			"extended_notifications":                schema.StringAttribute{Computed: true, Description: "Maps to the -ExtendedNotifications parameter."},
			"external_location_lookup_mode":         schema.StringAttribute{Computed: true, Description: "Maps to the -ExternalLocationLookupMode parameter."},
			"notification_dial_out_number":          schema.StringAttribute{Computed: true, Description: "Maps to the -NotificationDialOutNumber parameter."},
			"notification_group":                    schema.StringAttribute{Computed: true, Description: "Maps to the -NotificationGroup parameter."},
			"notification_mode":                     schema.StringAttribute{Computed: true, Description: "Maps to the -NotificationMode parameter."},
		},
	}
}

func (d *emergencyCallingPolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *emergencyCallingPolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data emergencyCallingPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsTeamsEmergencyCallingPolicy(ctx, cs.GetCsTeamsEmergencyCallingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-EmergencyCallingPolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("EmergencyCallingPolicy not found", "no EmergencyCallingPolicy object for identity "+identity)
		return
	}
	readEmergencyCallingPolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
