// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &filesPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &filesPolicyListDataSource{}
)

type filesPolicyListDataSource struct{ client *clients.Client }

// NewFilesPolicyListDataSource lists every FilesPolicy object (Get-FilesPolicy).
func NewFilesPolicyListDataSource() datasource.DataSource { return &filesPolicyListDataSource{} }

type filesPolicyListModel struct {
	Items []filesPolicyModel `tfsdk:"files_policies"`
}

func (d *filesPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_files_policies"
}

func (d *filesPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every FilesPolicy object (Get-FilesPolicy).",
		Attributes: map[string]schema.Attribute{
			"files_policies": schema.ListNestedAttribute{Computed: true, Description: "All FilesPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                         schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                   schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"default_file_upload_app_id": schema.StringAttribute{Computed: true, Description: "Maps to the -DefaultFileUploadAppId parameter."},
				"file_sharing_in_chatswith_external_users": schema.StringAttribute{Computed: true, Description: "Maps to the -FileSharingInChatswithExternalUsers parameter."},
				"native_file_entry_points":                 schema.StringAttribute{Computed: true, Description: "Maps to the -NativeFileEntryPoints parameter."},
				"sp_channel_files_tab":                     schema.StringAttribute{Computed: true, Description: "Maps to the -SPChannelFilesTab parameter."},
			}}},
		},
	}
}

func (d *filesPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *filesPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTeamsFilesPolicy(ctx, cs.GetCsTeamsFilesPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-FilesPolicy failed", err.Error())
		return
	}
	var data filesPolicyListModel
	for _, obj := range res.Value {
		var e filesPolicyModel
		readFilesPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
