// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &filesPolicyResource{}
	_ resource.ResourceWithConfigure   = &filesPolicyResource{}
	_ resource.ResourceWithImportState = &filesPolicyResource{}
)

type filesPolicyResource struct{ client *clients.Client }

// NewFilesPolicyResource manages the FilesPolicy object (New-FilesPolicy / Get-FilesPolicy / Set-FilesPolicy / Remove-FilesPolicy).
func NewFilesPolicyResource() resource.Resource { return &filesPolicyResource{} }

type filesPolicyModel struct {
	ID                                  types.String `tfsdk:"id"`
	Identity                            types.String `tfsdk:"identity"`
	DefaultFileUploadAppId              types.String `tfsdk:"default_file_upload_app_id"`
	FileSharingInChatswithExternalUsers types.String `tfsdk:"file_sharing_in_chatswith_external_users"`
	NativeFileEntryPoints               types.String `tfsdk:"native_file_entry_points"`
	SPChannelFilesTab                   types.String `tfsdk:"sp_channel_files_tab"`
}

func (r *filesPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_files_policy"
}

func (r *filesPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the FilesPolicy policy via New-CsTeamsFilesPolicy / Get-CsTeamsFilesPolicy / Set-CsTeamsFilesPolicy / Remove-CsTeamsFilesPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                         schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                   schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"default_file_upload_app_id": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultFileUploadAppId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"file_sharing_in_chatswith_external_users": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -FileSharingInChatswithExternalUsers parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"native_file_entry_points":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -NativeFileEntryPoints parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"sp_channel_files_tab":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SPChannelFilesTab parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *filesPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *filesPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan filesPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := cs.NewCsTeamsFilesPolicyParams{}
	if !plan.DefaultFileUploadAppId.IsUnknown() && !plan.DefaultFileUploadAppId.IsNull() {
		p.DefaultFileUploadAppId = plan.DefaultFileUploadAppId.ValueString()
	}
	if !plan.FileSharingInChatswithExternalUsers.IsUnknown() && !plan.FileSharingInChatswithExternalUsers.IsNull() {
		p.FileSharingInChatswithExternalUsers = plan.FileSharingInChatswithExternalUsers.ValueString()
	}
	if !plan.NativeFileEntryPoints.IsUnknown() && !plan.NativeFileEntryPoints.IsNull() {
		p.NativeFileEntryPoints = plan.NativeFileEntryPoints.ValueString()
	}
	if !plan.SPChannelFilesTab.IsUnknown() && !plan.SPChannelFilesTab.IsNull() {
		p.SPChannelFilesTab = plan.SPChannelFilesTab.ValueString()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTeamsFilesPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-FilesPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-FilesPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readFilesPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *filesPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state filesPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *filesPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state filesPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsFilesPolicyParams{}
	sp.Identity = id
	if !plan.DefaultFileUploadAppId.Equal(state.DefaultFileUploadAppId) {
		sp.DefaultFileUploadAppId = plan.DefaultFileUploadAppId.ValueString()
	}
	if !plan.FileSharingInChatswithExternalUsers.Equal(state.FileSharingInChatswithExternalUsers) {
		sp.FileSharingInChatswithExternalUsers = plan.FileSharingInChatswithExternalUsers.ValueString()
	}
	if !plan.NativeFileEntryPoints.Equal(state.NativeFileEntryPoints) {
		sp.NativeFileEntryPoints = plan.NativeFileEntryPoints.ValueString()
	}
	if !plan.SPChannelFilesTab.Equal(state.SPChannelFilesTab) {
		sp.SPChannelFilesTab = plan.SPChannelFilesTab.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsFilesPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-FilesPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"DefaultFileUploadAppId":              cfg.DefaultFileUploadAppId,
		"FileSharingInChatswithExternalUsers": cfg.FileSharingInChatswithExternalUsers,
		"NativeFileEntryPoints":               cfg.NativeFileEntryPoints,
		"SPChannelFilesTab":                   cfg.SPChannelFilesTab,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *filesPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state filesPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.RemoveCsTeamsFilesPolicy(ctx, cs.RemoveCsTeamsFilesPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-FilesPolicy failed", err.Error())
		}
	}
}

func (r *filesPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *filesPolicyResource) identityOf(m filesPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *filesPolicyResource) refresh(ctx context.Context, identity string, m *filesPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsFilesPolicy(ctx, cs.GetCsTeamsFilesPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-FilesPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readFilesPolicy(ctx, obj, m)
	return true
}

func readFilesPolicy(ctx context.Context, obj map[string]any, m *filesPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.DefaultFileUploadAppId = types.StringValue(getString(obj, "DefaultFileUploadAppId"))
	m.FileSharingInChatswithExternalUsers = types.StringValue(getString(obj, "FileSharingInChatswithExternalUsers"))
	m.NativeFileEntryPoints = types.StringValue(getString(obj, "NativeFileEntryPoints"))
	m.SPChannelFilesTab = types.StringValue(getString(obj, "SPChannelFilesTab"))
	_ = ctx
}

func (r *filesPolicyResource) reconcileState(cfg, read *filesPolicyModel) {
	read.DefaultFileUploadAppId = reconcile.KeepStr(cfg.DefaultFileUploadAppId, read.DefaultFileUploadAppId)
	read.FileSharingInChatswithExternalUsers = reconcile.KeepStr(cfg.FileSharingInChatswithExternalUsers, read.FileSharingInChatswithExternalUsers)
	read.NativeFileEntryPoints = reconcile.KeepStr(cfg.NativeFileEntryPoints, read.NativeFileEntryPoints)
	read.SPChannelFilesTab = reconcile.KeepStr(cfg.SPChannelFilesTab, read.SPChannelFilesTab)
}
