// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &firstPartyMeetingTemplateConfigurationResource{}
	_ resource.ResourceWithConfigure   = &firstPartyMeetingTemplateConfigurationResource{}
	_ resource.ResourceWithImportState = &firstPartyMeetingTemplateConfigurationResource{}
	_ resource.ResourceWithModifyPlan  = &firstPartyMeetingTemplateConfigurationResource{}
)

type firstPartyMeetingTemplateConfigurationResource struct{ client *clients.Client }

// NewFirstPartyMeetingTemplateConfigurationResource manages the FirstPartyMeetingTemplateConfiguration configuration (Get-FirstPartyMeetingTemplateConfiguration / Set-FirstPartyMeetingTemplateConfiguration); it adopts the existing object and is not deleted on destroy.
func NewFirstPartyMeetingTemplateConfigurationResource() resource.Resource {
	return &firstPartyMeetingTemplateConfigurationResource{}
}

type firstPartyMeetingTemplateConfigurationModel struct {
	ID                    types.String `tfsdk:"id"`
	Identity              types.String `tfsdk:"identity"`
	Description           types.String `tfsdk:"description"`
	TeamsMeetingTemplates types.String `tfsdk:"teams_meeting_templates"`
}

func (r *firstPartyMeetingTemplateConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_first_party_meeting_template_configuration"
}

func (r *firstPartyMeetingTemplateConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the FirstPartyMeetingTemplateConfiguration configuration via Set-CsTeamsFirstPartyMeetingTemplateConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                      schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_meeting_templates": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsMeetingTemplates parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *firstPartyMeetingTemplateConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *firstPartyMeetingTemplateConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firstPartyMeetingTemplateConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config firstPartyMeetingTemplateConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsFirstPartyMeetingTemplateConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.Description.IsNull() {
		sp.Description = plan.Description.ValueString()
	}
	if v := config.TeamsMeetingTemplates.ValueString(); v != "" {
		sp.TeamsMeetingTemplates = objectParam(v)
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsFirstPartyMeetingTemplateConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-FirstPartyMeetingTemplateConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firstPartyMeetingTemplateConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firstPartyMeetingTemplateConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firstPartyMeetingTemplateConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firstPartyMeetingTemplateConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsFirstPartyMeetingTemplateConfigurationParams{}
	sp.Identity = id
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if v := plan.TeamsMeetingTemplates.ValueString(); v != "" {
		sp.TeamsMeetingTemplates = objectParam(v)
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsFirstPartyMeetingTemplateConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-FirstPartyMeetingTemplateConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Description": cfg.Description,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firstPartyMeetingTemplateConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("FirstPartyMeetingTemplateConfiguration configuration not deleted", "This resource manages an existing FirstPartyMeetingTemplateConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *firstPartyMeetingTemplateConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *firstPartyMeetingTemplateConfigurationResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan firstPartyMeetingTemplateConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.CS.GetCsTeamsFirstPartyMeetingTemplateConfiguration(ctx, cs.GetCsTeamsFirstPartyMeetingTemplateConfigurationParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur firstPartyMeetingTemplateConfigurationModel
	readFirstPartyMeetingTemplateConfiguration(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.Description.IsUnknown() {
		plan.Description = cur.Description
	}
	if plan.TeamsMeetingTemplates.IsUnknown() {
		plan.TeamsMeetingTemplates = cur.TeamsMeetingTemplates
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *firstPartyMeetingTemplateConfigurationResource) identityOf(m firstPartyMeetingTemplateConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *firstPartyMeetingTemplateConfigurationResource) refresh(ctx context.Context, identity string, m *firstPartyMeetingTemplateConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsFirstPartyMeetingTemplateConfiguration(ctx, cs.GetCsTeamsFirstPartyMeetingTemplateConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-FirstPartyMeetingTemplateConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readFirstPartyMeetingTemplateConfiguration(ctx, obj, m)
	return true
}

func readFirstPartyMeetingTemplateConfiguration(ctx context.Context, obj map[string]any, m *firstPartyMeetingTemplateConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.TeamsMeetingTemplates = types.StringValue(getObjectJSON(obj, "TeamsMeetingTemplates"))
	_ = ctx
}

func (r *firstPartyMeetingTemplateConfigurationResource) reconcileState(cfg, read *firstPartyMeetingTemplateConfigurationModel) {
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.TeamsMeetingTemplates = reconcile.KeepStr(cfg.TeamsMeetingTemplates, read.TeamsMeetingTemplates)
}
