// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &guestMeetingConfigurationResource{}
	_ resource.ResourceWithConfigure   = &guestMeetingConfigurationResource{}
	_ resource.ResourceWithImportState = &guestMeetingConfigurationResource{}
	_ resource.ResourceWithModifyPlan  = &guestMeetingConfigurationResource{}
)

type guestMeetingConfigurationResource struct{ client *clients.Client }

// NewGuestMeetingConfigurationResource manages the GuestMeetingConfiguration configuration (Get-GuestMeetingConfiguration / Set-GuestMeetingConfiguration); it adopts the existing object and is not deleted on destroy.
func NewGuestMeetingConfigurationResource() resource.Resource {
	return &guestMeetingConfigurationResource{}
}

type guestMeetingConfigurationModel struct {
	ID                                         types.String `tfsdk:"id"`
	Identity                                   types.String `tfsdk:"identity"`
	AllowExternalParticipantGiveRequestControl types.Bool   `tfsdk:"allow_external_participant_give_request_control"`
	AllowIPVideo                               types.Bool   `tfsdk:"allow_ip_video"`
	AllowMeetNow                               types.Bool   `tfsdk:"allow_meet_now"`
	AllowMultipleScreenshare                   types.Bool   `tfsdk:"allow_multiple_screenshare"`
	AllowParticipantGiveRequestControl         types.Bool   `tfsdk:"allow_participant_give_request_control"`
	AllowTranscription                         types.Bool   `tfsdk:"allow_transcription"`
	LiveCaptionsEnabledType                    types.String `tfsdk:"live_captions_enabled_type"`
	ScreenSharingMode                          types.String `tfsdk:"screen_sharing_mode"`
}

func (r *guestMeetingConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_guest_meeting_configuration"
}

func (r *guestMeetingConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the GuestMeetingConfiguration configuration via Set-CsTeamsGuestMeetingConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"allow_external_participant_give_request_control": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowExternalParticipantGiveRequestControl parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_ip_video":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowIPVideo parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_meet_now":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowMeetNow parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_multiple_screenshare":             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowMultipleScreenshare parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_participant_give_request_control": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowParticipantGiveRequestControl parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_transcription":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowTranscription parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"live_captions_enabled_type":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LiveCaptionsEnabledType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"screen_sharing_mode":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ScreenSharingMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *guestMeetingConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *guestMeetingConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan guestMeetingConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config guestMeetingConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsGuestMeetingConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.AllowExternalParticipantGiveRequestControl.IsNull() {
		sp.AllowExternalParticipantGiveRequestControl = plan.AllowExternalParticipantGiveRequestControl.ValueBoolPointer()
	}
	if !config.AllowIPVideo.IsNull() {
		sp.AllowIPVideo = plan.AllowIPVideo.ValueBoolPointer()
	}
	if !config.AllowMeetNow.IsNull() {
		sp.AllowMeetNow = plan.AllowMeetNow.ValueBoolPointer()
	}
	if !config.AllowMultipleScreenshare.IsNull() {
		sp.AllowMultipleScreenshare = plan.AllowMultipleScreenshare.ValueBoolPointer()
	}
	if !config.AllowParticipantGiveRequestControl.IsNull() {
		sp.AllowParticipantGiveRequestControl = plan.AllowParticipantGiveRequestControl.ValueBoolPointer()
	}
	if !config.AllowTranscription.IsNull() {
		sp.AllowTranscription = plan.AllowTranscription.ValueBoolPointer()
	}
	if !config.LiveCaptionsEnabledType.IsNull() {
		sp.LiveCaptionsEnabledType = plan.LiveCaptionsEnabledType.ValueString()
	}
	if !config.ScreenSharingMode.IsNull() {
		sp.ScreenSharingMode = plan.ScreenSharingMode.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsGuestMeetingConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-GuestMeetingConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *guestMeetingConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state guestMeetingConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *guestMeetingConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state guestMeetingConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsGuestMeetingConfigurationParams{}
	sp.Identity = id
	if !plan.AllowExternalParticipantGiveRequestControl.Equal(state.AllowExternalParticipantGiveRequestControl) {
		sp.AllowExternalParticipantGiveRequestControl = plan.AllowExternalParticipantGiveRequestControl.ValueBoolPointer()
	}
	if !plan.AllowIPVideo.Equal(state.AllowIPVideo) {
		sp.AllowIPVideo = plan.AllowIPVideo.ValueBoolPointer()
	}
	if !plan.AllowMeetNow.Equal(state.AllowMeetNow) {
		sp.AllowMeetNow = plan.AllowMeetNow.ValueBoolPointer()
	}
	if !plan.AllowMultipleScreenshare.Equal(state.AllowMultipleScreenshare) {
		sp.AllowMultipleScreenshare = plan.AllowMultipleScreenshare.ValueBoolPointer()
	}
	if !plan.AllowParticipantGiveRequestControl.Equal(state.AllowParticipantGiveRequestControl) {
		sp.AllowParticipantGiveRequestControl = plan.AllowParticipantGiveRequestControl.ValueBoolPointer()
	}
	if !plan.AllowTranscription.Equal(state.AllowTranscription) {
		sp.AllowTranscription = plan.AllowTranscription.ValueBoolPointer()
	}
	if !plan.LiveCaptionsEnabledType.Equal(state.LiveCaptionsEnabledType) {
		sp.LiveCaptionsEnabledType = plan.LiveCaptionsEnabledType.ValueString()
	}
	if !plan.ScreenSharingMode.Equal(state.ScreenSharingMode) {
		sp.ScreenSharingMode = plan.ScreenSharingMode.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsGuestMeetingConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-GuestMeetingConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"LiveCaptionsEnabledType": cfg.LiveCaptionsEnabledType,
		"ScreenSharingMode":       cfg.ScreenSharingMode,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *guestMeetingConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("GuestMeetingConfiguration configuration not deleted", "This resource manages an existing GuestMeetingConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *guestMeetingConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *guestMeetingConfigurationResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan guestMeetingConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.CS.GetCsTeamsGuestMeetingConfiguration(ctx, cs.GetCsTeamsGuestMeetingConfigurationParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur guestMeetingConfigurationModel
	readGuestMeetingConfiguration(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AllowExternalParticipantGiveRequestControl.IsUnknown() {
		plan.AllowExternalParticipantGiveRequestControl = cur.AllowExternalParticipantGiveRequestControl
	}
	if plan.AllowIPVideo.IsUnknown() {
		plan.AllowIPVideo = cur.AllowIPVideo
	}
	if plan.AllowMeetNow.IsUnknown() {
		plan.AllowMeetNow = cur.AllowMeetNow
	}
	if plan.AllowMultipleScreenshare.IsUnknown() {
		plan.AllowMultipleScreenshare = cur.AllowMultipleScreenshare
	}
	if plan.AllowParticipantGiveRequestControl.IsUnknown() {
		plan.AllowParticipantGiveRequestControl = cur.AllowParticipantGiveRequestControl
	}
	if plan.AllowTranscription.IsUnknown() {
		plan.AllowTranscription = cur.AllowTranscription
	}
	if plan.LiveCaptionsEnabledType.IsUnknown() {
		plan.LiveCaptionsEnabledType = cur.LiveCaptionsEnabledType
	}
	if plan.ScreenSharingMode.IsUnknown() {
		plan.ScreenSharingMode = cur.ScreenSharingMode
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *guestMeetingConfigurationResource) identityOf(m guestMeetingConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *guestMeetingConfigurationResource) refresh(ctx context.Context, identity string, m *guestMeetingConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsGuestMeetingConfiguration(ctx, cs.GetCsTeamsGuestMeetingConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-GuestMeetingConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readGuestMeetingConfiguration(ctx, obj, m)
	return true
}

func readGuestMeetingConfiguration(ctx context.Context, obj map[string]any, m *guestMeetingConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AllowExternalParticipantGiveRequestControl = types.BoolValue(getBool(obj, "AllowExternalParticipantGiveRequestControl"))
	m.AllowIPVideo = types.BoolValue(getBool(obj, "AllowIPVideo"))
	m.AllowMeetNow = types.BoolValue(getBool(obj, "AllowMeetNow"))
	m.AllowMultipleScreenshare = types.BoolValue(getBool(obj, "AllowMultipleScreenshare"))
	m.AllowParticipantGiveRequestControl = types.BoolValue(getBool(obj, "AllowParticipantGiveRequestControl"))
	m.AllowTranscription = types.BoolValue(getBool(obj, "AllowTranscription"))
	m.LiveCaptionsEnabledType = types.StringValue(getString(obj, "LiveCaptionsEnabledType"))
	m.ScreenSharingMode = types.StringValue(getString(obj, "ScreenSharingMode"))
	_ = ctx
}

func (r *guestMeetingConfigurationResource) reconcileState(cfg, read *guestMeetingConfigurationModel) {
	read.AllowExternalParticipantGiveRequestControl = reconcile.KeepBool(cfg.AllowExternalParticipantGiveRequestControl, read.AllowExternalParticipantGiveRequestControl)
	read.AllowIPVideo = reconcile.KeepBool(cfg.AllowIPVideo, read.AllowIPVideo)
	read.AllowMeetNow = reconcile.KeepBool(cfg.AllowMeetNow, read.AllowMeetNow)
	read.AllowMultipleScreenshare = reconcile.KeepBool(cfg.AllowMultipleScreenshare, read.AllowMultipleScreenshare)
	read.AllowParticipantGiveRequestControl = reconcile.KeepBool(cfg.AllowParticipantGiveRequestControl, read.AllowParticipantGiveRequestControl)
	read.AllowTranscription = reconcile.KeepBool(cfg.AllowTranscription, read.AllowTranscription)
	read.LiveCaptionsEnabledType = reconcile.KeepStr(cfg.LiveCaptionsEnabledType, read.LiveCaptionsEnabledType)
	read.ScreenSharingMode = reconcile.KeepStr(cfg.ScreenSharingMode, read.ScreenSharingMode)
}
