// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &inboundExemptNumberPatternResource{}
	_ resource.ResourceWithConfigure   = &inboundExemptNumberPatternResource{}
	_ resource.ResourceWithImportState = &inboundExemptNumberPatternResource{}
)

type inboundExemptNumberPatternResource struct{ client *clients.Client }

// NewInboundExemptNumberPatternResource manages the InboundExemptNumberPattern object (New-InboundExemptNumberPattern / Get-InboundExemptNumberPattern / Set-InboundExemptNumberPattern / Remove-InboundExemptNumberPattern).
func NewInboundExemptNumberPatternResource() resource.Resource {
	return &inboundExemptNumberPatternResource{}
}

type inboundExemptNumberPatternModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	Description types.String `tfsdk:"description"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	Name        types.String `tfsdk:"name"`
	Pattern     types.String `tfsdk:"pattern"`
}

func (r *inboundExemptNumberPatternResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_inbound_exempt_number_pattern"
}

func (r *inboundExemptNumberPatternResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the InboundExemptNumberPattern policy via New-CsInboundExemptNumberPattern / Get-CsInboundExemptNumberPattern / Set-CsInboundExemptNumberPattern / Remove-CsInboundExemptNumberPattern.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":    schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"name":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"pattern":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Pattern parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *inboundExemptNumberPatternResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *inboundExemptNumberPatternResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan inboundExemptNumberPatternModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := cs.NewCsInboundExemptNumberPatternParams{}
	if !plan.Description.IsUnknown() && !plan.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if !plan.Enabled.IsUnknown() && !plan.Enabled.IsNull() {
		p.Enabled = plan.Enabled.ValueBoolPointer()
	}
	if !plan.Name.IsUnknown() && !plan.Name.IsNull() {
		p.Name = plan.Name.ValueString()
	}
	if !plan.Pattern.IsUnknown() && !plan.Pattern.IsNull() {
		p.Pattern = plan.Pattern.ValueString()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsInboundExemptNumberPattern(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-InboundExemptNumberPattern failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-InboundExemptNumberPattern returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readInboundExemptNumberPattern(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *inboundExemptNumberPatternResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state inboundExemptNumberPatternModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *inboundExemptNumberPatternResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state inboundExemptNumberPatternModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsInboundExemptNumberPatternParams{}
	sp.Identity = id
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.Enabled.Equal(state.Enabled) {
		sp.Enabled = plan.Enabled.ValueBoolPointer()
	}
	if !plan.Pattern.Equal(state.Pattern) {
		sp.Pattern = plan.Pattern.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsInboundExemptNumberPattern(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-InboundExemptNumberPattern failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Description": cfg.Description,
		"Pattern":     cfg.Pattern,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *inboundExemptNumberPatternResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state inboundExemptNumberPatternModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.RemoveCsInboundExemptNumberPattern(ctx, cs.RemoveCsInboundExemptNumberPatternParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-InboundExemptNumberPattern failed", err.Error())
		}
	}
}

func (r *inboundExemptNumberPatternResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *inboundExemptNumberPatternResource) identityOf(m inboundExemptNumberPatternModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *inboundExemptNumberPatternResource) refresh(ctx context.Context, identity string, m *inboundExemptNumberPatternModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsInboundExemptNumberPattern(ctx, cs.GetCsInboundExemptNumberPatternParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-InboundExemptNumberPattern failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readInboundExemptNumberPattern(ctx, obj, m)
	return true
}

func readInboundExemptNumberPattern(ctx context.Context, obj map[string]any, m *inboundExemptNumberPatternModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.Pattern = types.StringValue(getString(obj, "Pattern"))
	_ = ctx
}

func (r *inboundExemptNumberPatternResource) reconcileState(cfg, read *inboundExemptNumberPatternModel) {
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.Pattern = reconcile.KeepStr(cfg.Pattern, read.Pattern)
}
