// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &inboundExemptNumberPatternDataSource{}
	_ datasource.DataSourceWithConfigure = &inboundExemptNumberPatternDataSource{}
)

type inboundExemptNumberPatternDataSource struct{ client *clients.Client }

// NewInboundExemptNumberPatternDataSource looks up a InboundExemptNumberPattern object (Get-InboundExemptNumberPattern).
func NewInboundExemptNumberPatternDataSource() datasource.DataSource {
	return &inboundExemptNumberPatternDataSource{}
}

func (d *inboundExemptNumberPatternDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_inbound_exempt_number_pattern"
}

func (d *inboundExemptNumberPatternDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing InboundExemptNumberPattern object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":    schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"description": schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"enabled":     schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
			"name":        schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"pattern":     schema.StringAttribute{Computed: true, Description: "Maps to the -Pattern parameter."},
		},
	}
}

func (d *inboundExemptNumberPatternDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *inboundExemptNumberPatternDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data inboundExemptNumberPatternModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsInboundExemptNumberPattern(ctx, cs.GetCsInboundExemptNumberPatternParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-InboundExemptNumberPattern failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("InboundExemptNumberPattern not found", "no InboundExemptNumberPattern object for identity "+identity)
		return
	}
	readInboundExemptNumberPattern(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
