// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &iPPhonePolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &iPPhonePolicyDataSource{}
)

type iPPhonePolicyDataSource struct{ client *clients.Client }

// NewIPPhonePolicyDataSource looks up a IPPhonePolicy object (Get-IPPhonePolicy).
func NewIPPhonePolicyDataSource() datasource.DataSource { return &iPPhonePolicyDataSource{} }

func (d *iPPhonePolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ip_phone_policy"
}

func (d *iPPhonePolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing IPPhonePolicy object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                  schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"allow_better_together":               schema.StringAttribute{Computed: true, Description: "Maps to the -AllowBetterTogether parameter."},
			"allow_home_screen":                   schema.StringAttribute{Computed: true, Description: "Maps to the -AllowHomeScreen parameter."},
			"allow_hot_desking":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowHotDesking parameter."},
			"description":                         schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"hot_desking_idle_timeout_in_minutes": schema.Int64Attribute{Computed: true, Description: "Maps to the -HotDeskingIdleTimeoutInMinutes parameter."},
			"search_on_common_area_phone_mode":    schema.StringAttribute{Computed: true, Description: "Maps to the -SearchOnCommonAreaPhoneMode parameter."},
			"sign_in_mode":                        schema.StringAttribute{Computed: true, Description: "Maps to the -SignInMode parameter."},
		},
	}
}

func (d *iPPhonePolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *iPPhonePolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data iPPhonePolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsTeamsIPPhonePolicy(ctx, cs.GetCsTeamsIPPhonePolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-IPPhonePolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("IPPhonePolicy not found", "no IPPhonePolicy object for identity "+identity)
		return
	}
	readIPPhonePolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
