// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &mainlineAttendantTenantInformationListDataSource{}
	_ datasource.DataSourceWithConfigure = &mainlineAttendantTenantInformationListDataSource{}
)

type mainlineAttendantTenantInformationListDataSource struct{ client *clients.Client }

// NewMainlineAttendantTenantInformationListDataSource lists every MainlineAttendantTenantInformation object (Get-MainlineAttendantTenantInformation).
func NewMainlineAttendantTenantInformationListDataSource() datasource.DataSource {
	return &mainlineAttendantTenantInformationListDataSource{}
}

type mainlineAttendantTenantInformationListModel struct {
	Items []mainlineAttendantTenantInformationModel `tfsdk:"mainline_attendant_tenant_informations"`
}

func (d *mainlineAttendantTenantInformationListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mainline_attendant_tenant_informations"
}

func (d *mainlineAttendantTenantInformationListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every MainlineAttendantTenantInformation object (Get-MainlineAttendantTenantInformation).",
		Attributes: map[string]schema.Attribute{
			"mainline_attendant_tenant_informations": schema.ListNestedAttribute{Computed: true, Description: "All MainlineAttendantTenantInformation objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"name":         schema.StringAttribute{Computed: true, Description: "Name of the object."},
				"display_name": schema.StringAttribute{Computed: true, Description: "Display name of the object."},
				"json":         schema.StringAttribute{Computed: true, Description: "The full object encoded as JSON; decode with jsondecode()."},
			}}},
		},
	}
}

func (d *mainlineAttendantTenantInformationListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *mainlineAttendantTenantInformationListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsMainlineAttendantTenantInformation(ctx, cs.GetCsMainlineAttendantTenantInformationParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-MainlineAttendantTenantInformation failed", err.Error())
		return
	}
	var data mainlineAttendantTenantInformationListModel
	for _, obj := range res.Value {
		var e mainlineAttendantTenantInformationModel
		readMainlineAttendantTenantInformation(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
