// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &meetingTemplatePermissionPolicyResource{}
	_ resource.ResourceWithConfigure   = &meetingTemplatePermissionPolicyResource{}
	_ resource.ResourceWithImportState = &meetingTemplatePermissionPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &meetingTemplatePermissionPolicyResource{}
)

type meetingTemplatePermissionPolicyResource struct{ client *clients.Client }

// NewMeetingTemplatePermissionPolicyResource manages the MeetingTemplatePermissionPolicy object (New-MeetingTemplatePermissionPolicy / Get-MeetingTemplatePermissionPolicy / Set-MeetingTemplatePermissionPolicy / Remove-MeetingTemplatePermissionPolicy).
func NewMeetingTemplatePermissionPolicyResource() resource.Resource {
	return &meetingTemplatePermissionPolicyResource{}
}

type meetingTemplatePermissionPolicyModel struct {
	ID                       types.String `tfsdk:"id"`
	Identity                 types.String `tfsdk:"identity"`
	DefaultMeetingTemplateId types.String `tfsdk:"default_meeting_template_id"`
	Description              types.String `tfsdk:"description"`
	HiddenMeetingTemplates   types.String `tfsdk:"hidden_meeting_templates"`
}

func (r *meetingTemplatePermissionPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_meeting_template_permission_policy"
}

func (r *meetingTemplatePermissionPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MeetingTemplatePermissionPolicy policy via New-CsTeamsMeetingTemplatePermissionPolicy / Get-CsTeamsMeetingTemplatePermissionPolicy / Set-CsTeamsMeetingTemplatePermissionPolicy / Remove-CsTeamsMeetingTemplatePermissionPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                    schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"default_meeting_template_id": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultMeetingTemplateId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"hidden_meeting_templates":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -HiddenMeetingTemplates parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *meetingTemplatePermissionPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *meetingTemplatePermissionPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan meetingTemplatePermissionPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config meetingTemplatePermissionPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if plan.Identity.ValueString() == "Global" {
		sp := cs.SetCsTeamsMeetingTemplatePermissionPolicyParams{}
		sp.Identity = plan.Identity.ValueString()
		if !config.DefaultMeetingTemplateId.IsNull() {
			sp.DefaultMeetingTemplateId = plan.DefaultMeetingTemplateId.ValueString()
		}
		if !config.Description.IsNull() {
			sp.Description = plan.Description.ValueString()
		}
		if v := config.HiddenMeetingTemplates.ValueString(); v != "" {
			sp.HiddenMeetingTemplates = objectParam(v)
		}
		if resp.Diagnostics.HasError() {
			return
		}
		if _, err := r.client.CS.SetCsTeamsMeetingTemplatePermissionPolicy(ctx, sp); err != nil {
			resp.Diagnostics.AddError("Set-MeetingTemplatePermissionPolicy failed", err.Error())
			return
		}
		cfg := plan
		ident := plan.Identity.ValueString()
		if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
			if !resp.Diagnostics.HasError() {
				resp.Diagnostics.AddError("MeetingTemplatePermissionPolicy not found", "identity Global does not exist and cannot be created")
			}
			return
		}
		r.reconcileState(&cfg, &plan)
		resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
		return
	}
	p := cs.NewCsTeamsMeetingTemplatePermissionPolicyParams{}
	if !config.DefaultMeetingTemplateId.IsNull() {
		p.DefaultMeetingTemplateId = plan.DefaultMeetingTemplateId.ValueString()
	}
	if !config.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if v := config.HiddenMeetingTemplates.ValueString(); v != "" {
		p.HiddenMeetingTemplates = objectParam(v)
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTeamsMeetingTemplatePermissionPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-MeetingTemplatePermissionPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-MeetingTemplatePermissionPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readMeetingTemplatePermissionPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *meetingTemplatePermissionPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state meetingTemplatePermissionPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *meetingTemplatePermissionPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state meetingTemplatePermissionPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsMeetingTemplatePermissionPolicyParams{}
	sp.Identity = id
	if !plan.DefaultMeetingTemplateId.Equal(state.DefaultMeetingTemplateId) {
		sp.DefaultMeetingTemplateId = plan.DefaultMeetingTemplateId.ValueString()
	}
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if v := plan.HiddenMeetingTemplates.ValueString(); v != "" {
		sp.HiddenMeetingTemplates = objectParam(v)
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsMeetingTemplatePermissionPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MeetingTemplatePermissionPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"DefaultMeetingTemplateId": cfg.DefaultMeetingTemplateId,
		"Description":              cfg.Description,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *meetingTemplatePermissionPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state meetingTemplatePermissionPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.identityOf(state) == "Global" {
		resp.Diagnostics.AddWarning("MeetingTemplatePermissionPolicy Global not deleted", "The Global MeetingTemplatePermissionPolicy is a built-in tenant singleton that cannot be removed. It has been dropped from Terraform state but remains unchanged in the tenant.")
		return
	}
	if _, err := r.client.CS.RemoveCsTeamsMeetingTemplatePermissionPolicy(ctx, cs.RemoveCsTeamsMeetingTemplatePermissionPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-MeetingTemplatePermissionPolicy failed", err.Error())
		}
	}
}

func (r *meetingTemplatePermissionPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *meetingTemplatePermissionPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan meetingTemplatePermissionPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity != "Global" {
		return
	}
	res, err := r.client.CS.GetCsTeamsMeetingTemplatePermissionPolicy(ctx, cs.GetCsTeamsMeetingTemplatePermissionPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur meetingTemplatePermissionPolicyModel
	readMeetingTemplatePermissionPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.DefaultMeetingTemplateId.IsUnknown() {
		plan.DefaultMeetingTemplateId = cur.DefaultMeetingTemplateId
	}
	if plan.Description.IsUnknown() {
		plan.Description = cur.Description
	}
	if plan.HiddenMeetingTemplates.IsUnknown() {
		plan.HiddenMeetingTemplates = cur.HiddenMeetingTemplates
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *meetingTemplatePermissionPolicyResource) identityOf(m meetingTemplatePermissionPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *meetingTemplatePermissionPolicyResource) refresh(ctx context.Context, identity string, m *meetingTemplatePermissionPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsMeetingTemplatePermissionPolicy(ctx, cs.GetCsTeamsMeetingTemplatePermissionPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MeetingTemplatePermissionPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMeetingTemplatePermissionPolicy(ctx, obj, m)
	return true
}

func readMeetingTemplatePermissionPolicy(ctx context.Context, obj map[string]any, m *meetingTemplatePermissionPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.DefaultMeetingTemplateId = types.StringValue(getString(obj, "DefaultMeetingTemplateId"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.HiddenMeetingTemplates = types.StringValue(getObjectJSON(obj, "HiddenMeetingTemplates"))
	_ = ctx
}

func (r *meetingTemplatePermissionPolicyResource) reconcileState(cfg, read *meetingTemplatePermissionPolicyModel) {
	read.DefaultMeetingTemplateId = reconcile.KeepStr(cfg.DefaultMeetingTemplateId, read.DefaultMeetingTemplateId)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.HiddenMeetingTemplates = reconcile.KeepStr(cfg.HiddenMeetingTemplates, read.HiddenMeetingTemplates)
}
