// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &meetingTemplatePermissionPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &meetingTemplatePermissionPolicyListDataSource{}
)

type meetingTemplatePermissionPolicyListDataSource struct{ client *clients.Client }

// NewMeetingTemplatePermissionPolicyListDataSource lists every MeetingTemplatePermissionPolicy object (Get-MeetingTemplatePermissionPolicy).
func NewMeetingTemplatePermissionPolicyListDataSource() datasource.DataSource {
	return &meetingTemplatePermissionPolicyListDataSource{}
}

type meetingTemplatePermissionPolicyListModel struct {
	Items []meetingTemplatePermissionPolicyModel `tfsdk:"meeting_template_permission_policies"`
}

func (d *meetingTemplatePermissionPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_meeting_template_permission_policies"
}

func (d *meetingTemplatePermissionPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every MeetingTemplatePermissionPolicy object (Get-MeetingTemplatePermissionPolicy).",
		Attributes: map[string]schema.Attribute{
			"meeting_template_permission_policies": schema.ListNestedAttribute{Computed: true, Description: "All MeetingTemplatePermissionPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                    schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"default_meeting_template_id": schema.StringAttribute{Computed: true, Description: "Maps to the -DefaultMeetingTemplateId parameter."},
				"description":                 schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
				"hidden_meeting_templates":    schema.StringAttribute{Computed: true, Description: "Maps to the -HiddenMeetingTemplates parameter."},
			}}},
		},
	}
}

func (d *meetingTemplatePermissionPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *meetingTemplatePermissionPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTeamsMeetingTemplatePermissionPolicy(ctx, cs.GetCsTeamsMeetingTemplatePermissionPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-MeetingTemplatePermissionPolicy failed", err.Error())
		return
	}
	var data meetingTemplatePermissionPolicyListModel
	for _, obj := range res.Value {
		var e meetingTemplatePermissionPolicyModel
		readMeetingTemplatePermissionPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
