// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &meetingConfigurationResource{}
	_ resource.ResourceWithConfigure   = &meetingConfigurationResource{}
	_ resource.ResourceWithImportState = &meetingConfigurationResource{}
	_ resource.ResourceWithModifyPlan  = &meetingConfigurationResource{}
)

type meetingConfigurationResource struct{ client *clients.Client }

// NewMeetingConfigurationResource manages the MeetingConfiguration configuration (Get-MeetingConfiguration / Set-MeetingConfiguration); it adopts the existing object and is not deleted on destroy.
func NewMeetingConfigurationResource() resource.Resource { return &meetingConfigurationResource{} }

type meetingConfigurationModel struct {
	ID                                     types.String `tfsdk:"id"`
	Identity                               types.String `tfsdk:"identity"`
	ClientAppSharingPort                   types.Int64  `tfsdk:"client_app_sharing_port"`
	ClientAppSharingPortRange              types.Int64  `tfsdk:"client_app_sharing_port_range"`
	ClientAudioPort                        types.Int64  `tfsdk:"client_audio_port"`
	ClientAudioPortRange                   types.Int64  `tfsdk:"client_audio_port_range"`
	ClientMediaPortRangeEnabled            types.Bool   `tfsdk:"client_media_port_range_enabled"`
	ClientVideoPort                        types.Int64  `tfsdk:"client_video_port"`
	ClientVideoPortRange                   types.Int64  `tfsdk:"client_video_port_range"`
	CustomFooterText                       types.String `tfsdk:"custom_footer_text"`
	DisableAnonymousJoin                   types.Bool   `tfsdk:"disable_anonymous_join"`
	DisableAppInteractionForAnonymousUsers types.Bool   `tfsdk:"disable_app_interaction_for_anonymous_users"`
	EnableAttributedTranscripts            types.Bool   `tfsdk:"enable_attributed_transcripts"`
	EnableGraphTranscriptAccess            types.Bool   `tfsdk:"enable_graph_transcript_access"`
	EnableQoS                              types.Bool   `tfsdk:"enable_qo_s"`
	FeedbackSurveyForAnonymousUsers        types.String `tfsdk:"feedback_survey_for_anonymous_users"`
	HelpURL                                types.String `tfsdk:"help_url"`
	LegalURL                               types.String `tfsdk:"legal_url"`
	LimitPresenterRolePermissions          types.Bool   `tfsdk:"limit_presenter_role_permissions"`
	LogoURL                                types.String `tfsdk:"logo_url"`
	PublishedEntraAuthenticationContexts   types.String `tfsdk:"published_entra_authentication_contexts"`
	ReportMeeting                          types.String `tfsdk:"report_meeting"`
}

func (r *meetingConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_meeting_configuration"
}

func (r *meetingConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MeetingConfiguration configuration via Set-CsTeamsMeetingConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                                          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                                    schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"client_app_sharing_port":                     schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -ClientAppSharingPort parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"client_app_sharing_port_range":               schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -ClientAppSharingPortRange parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"client_audio_port":                           schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -ClientAudioPort parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"client_audio_port_range":                     schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -ClientAudioPortRange parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"client_media_port_range_enabled":             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ClientMediaPortRangeEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"client_video_port":                           schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -ClientVideoPort parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"client_video_port_range":                     schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -ClientVideoPortRange parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"custom_footer_text":                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomFooterText parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"disable_anonymous_join":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DisableAnonymousJoin parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"disable_app_interaction_for_anonymous_users": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DisableAppInteractionForAnonymousUsers parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_attributed_transcripts":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableAttributedTranscripts parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_graph_transcript_access":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableGraphTranscriptAccess parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_qo_s":                                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableQoS parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"feedback_survey_for_anonymous_users":         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -FeedbackSurveyForAnonymousUsers parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"help_url":                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -HelpURL parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"legal_url":                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LegalURL parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"limit_presenter_role_permissions":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -LimitPresenterRolePermissions parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"logo_url":                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LogoURL parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"published_entra_authentication_contexts":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PublishedEntraAuthenticationContexts parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"report_meeting":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ReportMeeting parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *meetingConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *meetingConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan meetingConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config meetingConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsMeetingConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.ClientAppSharingPort.IsNull() {
		sp.ClientAppSharingPort = plan.ClientAppSharingPort.ValueInt64Pointer()
	}
	if !config.ClientAppSharingPortRange.IsNull() {
		sp.ClientAppSharingPortRange = plan.ClientAppSharingPortRange.ValueInt64Pointer()
	}
	if !config.ClientAudioPort.IsNull() {
		sp.ClientAudioPort = plan.ClientAudioPort.ValueInt64Pointer()
	}
	if !config.ClientAudioPortRange.IsNull() {
		sp.ClientAudioPortRange = plan.ClientAudioPortRange.ValueInt64Pointer()
	}
	if !config.ClientMediaPortRangeEnabled.IsNull() {
		sp.ClientMediaPortRangeEnabled = plan.ClientMediaPortRangeEnabled.ValueBoolPointer()
	}
	if !config.ClientVideoPort.IsNull() {
		sp.ClientVideoPort = plan.ClientVideoPort.ValueInt64Pointer()
	}
	if !config.ClientVideoPortRange.IsNull() {
		sp.ClientVideoPortRange = plan.ClientVideoPortRange.ValueInt64Pointer()
	}
	if !config.CustomFooterText.IsNull() {
		sp.CustomFooterText = plan.CustomFooterText.ValueString()
	}
	if !config.DisableAnonymousJoin.IsNull() {
		sp.DisableAnonymousJoin = plan.DisableAnonymousJoin.ValueBoolPointer()
	}
	if !config.DisableAppInteractionForAnonymousUsers.IsNull() {
		sp.DisableAppInteractionForAnonymousUsers = plan.DisableAppInteractionForAnonymousUsers.ValueBoolPointer()
	}
	if !config.EnableAttributedTranscripts.IsNull() {
		sp.EnableAttributedTranscripts = plan.EnableAttributedTranscripts.ValueBoolPointer()
	}
	if !config.EnableGraphTranscriptAccess.IsNull() {
		sp.EnableGraphTranscriptAccess = plan.EnableGraphTranscriptAccess.ValueBoolPointer()
	}
	if !config.EnableQoS.IsNull() {
		sp.EnableQoS = plan.EnableQoS.ValueBoolPointer()
	}
	if !config.FeedbackSurveyForAnonymousUsers.IsNull() {
		sp.FeedbackSurveyForAnonymousUsers = plan.FeedbackSurveyForAnonymousUsers.ValueString()
	}
	if !config.HelpURL.IsNull() {
		sp.HelpURL = plan.HelpURL.ValueString()
	}
	if !config.LegalURL.IsNull() {
		sp.LegalURL = plan.LegalURL.ValueString()
	}
	if !config.LimitPresenterRolePermissions.IsNull() {
		sp.LimitPresenterRolePermissions = plan.LimitPresenterRolePermissions.ValueBoolPointer()
	}
	if !config.LogoURL.IsNull() {
		sp.LogoURL = plan.LogoURL.ValueString()
	}
	if v := config.PublishedEntraAuthenticationContexts.ValueString(); v != "" {
		sp.PublishedEntraAuthenticationContexts = objectParam(v)
	}
	if !config.ReportMeeting.IsNull() {
		sp.ReportMeeting = plan.ReportMeeting.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsMeetingConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MeetingConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *meetingConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state meetingConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *meetingConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state meetingConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsMeetingConfigurationParams{}
	sp.Identity = id
	if !plan.ClientAppSharingPort.Equal(state.ClientAppSharingPort) {
		sp.ClientAppSharingPort = plan.ClientAppSharingPort.ValueInt64Pointer()
	}
	if !plan.ClientAppSharingPortRange.Equal(state.ClientAppSharingPortRange) {
		sp.ClientAppSharingPortRange = plan.ClientAppSharingPortRange.ValueInt64Pointer()
	}
	if !plan.ClientAudioPort.Equal(state.ClientAudioPort) {
		sp.ClientAudioPort = plan.ClientAudioPort.ValueInt64Pointer()
	}
	if !plan.ClientAudioPortRange.Equal(state.ClientAudioPortRange) {
		sp.ClientAudioPortRange = plan.ClientAudioPortRange.ValueInt64Pointer()
	}
	if !plan.ClientMediaPortRangeEnabled.Equal(state.ClientMediaPortRangeEnabled) {
		sp.ClientMediaPortRangeEnabled = plan.ClientMediaPortRangeEnabled.ValueBoolPointer()
	}
	if !plan.ClientVideoPort.Equal(state.ClientVideoPort) {
		sp.ClientVideoPort = plan.ClientVideoPort.ValueInt64Pointer()
	}
	if !plan.ClientVideoPortRange.Equal(state.ClientVideoPortRange) {
		sp.ClientVideoPortRange = plan.ClientVideoPortRange.ValueInt64Pointer()
	}
	if !plan.CustomFooterText.Equal(state.CustomFooterText) {
		sp.CustomFooterText = plan.CustomFooterText.ValueString()
	}
	if !plan.DisableAnonymousJoin.Equal(state.DisableAnonymousJoin) {
		sp.DisableAnonymousJoin = plan.DisableAnonymousJoin.ValueBoolPointer()
	}
	if !plan.DisableAppInteractionForAnonymousUsers.Equal(state.DisableAppInteractionForAnonymousUsers) {
		sp.DisableAppInteractionForAnonymousUsers = plan.DisableAppInteractionForAnonymousUsers.ValueBoolPointer()
	}
	if !plan.EnableAttributedTranscripts.Equal(state.EnableAttributedTranscripts) {
		sp.EnableAttributedTranscripts = plan.EnableAttributedTranscripts.ValueBoolPointer()
	}
	if !plan.EnableGraphTranscriptAccess.Equal(state.EnableGraphTranscriptAccess) {
		sp.EnableGraphTranscriptAccess = plan.EnableGraphTranscriptAccess.ValueBoolPointer()
	}
	if !plan.EnableQoS.Equal(state.EnableQoS) {
		sp.EnableQoS = plan.EnableQoS.ValueBoolPointer()
	}
	if !plan.FeedbackSurveyForAnonymousUsers.Equal(state.FeedbackSurveyForAnonymousUsers) {
		sp.FeedbackSurveyForAnonymousUsers = plan.FeedbackSurveyForAnonymousUsers.ValueString()
	}
	if !plan.HelpURL.Equal(state.HelpURL) {
		sp.HelpURL = plan.HelpURL.ValueString()
	}
	if !plan.LegalURL.Equal(state.LegalURL) {
		sp.LegalURL = plan.LegalURL.ValueString()
	}
	if !plan.LimitPresenterRolePermissions.Equal(state.LimitPresenterRolePermissions) {
		sp.LimitPresenterRolePermissions = plan.LimitPresenterRolePermissions.ValueBoolPointer()
	}
	if !plan.LogoURL.Equal(state.LogoURL) {
		sp.LogoURL = plan.LogoURL.ValueString()
	}
	if v := plan.PublishedEntraAuthenticationContexts.ValueString(); v != "" {
		sp.PublishedEntraAuthenticationContexts = objectParam(v)
	}
	if !plan.ReportMeeting.Equal(state.ReportMeeting) {
		sp.ReportMeeting = plan.ReportMeeting.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsMeetingConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MeetingConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"CustomFooterText":                cfg.CustomFooterText,
		"FeedbackSurveyForAnonymousUsers": cfg.FeedbackSurveyForAnonymousUsers,
		"HelpURL":                         cfg.HelpURL,
		"LegalURL":                        cfg.LegalURL,
		"LogoURL":                         cfg.LogoURL,
		"ReportMeeting":                   cfg.ReportMeeting,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *meetingConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("MeetingConfiguration configuration not deleted", "This resource manages an existing MeetingConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *meetingConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *meetingConfigurationResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan meetingConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.CS.GetCsTeamsMeetingConfiguration(ctx, cs.GetCsTeamsMeetingConfigurationParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur meetingConfigurationModel
	readMeetingConfiguration(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.ClientAppSharingPort.IsUnknown() {
		plan.ClientAppSharingPort = cur.ClientAppSharingPort
	}
	if plan.ClientAppSharingPortRange.IsUnknown() {
		plan.ClientAppSharingPortRange = cur.ClientAppSharingPortRange
	}
	if plan.ClientAudioPort.IsUnknown() {
		plan.ClientAudioPort = cur.ClientAudioPort
	}
	if plan.ClientAudioPortRange.IsUnknown() {
		plan.ClientAudioPortRange = cur.ClientAudioPortRange
	}
	if plan.ClientMediaPortRangeEnabled.IsUnknown() {
		plan.ClientMediaPortRangeEnabled = cur.ClientMediaPortRangeEnabled
	}
	if plan.ClientVideoPort.IsUnknown() {
		plan.ClientVideoPort = cur.ClientVideoPort
	}
	if plan.ClientVideoPortRange.IsUnknown() {
		plan.ClientVideoPortRange = cur.ClientVideoPortRange
	}
	if plan.CustomFooterText.IsUnknown() {
		plan.CustomFooterText = cur.CustomFooterText
	}
	if plan.DisableAnonymousJoin.IsUnknown() {
		plan.DisableAnonymousJoin = cur.DisableAnonymousJoin
	}
	if plan.DisableAppInteractionForAnonymousUsers.IsUnknown() {
		plan.DisableAppInteractionForAnonymousUsers = cur.DisableAppInteractionForAnonymousUsers
	}
	if plan.EnableAttributedTranscripts.IsUnknown() {
		plan.EnableAttributedTranscripts = cur.EnableAttributedTranscripts
	}
	if plan.EnableGraphTranscriptAccess.IsUnknown() {
		plan.EnableGraphTranscriptAccess = cur.EnableGraphTranscriptAccess
	}
	if plan.EnableQoS.IsUnknown() {
		plan.EnableQoS = cur.EnableQoS
	}
	if plan.FeedbackSurveyForAnonymousUsers.IsUnknown() {
		plan.FeedbackSurveyForAnonymousUsers = cur.FeedbackSurveyForAnonymousUsers
	}
	if plan.HelpURL.IsUnknown() {
		plan.HelpURL = cur.HelpURL
	}
	if plan.LegalURL.IsUnknown() {
		plan.LegalURL = cur.LegalURL
	}
	if plan.LimitPresenterRolePermissions.IsUnknown() {
		plan.LimitPresenterRolePermissions = cur.LimitPresenterRolePermissions
	}
	if plan.LogoURL.IsUnknown() {
		plan.LogoURL = cur.LogoURL
	}
	if plan.PublishedEntraAuthenticationContexts.IsUnknown() {
		plan.PublishedEntraAuthenticationContexts = cur.PublishedEntraAuthenticationContexts
	}
	if plan.ReportMeeting.IsUnknown() {
		plan.ReportMeeting = cur.ReportMeeting
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *meetingConfigurationResource) identityOf(m meetingConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *meetingConfigurationResource) refresh(ctx context.Context, identity string, m *meetingConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsMeetingConfiguration(ctx, cs.GetCsTeamsMeetingConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MeetingConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMeetingConfiguration(ctx, obj, m)
	return true
}

func readMeetingConfiguration(ctx context.Context, obj map[string]any, m *meetingConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.ClientAppSharingPort = types.Int64Value(getInt(obj, "ClientAppSharingPort"))
	m.ClientAppSharingPortRange = types.Int64Value(getInt(obj, "ClientAppSharingPortRange"))
	m.ClientAudioPort = types.Int64Value(getInt(obj, "ClientAudioPort"))
	m.ClientAudioPortRange = types.Int64Value(getInt(obj, "ClientAudioPortRange"))
	m.ClientMediaPortRangeEnabled = types.BoolValue(getBool(obj, "ClientMediaPortRangeEnabled"))
	m.ClientVideoPort = types.Int64Value(getInt(obj, "ClientVideoPort"))
	m.ClientVideoPortRange = types.Int64Value(getInt(obj, "ClientVideoPortRange"))
	m.CustomFooterText = types.StringValue(getString(obj, "CustomFooterText"))
	m.DisableAnonymousJoin = types.BoolValue(getBool(obj, "DisableAnonymousJoin"))
	m.DisableAppInteractionForAnonymousUsers = types.BoolValue(getBool(obj, "DisableAppInteractionForAnonymousUsers"))
	m.EnableAttributedTranscripts = types.BoolValue(getBool(obj, "EnableAttributedTranscripts"))
	m.EnableGraphTranscriptAccess = types.BoolValue(getBool(obj, "EnableGraphTranscriptAccess"))
	m.EnableQoS = types.BoolValue(getBool(obj, "EnableQoS"))
	m.FeedbackSurveyForAnonymousUsers = types.StringValue(getString(obj, "FeedbackSurveyForAnonymousUsers"))
	m.HelpURL = types.StringValue(getString(obj, "HelpURL"))
	m.LegalURL = types.StringValue(getString(obj, "LegalURL"))
	m.LimitPresenterRolePermissions = types.BoolValue(getBool(obj, "LimitPresenterRolePermissions"))
	m.LogoURL = types.StringValue(getString(obj, "LogoURL"))
	m.PublishedEntraAuthenticationContexts = types.StringValue(getObjectJSON(obj, "PublishedEntraAuthenticationContexts"))
	m.ReportMeeting = types.StringValue(getString(obj, "ReportMeeting"))
	_ = ctx
}

func (r *meetingConfigurationResource) reconcileState(cfg, read *meetingConfigurationModel) {
	read.ClientAppSharingPort = reconcile.KeepInt64(cfg.ClientAppSharingPort, read.ClientAppSharingPort)
	read.ClientAppSharingPortRange = reconcile.KeepInt64(cfg.ClientAppSharingPortRange, read.ClientAppSharingPortRange)
	read.ClientAudioPort = reconcile.KeepInt64(cfg.ClientAudioPort, read.ClientAudioPort)
	read.ClientAudioPortRange = reconcile.KeepInt64(cfg.ClientAudioPortRange, read.ClientAudioPortRange)
	read.ClientMediaPortRangeEnabled = reconcile.KeepBool(cfg.ClientMediaPortRangeEnabled, read.ClientMediaPortRangeEnabled)
	read.ClientVideoPort = reconcile.KeepInt64(cfg.ClientVideoPort, read.ClientVideoPort)
	read.ClientVideoPortRange = reconcile.KeepInt64(cfg.ClientVideoPortRange, read.ClientVideoPortRange)
	read.CustomFooterText = reconcile.KeepStr(cfg.CustomFooterText, read.CustomFooterText)
	read.DisableAnonymousJoin = reconcile.KeepBool(cfg.DisableAnonymousJoin, read.DisableAnonymousJoin)
	read.DisableAppInteractionForAnonymousUsers = reconcile.KeepBool(cfg.DisableAppInteractionForAnonymousUsers, read.DisableAppInteractionForAnonymousUsers)
	read.EnableAttributedTranscripts = reconcile.KeepBool(cfg.EnableAttributedTranscripts, read.EnableAttributedTranscripts)
	read.EnableGraphTranscriptAccess = reconcile.KeepBool(cfg.EnableGraphTranscriptAccess, read.EnableGraphTranscriptAccess)
	read.EnableQoS = reconcile.KeepBool(cfg.EnableQoS, read.EnableQoS)
	read.FeedbackSurveyForAnonymousUsers = reconcile.KeepStr(cfg.FeedbackSurveyForAnonymousUsers, read.FeedbackSurveyForAnonymousUsers)
	read.HelpURL = reconcile.KeepStr(cfg.HelpURL, read.HelpURL)
	read.LegalURL = reconcile.KeepStr(cfg.LegalURL, read.LegalURL)
	read.LimitPresenterRolePermissions = reconcile.KeepBool(cfg.LimitPresenterRolePermissions, read.LimitPresenterRolePermissions)
	read.LogoURL = reconcile.KeepStr(cfg.LogoURL, read.LogoURL)
	read.PublishedEntraAuthenticationContexts = reconcile.KeepStr(cfg.PublishedEntraAuthenticationContexts, read.PublishedEntraAuthenticationContexts)
	read.ReportMeeting = reconcile.KeepStr(cfg.ReportMeeting, read.ReportMeeting)
}
