// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &messagingPolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &messagingPolicyDataSource{}
)

type messagingPolicyDataSource struct{ client *clients.Client }

// NewMessagingPolicyDataSource looks up a MessagingPolicy object (Get-MessagingPolicy).
func NewMessagingPolicyDataSource() datasource.DataSource { return &messagingPolicyDataSource{} }

func (d *messagingPolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_messaging_policy"
}

func (d *messagingPolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing MessagingPolicy object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                    schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":              schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"allow_chat_with_group": schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowChatWithGroup parameter."},
			"allow_communication_compliance_end_user_reporting":     schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCommunicationComplianceEndUserReporting parameter."},
			"allow_custom_group_chat_avatars":                       schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowCustomGroupChatAvatars parameter."},
			"allow_fluid_collaborate":                               schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowFluidCollaborate parameter."},
			"allow_full_chat_permission_user_to_delete_any_message": schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowFullChatPermissionUserToDeleteAnyMessage parameter."},
			"allow_giphy":                            schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowGiphy parameter."},
			"allow_giphy_display":                    schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowGiphyDisplay parameter."},
			"allow_group_chat_join_links":            schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowGroupChatJoinLinks parameter."},
			"allow_immersive_reader":                 schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowImmersiveReader parameter."},
			"allow_memes":                            schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowMemes parameter."},
			"allow_owner_delete_message":             schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowOwnerDeleteMessage parameter."},
			"allow_paste_internet_image":             schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowPasteInternetImage parameter."},
			"allow_priority_messages":                schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowPriorityMessages parameter."},
			"allow_proactive_summaries":              schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowProactiveSummaries parameter."},
			"allow_remove_user":                      schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowRemoveUser parameter."},
			"allow_security_end_user_reporting":      schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowSecurityEndUserReporting parameter."},
			"allow_smart_compose":                    schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowSmartCompose parameter."},
			"allow_smart_reply":                      schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowSmartReply parameter."},
			"allow_stickers":                         schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowStickers parameter."},
			"allow_url_previews":                     schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowUrlPreviews parameter."},
			"allow_user_chat":                        schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowUserChat parameter."},
			"allow_user_delete_chat":                 schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowUserDeleteChat parameter."},
			"allow_user_delete_message":              schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowUserDeleteMessage parameter."},
			"allow_user_edit_message":                schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowUserEditMessage parameter."},
			"allow_user_translation":                 schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowUserTranslation parameter."},
			"allow_video_messages":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowVideoMessages parameter."},
			"audio_message_enabled_type":             schema.StringAttribute{Computed: true, Description: "Maps to the -AudioMessageEnabledType parameter."},
			"auto_share_files_in_external_chats":     schema.StringAttribute{Computed: true, Description: "Maps to the -AutoShareFilesInExternalChats parameter."},
			"channels_in_chat_list_enabled_type":     schema.StringAttribute{Computed: true, Description: "Maps to the -ChannelsInChatListEnabledType parameter."},
			"chat_permission_role":                   schema.StringAttribute{Computed: true, Description: "Maps to the -ChatPermissionRole parameter."},
			"create_custom_emojis":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -CreateCustomEmojis parameter."},
			"delete_custom_emojis":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -DeleteCustomEmojis parameter."},
			"description":                            schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"designer_for_backgrounds_and_images":    schema.StringAttribute{Computed: true, Description: "Maps to the -DesignerForBackgroundsAndImages parameter."},
			"giphy_rating_type":                      schema.StringAttribute{Computed: true, Description: "Maps to the -GiphyRatingType parameter."},
			"in_organization_chat_control":           schema.StringAttribute{Computed: true, Description: "Maps to the -InOrganizationChatControl parameter."},
			"read_receipts_enabled_type":             schema.StringAttribute{Computed: true, Description: "Maps to the -ReadReceiptsEnabledType parameter."},
			"use_b2_b_invites_to_add_external_users": schema.BoolAttribute{Computed: true, Description: "Maps to the -UseB2BInvitesToAddExternalUsers parameter."},
			"users_can_delete_bot_messages":          schema.BoolAttribute{Computed: true, Description: "Maps to the -UsersCanDeleteBotMessages parameter."},
		},
	}
}

func (d *messagingPolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *messagingPolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data messagingPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsTeamsMessagingPolicy(ctx, cs.GetCsTeamsMessagingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-MessagingPolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("MessagingPolicy not found", "no MessagingPolicy object for identity "+identity)
		return
	}
	readMessagingPolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
