// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &messagingPolicyResource{}
	_ resource.ResourceWithConfigure   = &messagingPolicyResource{}
	_ resource.ResourceWithImportState = &messagingPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &messagingPolicyResource{}
)

type messagingPolicyResource struct{ client *clients.Client }

// NewMessagingPolicyResource manages the MessagingPolicy object (New-MessagingPolicy / Get-MessagingPolicy / Set-MessagingPolicy / Remove-MessagingPolicy).
func NewMessagingPolicyResource() resource.Resource { return &messagingPolicyResource{} }

type messagingPolicyModel struct {
	ID                                            types.String `tfsdk:"id"`
	Identity                                      types.String `tfsdk:"identity"`
	AllowChatWithGroup                            types.Bool   `tfsdk:"allow_chat_with_group"`
	AllowCommunicationComplianceEndUserReporting  types.Bool   `tfsdk:"allow_communication_compliance_end_user_reporting"`
	AllowCustomGroupChatAvatars                   types.Bool   `tfsdk:"allow_custom_group_chat_avatars"`
	AllowFluidCollaborate                         types.Bool   `tfsdk:"allow_fluid_collaborate"`
	AllowFullChatPermissionUserToDeleteAnyMessage types.Bool   `tfsdk:"allow_full_chat_permission_user_to_delete_any_message"`
	AllowGiphy                                    types.Bool   `tfsdk:"allow_giphy"`
	AllowGiphyDisplay                             types.Bool   `tfsdk:"allow_giphy_display"`
	AllowGroupChatJoinLinks                       types.Bool   `tfsdk:"allow_group_chat_join_links"`
	AllowImmersiveReader                          types.Bool   `tfsdk:"allow_immersive_reader"`
	AllowMemes                                    types.Bool   `tfsdk:"allow_memes"`
	AllowOwnerDeleteMessage                       types.Bool   `tfsdk:"allow_owner_delete_message"`
	AllowPasteInternetImage                       types.Bool   `tfsdk:"allow_paste_internet_image"`
	AllowPriorityMessages                         types.Bool   `tfsdk:"allow_priority_messages"`
	AllowProactiveSummaries                       types.Bool   `tfsdk:"allow_proactive_summaries"`
	AllowRemoveUser                               types.Bool   `tfsdk:"allow_remove_user"`
	AllowSecurityEndUserReporting                 types.Bool   `tfsdk:"allow_security_end_user_reporting"`
	AllowSmartCompose                             types.Bool   `tfsdk:"allow_smart_compose"`
	AllowSmartReply                               types.Bool   `tfsdk:"allow_smart_reply"`
	AllowStickers                                 types.Bool   `tfsdk:"allow_stickers"`
	AllowUrlPreviews                              types.Bool   `tfsdk:"allow_url_previews"`
	AllowUserChat                                 types.Bool   `tfsdk:"allow_user_chat"`
	AllowUserDeleteChat                           types.Bool   `tfsdk:"allow_user_delete_chat"`
	AllowUserDeleteMessage                        types.Bool   `tfsdk:"allow_user_delete_message"`
	AllowUserEditMessage                          types.Bool   `tfsdk:"allow_user_edit_message"`
	AllowUserTranslation                          types.Bool   `tfsdk:"allow_user_translation"`
	AllowVideoMessages                            types.Bool   `tfsdk:"allow_video_messages"`
	AudioMessageEnabledType                       types.String `tfsdk:"audio_message_enabled_type"`
	AutoShareFilesInExternalChats                 types.String `tfsdk:"auto_share_files_in_external_chats"`
	ChannelsInChatListEnabledType                 types.String `tfsdk:"channels_in_chat_list_enabled_type"`
	ChatPermissionRole                            types.String `tfsdk:"chat_permission_role"`
	CreateCustomEmojis                            types.Bool   `tfsdk:"create_custom_emojis"`
	DeleteCustomEmojis                            types.Bool   `tfsdk:"delete_custom_emojis"`
	Description                                   types.String `tfsdk:"description"`
	DesignerForBackgroundsAndImages               types.String `tfsdk:"designer_for_backgrounds_and_images"`
	GiphyRatingType                               types.String `tfsdk:"giphy_rating_type"`
	InOrganizationChatControl                     types.String `tfsdk:"in_organization_chat_control"`
	ReadReceiptsEnabledType                       types.String `tfsdk:"read_receipts_enabled_type"`
	UseB2BInvitesToAddExternalUsers               types.Bool   `tfsdk:"use_b2_b_invites_to_add_external_users"`
	UsersCanDeleteBotMessages                     types.Bool   `tfsdk:"users_can_delete_bot_messages"`
}

func (r *messagingPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_messaging_policy"
}

func (r *messagingPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MessagingPolicy policy via New-CsTeamsMessagingPolicy / Get-CsTeamsMessagingPolicy / Set-CsTeamsMessagingPolicy / Remove-CsTeamsMessagingPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                    schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":              schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"allow_chat_with_group": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowChatWithGroup parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_communication_compliance_end_user_reporting":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowCommunicationComplianceEndUserReporting parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_custom_group_chat_avatars":                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowCustomGroupChatAvatars parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_fluid_collaborate":                               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowFluidCollaborate parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_full_chat_permission_user_to_delete_any_message": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowFullChatPermissionUserToDeleteAnyMessage parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_giphy":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowGiphy parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_giphy_display":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowGiphyDisplay parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_group_chat_join_links":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowGroupChatJoinLinks parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_immersive_reader":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowImmersiveReader parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_memes":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowMemes parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_owner_delete_message":             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowOwnerDeleteMessage parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_paste_internet_image":             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowPasteInternetImage parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_priority_messages":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowPriorityMessages parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_proactive_summaries":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowProactiveSummaries parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_remove_user":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowRemoveUser parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_security_end_user_reporting":      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowSecurityEndUserReporting parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_smart_compose":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowSmartCompose parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_smart_reply":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowSmartReply parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_stickers":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowStickers parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_url_previews":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowUrlPreviews parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_user_chat":                        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowUserChat parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_user_delete_chat":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowUserDeleteChat parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_user_delete_message":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowUserDeleteMessage parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_user_edit_message":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowUserEditMessage parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_user_translation":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowUserTranslation parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_video_messages":                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowVideoMessages parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"audio_message_enabled_type":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AudioMessageEnabledType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"auto_share_files_in_external_chats":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AutoShareFilesInExternalChats parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"channels_in_chat_list_enabled_type":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ChannelsInChatListEnabledType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"chat_permission_role":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ChatPermissionRole parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"create_custom_emojis":                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -CreateCustomEmojis parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"delete_custom_emojis":                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DeleteCustomEmojis parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"description":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"designer_for_backgrounds_and_images":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DesignerForBackgroundsAndImages parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"giphy_rating_type":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -GiphyRatingType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"in_organization_chat_control":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -InOrganizationChatControl parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"read_receipts_enabled_type":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ReadReceiptsEnabledType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"use_b2_b_invites_to_add_external_users": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UseB2BInvitesToAddExternalUsers parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"users_can_delete_bot_messages":          schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UsersCanDeleteBotMessages parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *messagingPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *messagingPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan messagingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config messagingPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if plan.Identity.ValueString() == "Global" {
		sp := cs.SetCsTeamsMessagingPolicyParams{}
		sp.Identity = plan.Identity.ValueString()
		if !config.AllowChatWithGroup.IsNull() {
			sp.AllowChatWithGroup = plan.AllowChatWithGroup.ValueBoolPointer()
		}
		if !config.AllowCommunicationComplianceEndUserReporting.IsNull() {
			sp.AllowCommunicationComplianceEndUserReporting = plan.AllowCommunicationComplianceEndUserReporting.ValueBoolPointer()
		}
		if !config.AllowCustomGroupChatAvatars.IsNull() {
			sp.AllowCustomGroupChatAvatars = plan.AllowCustomGroupChatAvatars.ValueBoolPointer()
		}
		if !config.AllowFluidCollaborate.IsNull() {
			sp.AllowFluidCollaborate = plan.AllowFluidCollaborate.ValueBoolPointer()
		}
		if !config.AllowFullChatPermissionUserToDeleteAnyMessage.IsNull() {
			sp.AllowFullChatPermissionUserToDeleteAnyMessage = plan.AllowFullChatPermissionUserToDeleteAnyMessage.ValueBoolPointer()
		}
		if !config.AllowGiphy.IsNull() {
			sp.AllowGiphy = plan.AllowGiphy.ValueBoolPointer()
		}
		if !config.AllowGiphyDisplay.IsNull() {
			sp.AllowGiphyDisplay = plan.AllowGiphyDisplay.ValueBoolPointer()
		}
		if !config.AllowGroupChatJoinLinks.IsNull() {
			sp.AllowGroupChatJoinLinks = plan.AllowGroupChatJoinLinks.ValueBoolPointer()
		}
		if !config.AllowImmersiveReader.IsNull() {
			sp.AllowImmersiveReader = plan.AllowImmersiveReader.ValueBoolPointer()
		}
		if !config.AllowMemes.IsNull() {
			sp.AllowMemes = plan.AllowMemes.ValueBoolPointer()
		}
		if !config.AllowOwnerDeleteMessage.IsNull() {
			sp.AllowOwnerDeleteMessage = plan.AllowOwnerDeleteMessage.ValueBoolPointer()
		}
		if !config.AllowPasteInternetImage.IsNull() {
			sp.AllowPasteInternetImage = plan.AllowPasteInternetImage.ValueBoolPointer()
		}
		if !config.AllowPriorityMessages.IsNull() {
			sp.AllowPriorityMessages = plan.AllowPriorityMessages.ValueBoolPointer()
		}
		if !config.AllowProactiveSummaries.IsNull() {
			sp.AllowProactiveSummaries = plan.AllowProactiveSummaries.ValueBoolPointer()
		}
		if !config.AllowRemoveUser.IsNull() {
			sp.AllowRemoveUser = plan.AllowRemoveUser.ValueBoolPointer()
		}
		if !config.AllowSecurityEndUserReporting.IsNull() {
			sp.AllowSecurityEndUserReporting = plan.AllowSecurityEndUserReporting.ValueBoolPointer()
		}
		if !config.AllowSmartCompose.IsNull() {
			sp.AllowSmartCompose = plan.AllowSmartCompose.ValueBoolPointer()
		}
		if !config.AllowSmartReply.IsNull() {
			sp.AllowSmartReply = plan.AllowSmartReply.ValueBoolPointer()
		}
		if !config.AllowStickers.IsNull() {
			sp.AllowStickers = plan.AllowStickers.ValueBoolPointer()
		}
		if !config.AllowUrlPreviews.IsNull() {
			sp.AllowUrlPreviews = plan.AllowUrlPreviews.ValueBoolPointer()
		}
		if !config.AllowUserChat.IsNull() {
			sp.AllowUserChat = plan.AllowUserChat.ValueBoolPointer()
		}
		if !config.AllowUserDeleteChat.IsNull() {
			sp.AllowUserDeleteChat = plan.AllowUserDeleteChat.ValueBoolPointer()
		}
		if !config.AllowUserDeleteMessage.IsNull() {
			sp.AllowUserDeleteMessage = plan.AllowUserDeleteMessage.ValueBoolPointer()
		}
		if !config.AllowUserEditMessage.IsNull() {
			sp.AllowUserEditMessage = plan.AllowUserEditMessage.ValueBoolPointer()
		}
		if !config.AllowUserTranslation.IsNull() {
			sp.AllowUserTranslation = plan.AllowUserTranslation.ValueBoolPointer()
		}
		if !config.AllowVideoMessages.IsNull() {
			sp.AllowVideoMessages = plan.AllowVideoMessages.ValueBoolPointer()
		}
		if !config.AudioMessageEnabledType.IsNull() {
			sp.AudioMessageEnabledType = plan.AudioMessageEnabledType.ValueString()
		}
		if !config.AutoShareFilesInExternalChats.IsNull() {
			sp.AutoShareFilesInExternalChats = plan.AutoShareFilesInExternalChats.ValueString()
		}
		if !config.ChannelsInChatListEnabledType.IsNull() {
			sp.ChannelsInChatListEnabledType = plan.ChannelsInChatListEnabledType.ValueString()
		}
		if !config.ChatPermissionRole.IsNull() {
			sp.ChatPermissionRole = plan.ChatPermissionRole.ValueString()
		}
		if !config.CreateCustomEmojis.IsNull() {
			sp.CreateCustomEmojis = plan.CreateCustomEmojis.ValueBoolPointer()
		}
		if !config.DeleteCustomEmojis.IsNull() {
			sp.DeleteCustomEmojis = plan.DeleteCustomEmojis.ValueBoolPointer()
		}
		if !config.Description.IsNull() {
			sp.Description = plan.Description.ValueString()
		}
		if !config.DesignerForBackgroundsAndImages.IsNull() {
			sp.DesignerForBackgroundsAndImages = plan.DesignerForBackgroundsAndImages.ValueString()
		}
		if !config.GiphyRatingType.IsNull() {
			sp.GiphyRatingType = plan.GiphyRatingType.ValueString()
		}
		if !config.InOrganizationChatControl.IsNull() {
			sp.InOrganizationChatControl = plan.InOrganizationChatControl.ValueString()
		}
		if !config.ReadReceiptsEnabledType.IsNull() {
			sp.ReadReceiptsEnabledType = plan.ReadReceiptsEnabledType.ValueString()
		}
		if !config.UseB2BInvitesToAddExternalUsers.IsNull() {
			sp.UseB2BInvitesToAddExternalUsers = plan.UseB2BInvitesToAddExternalUsers.ValueBoolPointer()
		}
		if !config.UsersCanDeleteBotMessages.IsNull() {
			sp.UsersCanDeleteBotMessages = plan.UsersCanDeleteBotMessages.ValueBoolPointer()
		}
		if resp.Diagnostics.HasError() {
			return
		}
		if _, err := r.client.CS.SetCsTeamsMessagingPolicy(ctx, sp); err != nil {
			resp.Diagnostics.AddError("Set-MessagingPolicy failed", err.Error())
			return
		}
		cfg := plan
		ident := plan.Identity.ValueString()
		if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
			if !resp.Diagnostics.HasError() {
				resp.Diagnostics.AddError("MessagingPolicy not found", "identity Global does not exist and cannot be created")
			}
			return
		}
		r.reconcileState(&cfg, &plan)
		resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
		return
	}
	p := cs.NewCsTeamsMessagingPolicyParams{}
	if !config.AllowChatWithGroup.IsNull() {
		p.AllowChatWithGroup = plan.AllowChatWithGroup.ValueBoolPointer()
	}
	if !config.AllowCommunicationComplianceEndUserReporting.IsNull() {
		p.AllowCommunicationComplianceEndUserReporting = plan.AllowCommunicationComplianceEndUserReporting.ValueBoolPointer()
	}
	if !config.AllowCustomGroupChatAvatars.IsNull() {
		p.AllowCustomGroupChatAvatars = plan.AllowCustomGroupChatAvatars.ValueBoolPointer()
	}
	if !config.AllowFluidCollaborate.IsNull() {
		p.AllowFluidCollaborate = plan.AllowFluidCollaborate.ValueBoolPointer()
	}
	if !config.AllowFullChatPermissionUserToDeleteAnyMessage.IsNull() {
		p.AllowFullChatPermissionUserToDeleteAnyMessage = plan.AllowFullChatPermissionUserToDeleteAnyMessage.ValueBoolPointer()
	}
	if !config.AllowGiphy.IsNull() {
		p.AllowGiphy = plan.AllowGiphy.ValueBoolPointer()
	}
	if !config.AllowGiphyDisplay.IsNull() {
		p.AllowGiphyDisplay = plan.AllowGiphyDisplay.ValueBoolPointer()
	}
	if !config.AllowGroupChatJoinLinks.IsNull() {
		p.AllowGroupChatJoinLinks = plan.AllowGroupChatJoinLinks.ValueBoolPointer()
	}
	if !config.AllowImmersiveReader.IsNull() {
		p.AllowImmersiveReader = plan.AllowImmersiveReader.ValueBoolPointer()
	}
	if !config.AllowMemes.IsNull() {
		p.AllowMemes = plan.AllowMemes.ValueBoolPointer()
	}
	if !config.AllowOwnerDeleteMessage.IsNull() {
		p.AllowOwnerDeleteMessage = plan.AllowOwnerDeleteMessage.ValueBoolPointer()
	}
	if !config.AllowPasteInternetImage.IsNull() {
		p.AllowPasteInternetImage = plan.AllowPasteInternetImage.ValueBoolPointer()
	}
	if !config.AllowPriorityMessages.IsNull() {
		p.AllowPriorityMessages = plan.AllowPriorityMessages.ValueBoolPointer()
	}
	if !config.AllowProactiveSummaries.IsNull() {
		p.AllowProactiveSummaries = plan.AllowProactiveSummaries.ValueBoolPointer()
	}
	if !config.AllowRemoveUser.IsNull() {
		p.AllowRemoveUser = plan.AllowRemoveUser.ValueBoolPointer()
	}
	if !config.AllowSecurityEndUserReporting.IsNull() {
		p.AllowSecurityEndUserReporting = plan.AllowSecurityEndUserReporting.ValueBoolPointer()
	}
	if !config.AllowSmartCompose.IsNull() {
		p.AllowSmartCompose = plan.AllowSmartCompose.ValueBoolPointer()
	}
	if !config.AllowSmartReply.IsNull() {
		p.AllowSmartReply = plan.AllowSmartReply.ValueBoolPointer()
	}
	if !config.AllowStickers.IsNull() {
		p.AllowStickers = plan.AllowStickers.ValueBoolPointer()
	}
	if !config.AllowUrlPreviews.IsNull() {
		p.AllowUrlPreviews = plan.AllowUrlPreviews.ValueBoolPointer()
	}
	if !config.AllowUserChat.IsNull() {
		p.AllowUserChat = plan.AllowUserChat.ValueBoolPointer()
	}
	if !config.AllowUserDeleteChat.IsNull() {
		p.AllowUserDeleteChat = plan.AllowUserDeleteChat.ValueBoolPointer()
	}
	if !config.AllowUserDeleteMessage.IsNull() {
		p.AllowUserDeleteMessage = plan.AllowUserDeleteMessage.ValueBoolPointer()
	}
	if !config.AllowUserEditMessage.IsNull() {
		p.AllowUserEditMessage = plan.AllowUserEditMessage.ValueBoolPointer()
	}
	if !config.AllowUserTranslation.IsNull() {
		p.AllowUserTranslation = plan.AllowUserTranslation.ValueBoolPointer()
	}
	if !config.AllowVideoMessages.IsNull() {
		p.AllowVideoMessages = plan.AllowVideoMessages.ValueBoolPointer()
	}
	if !config.AudioMessageEnabledType.IsNull() {
		p.AudioMessageEnabledType = plan.AudioMessageEnabledType.ValueString()
	}
	if !config.AutoShareFilesInExternalChats.IsNull() {
		p.AutoShareFilesInExternalChats = plan.AutoShareFilesInExternalChats.ValueString()
	}
	if !config.ChannelsInChatListEnabledType.IsNull() {
		p.ChannelsInChatListEnabledType = plan.ChannelsInChatListEnabledType.ValueString()
	}
	if !config.ChatPermissionRole.IsNull() {
		p.ChatPermissionRole = plan.ChatPermissionRole.ValueString()
	}
	if !config.CreateCustomEmojis.IsNull() {
		p.CreateCustomEmojis = plan.CreateCustomEmojis.ValueBoolPointer()
	}
	if !config.DeleteCustomEmojis.IsNull() {
		p.DeleteCustomEmojis = plan.DeleteCustomEmojis.ValueBoolPointer()
	}
	if !config.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if !config.DesignerForBackgroundsAndImages.IsNull() {
		p.DesignerForBackgroundsAndImages = plan.DesignerForBackgroundsAndImages.ValueString()
	}
	if !config.GiphyRatingType.IsNull() {
		p.GiphyRatingType = plan.GiphyRatingType.ValueString()
	}
	if !config.InOrganizationChatControl.IsNull() {
		p.InOrganizationChatControl = plan.InOrganizationChatControl.ValueString()
	}
	if !config.ReadReceiptsEnabledType.IsNull() {
		p.ReadReceiptsEnabledType = plan.ReadReceiptsEnabledType.ValueString()
	}
	if !config.UseB2BInvitesToAddExternalUsers.IsNull() {
		p.UseB2BInvitesToAddExternalUsers = plan.UseB2BInvitesToAddExternalUsers.ValueBoolPointer()
	}
	if !config.UsersCanDeleteBotMessages.IsNull() {
		p.UsersCanDeleteBotMessages = plan.UsersCanDeleteBotMessages.ValueBoolPointer()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTeamsMessagingPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-MessagingPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-MessagingPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readMessagingPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *messagingPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state messagingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *messagingPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state messagingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsMessagingPolicyParams{}
	sp.Identity = id
	if !plan.AllowChatWithGroup.Equal(state.AllowChatWithGroup) {
		sp.AllowChatWithGroup = plan.AllowChatWithGroup.ValueBoolPointer()
	}
	if !plan.AllowCommunicationComplianceEndUserReporting.Equal(state.AllowCommunicationComplianceEndUserReporting) {
		sp.AllowCommunicationComplianceEndUserReporting = plan.AllowCommunicationComplianceEndUserReporting.ValueBoolPointer()
	}
	if !plan.AllowCustomGroupChatAvatars.Equal(state.AllowCustomGroupChatAvatars) {
		sp.AllowCustomGroupChatAvatars = plan.AllowCustomGroupChatAvatars.ValueBoolPointer()
	}
	if !plan.AllowFluidCollaborate.Equal(state.AllowFluidCollaborate) {
		sp.AllowFluidCollaborate = plan.AllowFluidCollaborate.ValueBoolPointer()
	}
	if !plan.AllowFullChatPermissionUserToDeleteAnyMessage.Equal(state.AllowFullChatPermissionUserToDeleteAnyMessage) {
		sp.AllowFullChatPermissionUserToDeleteAnyMessage = plan.AllowFullChatPermissionUserToDeleteAnyMessage.ValueBoolPointer()
	}
	if !plan.AllowGiphy.Equal(state.AllowGiphy) {
		sp.AllowGiphy = plan.AllowGiphy.ValueBoolPointer()
	}
	if !plan.AllowGiphyDisplay.Equal(state.AllowGiphyDisplay) {
		sp.AllowGiphyDisplay = plan.AllowGiphyDisplay.ValueBoolPointer()
	}
	if !plan.AllowGroupChatJoinLinks.Equal(state.AllowGroupChatJoinLinks) {
		sp.AllowGroupChatJoinLinks = plan.AllowGroupChatJoinLinks.ValueBoolPointer()
	}
	if !plan.AllowImmersiveReader.Equal(state.AllowImmersiveReader) {
		sp.AllowImmersiveReader = plan.AllowImmersiveReader.ValueBoolPointer()
	}
	if !plan.AllowMemes.Equal(state.AllowMemes) {
		sp.AllowMemes = plan.AllowMemes.ValueBoolPointer()
	}
	if !plan.AllowOwnerDeleteMessage.Equal(state.AllowOwnerDeleteMessage) {
		sp.AllowOwnerDeleteMessage = plan.AllowOwnerDeleteMessage.ValueBoolPointer()
	}
	if !plan.AllowPasteInternetImage.Equal(state.AllowPasteInternetImage) {
		sp.AllowPasteInternetImage = plan.AllowPasteInternetImage.ValueBoolPointer()
	}
	if !plan.AllowPriorityMessages.Equal(state.AllowPriorityMessages) {
		sp.AllowPriorityMessages = plan.AllowPriorityMessages.ValueBoolPointer()
	}
	if !plan.AllowProactiveSummaries.Equal(state.AllowProactiveSummaries) {
		sp.AllowProactiveSummaries = plan.AllowProactiveSummaries.ValueBoolPointer()
	}
	if !plan.AllowRemoveUser.Equal(state.AllowRemoveUser) {
		sp.AllowRemoveUser = plan.AllowRemoveUser.ValueBoolPointer()
	}
	if !plan.AllowSecurityEndUserReporting.Equal(state.AllowSecurityEndUserReporting) {
		sp.AllowSecurityEndUserReporting = plan.AllowSecurityEndUserReporting.ValueBoolPointer()
	}
	if !plan.AllowSmartCompose.Equal(state.AllowSmartCompose) {
		sp.AllowSmartCompose = plan.AllowSmartCompose.ValueBoolPointer()
	}
	if !plan.AllowSmartReply.Equal(state.AllowSmartReply) {
		sp.AllowSmartReply = plan.AllowSmartReply.ValueBoolPointer()
	}
	if !plan.AllowStickers.Equal(state.AllowStickers) {
		sp.AllowStickers = plan.AllowStickers.ValueBoolPointer()
	}
	if !plan.AllowUrlPreviews.Equal(state.AllowUrlPreviews) {
		sp.AllowUrlPreviews = plan.AllowUrlPreviews.ValueBoolPointer()
	}
	if !plan.AllowUserChat.Equal(state.AllowUserChat) {
		sp.AllowUserChat = plan.AllowUserChat.ValueBoolPointer()
	}
	if !plan.AllowUserDeleteChat.Equal(state.AllowUserDeleteChat) {
		sp.AllowUserDeleteChat = plan.AllowUserDeleteChat.ValueBoolPointer()
	}
	if !plan.AllowUserDeleteMessage.Equal(state.AllowUserDeleteMessage) {
		sp.AllowUserDeleteMessage = plan.AllowUserDeleteMessage.ValueBoolPointer()
	}
	if !plan.AllowUserEditMessage.Equal(state.AllowUserEditMessage) {
		sp.AllowUserEditMessage = plan.AllowUserEditMessage.ValueBoolPointer()
	}
	if !plan.AllowUserTranslation.Equal(state.AllowUserTranslation) {
		sp.AllowUserTranslation = plan.AllowUserTranslation.ValueBoolPointer()
	}
	if !plan.AllowVideoMessages.Equal(state.AllowVideoMessages) {
		sp.AllowVideoMessages = plan.AllowVideoMessages.ValueBoolPointer()
	}
	if !plan.AudioMessageEnabledType.Equal(state.AudioMessageEnabledType) {
		sp.AudioMessageEnabledType = plan.AudioMessageEnabledType.ValueString()
	}
	if !plan.AutoShareFilesInExternalChats.Equal(state.AutoShareFilesInExternalChats) {
		sp.AutoShareFilesInExternalChats = plan.AutoShareFilesInExternalChats.ValueString()
	}
	if !plan.ChannelsInChatListEnabledType.Equal(state.ChannelsInChatListEnabledType) {
		sp.ChannelsInChatListEnabledType = plan.ChannelsInChatListEnabledType.ValueString()
	}
	if !plan.ChatPermissionRole.Equal(state.ChatPermissionRole) {
		sp.ChatPermissionRole = plan.ChatPermissionRole.ValueString()
	}
	if !plan.CreateCustomEmojis.Equal(state.CreateCustomEmojis) {
		sp.CreateCustomEmojis = plan.CreateCustomEmojis.ValueBoolPointer()
	}
	if !plan.DeleteCustomEmojis.Equal(state.DeleteCustomEmojis) {
		sp.DeleteCustomEmojis = plan.DeleteCustomEmojis.ValueBoolPointer()
	}
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.DesignerForBackgroundsAndImages.Equal(state.DesignerForBackgroundsAndImages) {
		sp.DesignerForBackgroundsAndImages = plan.DesignerForBackgroundsAndImages.ValueString()
	}
	if !plan.GiphyRatingType.Equal(state.GiphyRatingType) {
		sp.GiphyRatingType = plan.GiphyRatingType.ValueString()
	}
	if !plan.InOrganizationChatControl.Equal(state.InOrganizationChatControl) {
		sp.InOrganizationChatControl = plan.InOrganizationChatControl.ValueString()
	}
	if !plan.ReadReceiptsEnabledType.Equal(state.ReadReceiptsEnabledType) {
		sp.ReadReceiptsEnabledType = plan.ReadReceiptsEnabledType.ValueString()
	}
	if !plan.UseB2BInvitesToAddExternalUsers.Equal(state.UseB2BInvitesToAddExternalUsers) {
		sp.UseB2BInvitesToAddExternalUsers = plan.UseB2BInvitesToAddExternalUsers.ValueBoolPointer()
	}
	if !plan.UsersCanDeleteBotMessages.Equal(state.UsersCanDeleteBotMessages) {
		sp.UsersCanDeleteBotMessages = plan.UsersCanDeleteBotMessages.ValueBoolPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsMessagingPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MessagingPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AudioMessageEnabledType":         cfg.AudioMessageEnabledType,
		"AutoShareFilesInExternalChats":   cfg.AutoShareFilesInExternalChats,
		"ChannelsInChatListEnabledType":   cfg.ChannelsInChatListEnabledType,
		"ChatPermissionRole":              cfg.ChatPermissionRole,
		"Description":                     cfg.Description,
		"DesignerForBackgroundsAndImages": cfg.DesignerForBackgroundsAndImages,
		"GiphyRatingType":                 cfg.GiphyRatingType,
		"InOrganizationChatControl":       cfg.InOrganizationChatControl,
		"ReadReceiptsEnabledType":         cfg.ReadReceiptsEnabledType,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *messagingPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state messagingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.identityOf(state) == "Global" {
		resp.Diagnostics.AddWarning("MessagingPolicy Global not deleted", "The Global MessagingPolicy is a built-in tenant singleton that cannot be removed. It has been dropped from Terraform state but remains unchanged in the tenant.")
		return
	}
	if _, err := r.client.CS.RemoveCsTeamsMessagingPolicy(ctx, cs.RemoveCsTeamsMessagingPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-MessagingPolicy failed", err.Error())
		}
	}
}

func (r *messagingPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *messagingPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan messagingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity != "Global" {
		return
	}
	res, err := r.client.CS.GetCsTeamsMessagingPolicy(ctx, cs.GetCsTeamsMessagingPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur messagingPolicyModel
	readMessagingPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AllowChatWithGroup.IsUnknown() {
		plan.AllowChatWithGroup = cur.AllowChatWithGroup
	}
	if plan.AllowCommunicationComplianceEndUserReporting.IsUnknown() {
		plan.AllowCommunicationComplianceEndUserReporting = cur.AllowCommunicationComplianceEndUserReporting
	}
	if plan.AllowCustomGroupChatAvatars.IsUnknown() {
		plan.AllowCustomGroupChatAvatars = cur.AllowCustomGroupChatAvatars
	}
	if plan.AllowFluidCollaborate.IsUnknown() {
		plan.AllowFluidCollaborate = cur.AllowFluidCollaborate
	}
	if plan.AllowFullChatPermissionUserToDeleteAnyMessage.IsUnknown() {
		plan.AllowFullChatPermissionUserToDeleteAnyMessage = cur.AllowFullChatPermissionUserToDeleteAnyMessage
	}
	if plan.AllowGiphy.IsUnknown() {
		plan.AllowGiphy = cur.AllowGiphy
	}
	if plan.AllowGiphyDisplay.IsUnknown() {
		plan.AllowGiphyDisplay = cur.AllowGiphyDisplay
	}
	if plan.AllowGroupChatJoinLinks.IsUnknown() {
		plan.AllowGroupChatJoinLinks = cur.AllowGroupChatJoinLinks
	}
	if plan.AllowImmersiveReader.IsUnknown() {
		plan.AllowImmersiveReader = cur.AllowImmersiveReader
	}
	if plan.AllowMemes.IsUnknown() {
		plan.AllowMemes = cur.AllowMemes
	}
	if plan.AllowOwnerDeleteMessage.IsUnknown() {
		plan.AllowOwnerDeleteMessage = cur.AllowOwnerDeleteMessage
	}
	if plan.AllowPasteInternetImage.IsUnknown() {
		plan.AllowPasteInternetImage = cur.AllowPasteInternetImage
	}
	if plan.AllowPriorityMessages.IsUnknown() {
		plan.AllowPriorityMessages = cur.AllowPriorityMessages
	}
	if plan.AllowProactiveSummaries.IsUnknown() {
		plan.AllowProactiveSummaries = cur.AllowProactiveSummaries
	}
	if plan.AllowRemoveUser.IsUnknown() {
		plan.AllowRemoveUser = cur.AllowRemoveUser
	}
	if plan.AllowSecurityEndUserReporting.IsUnknown() {
		plan.AllowSecurityEndUserReporting = cur.AllowSecurityEndUserReporting
	}
	if plan.AllowSmartCompose.IsUnknown() {
		plan.AllowSmartCompose = cur.AllowSmartCompose
	}
	if plan.AllowSmartReply.IsUnknown() {
		plan.AllowSmartReply = cur.AllowSmartReply
	}
	if plan.AllowStickers.IsUnknown() {
		plan.AllowStickers = cur.AllowStickers
	}
	if plan.AllowUrlPreviews.IsUnknown() {
		plan.AllowUrlPreviews = cur.AllowUrlPreviews
	}
	if plan.AllowUserChat.IsUnknown() {
		plan.AllowUserChat = cur.AllowUserChat
	}
	if plan.AllowUserDeleteChat.IsUnknown() {
		plan.AllowUserDeleteChat = cur.AllowUserDeleteChat
	}
	if plan.AllowUserDeleteMessage.IsUnknown() {
		plan.AllowUserDeleteMessage = cur.AllowUserDeleteMessage
	}
	if plan.AllowUserEditMessage.IsUnknown() {
		plan.AllowUserEditMessage = cur.AllowUserEditMessage
	}
	if plan.AllowUserTranslation.IsUnknown() {
		plan.AllowUserTranslation = cur.AllowUserTranslation
	}
	if plan.AllowVideoMessages.IsUnknown() {
		plan.AllowVideoMessages = cur.AllowVideoMessages
	}
	if plan.AudioMessageEnabledType.IsUnknown() {
		plan.AudioMessageEnabledType = cur.AudioMessageEnabledType
	}
	if plan.AutoShareFilesInExternalChats.IsUnknown() {
		plan.AutoShareFilesInExternalChats = cur.AutoShareFilesInExternalChats
	}
	if plan.ChannelsInChatListEnabledType.IsUnknown() {
		plan.ChannelsInChatListEnabledType = cur.ChannelsInChatListEnabledType
	}
	if plan.ChatPermissionRole.IsUnknown() {
		plan.ChatPermissionRole = cur.ChatPermissionRole
	}
	if plan.CreateCustomEmojis.IsUnknown() {
		plan.CreateCustomEmojis = cur.CreateCustomEmojis
	}
	if plan.DeleteCustomEmojis.IsUnknown() {
		plan.DeleteCustomEmojis = cur.DeleteCustomEmojis
	}
	if plan.Description.IsUnknown() {
		plan.Description = cur.Description
	}
	if plan.DesignerForBackgroundsAndImages.IsUnknown() {
		plan.DesignerForBackgroundsAndImages = cur.DesignerForBackgroundsAndImages
	}
	if plan.GiphyRatingType.IsUnknown() {
		plan.GiphyRatingType = cur.GiphyRatingType
	}
	if plan.InOrganizationChatControl.IsUnknown() {
		plan.InOrganizationChatControl = cur.InOrganizationChatControl
	}
	if plan.ReadReceiptsEnabledType.IsUnknown() {
		plan.ReadReceiptsEnabledType = cur.ReadReceiptsEnabledType
	}
	if plan.UseB2BInvitesToAddExternalUsers.IsUnknown() {
		plan.UseB2BInvitesToAddExternalUsers = cur.UseB2BInvitesToAddExternalUsers
	}
	if plan.UsersCanDeleteBotMessages.IsUnknown() {
		plan.UsersCanDeleteBotMessages = cur.UsersCanDeleteBotMessages
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *messagingPolicyResource) identityOf(m messagingPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *messagingPolicyResource) refresh(ctx context.Context, identity string, m *messagingPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsMessagingPolicy(ctx, cs.GetCsTeamsMessagingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MessagingPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMessagingPolicy(ctx, obj, m)
	return true
}

func readMessagingPolicy(ctx context.Context, obj map[string]any, m *messagingPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AllowChatWithGroup = types.BoolValue(getBool(obj, "AllowChatWithGroup"))
	m.AllowCommunicationComplianceEndUserReporting = types.BoolValue(getBool(obj, "AllowCommunicationComplianceEndUserReporting"))
	m.AllowCustomGroupChatAvatars = types.BoolValue(getBool(obj, "AllowCustomGroupChatAvatars"))
	m.AllowFluidCollaborate = types.BoolValue(getBool(obj, "AllowFluidCollaborate"))
	m.AllowFullChatPermissionUserToDeleteAnyMessage = types.BoolValue(getBool(obj, "AllowFullChatPermissionUserToDeleteAnyMessage"))
	m.AllowGiphy = types.BoolValue(getBool(obj, "AllowGiphy"))
	m.AllowGiphyDisplay = types.BoolValue(getBool(obj, "AllowGiphyDisplay"))
	m.AllowGroupChatJoinLinks = types.BoolValue(getBool(obj, "AllowGroupChatJoinLinks"))
	m.AllowImmersiveReader = types.BoolValue(getBool(obj, "AllowImmersiveReader"))
	m.AllowMemes = types.BoolValue(getBool(obj, "AllowMemes"))
	m.AllowOwnerDeleteMessage = types.BoolValue(getBool(obj, "AllowOwnerDeleteMessage"))
	m.AllowPasteInternetImage = types.BoolValue(getBool(obj, "AllowPasteInternetImage"))
	m.AllowPriorityMessages = types.BoolValue(getBool(obj, "AllowPriorityMessages"))
	m.AllowProactiveSummaries = types.BoolValue(getBool(obj, "AllowProactiveSummaries"))
	m.AllowRemoveUser = types.BoolValue(getBool(obj, "AllowRemoveUser"))
	m.AllowSecurityEndUserReporting = types.BoolValue(getBool(obj, "AllowSecurityEndUserReporting"))
	m.AllowSmartCompose = types.BoolValue(getBool(obj, "AllowSmartCompose"))
	m.AllowSmartReply = types.BoolValue(getBool(obj, "AllowSmartReply"))
	m.AllowStickers = types.BoolValue(getBool(obj, "AllowStickers"))
	m.AllowUrlPreviews = types.BoolValue(getBool(obj, "AllowUrlPreviews"))
	m.AllowUserChat = types.BoolValue(getBool(obj, "AllowUserChat"))
	m.AllowUserDeleteChat = types.BoolValue(getBool(obj, "AllowUserDeleteChat"))
	m.AllowUserDeleteMessage = types.BoolValue(getBool(obj, "AllowUserDeleteMessage"))
	m.AllowUserEditMessage = types.BoolValue(getBool(obj, "AllowUserEditMessage"))
	m.AllowUserTranslation = types.BoolValue(getBool(obj, "AllowUserTranslation"))
	m.AllowVideoMessages = types.BoolValue(getBool(obj, "AllowVideoMessages"))
	m.AudioMessageEnabledType = types.StringValue(getString(obj, "AudioMessageEnabledType"))
	m.AutoShareFilesInExternalChats = types.StringValue(getString(obj, "AutoShareFilesInExternalChats"))
	m.ChannelsInChatListEnabledType = types.StringValue(getString(obj, "ChannelsInChatListEnabledType"))
	m.ChatPermissionRole = types.StringValue(getString(obj, "ChatPermissionRole"))
	m.CreateCustomEmojis = types.BoolValue(getBool(obj, "CreateCustomEmojis"))
	m.DeleteCustomEmojis = types.BoolValue(getBool(obj, "DeleteCustomEmojis"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.DesignerForBackgroundsAndImages = types.StringValue(getString(obj, "DesignerForBackgroundsAndImages"))
	m.GiphyRatingType = types.StringValue(getString(obj, "GiphyRatingType"))
	m.InOrganizationChatControl = types.StringValue(getString(obj, "InOrganizationChatControl"))
	m.ReadReceiptsEnabledType = types.StringValue(getString(obj, "ReadReceiptsEnabledType"))
	m.UseB2BInvitesToAddExternalUsers = types.BoolValue(getBool(obj, "UseB2BInvitesToAddExternalUsers"))
	m.UsersCanDeleteBotMessages = types.BoolValue(getBool(obj, "UsersCanDeleteBotMessages"))
	_ = ctx
}

func (r *messagingPolicyResource) reconcileState(cfg, read *messagingPolicyModel) {
	read.AllowChatWithGroup = reconcile.KeepBool(cfg.AllowChatWithGroup, read.AllowChatWithGroup)
	read.AllowCommunicationComplianceEndUserReporting = reconcile.KeepBool(cfg.AllowCommunicationComplianceEndUserReporting, read.AllowCommunicationComplianceEndUserReporting)
	read.AllowCustomGroupChatAvatars = reconcile.KeepBool(cfg.AllowCustomGroupChatAvatars, read.AllowCustomGroupChatAvatars)
	read.AllowFluidCollaborate = reconcile.KeepBool(cfg.AllowFluidCollaborate, read.AllowFluidCollaborate)
	read.AllowFullChatPermissionUserToDeleteAnyMessage = reconcile.KeepBool(cfg.AllowFullChatPermissionUserToDeleteAnyMessage, read.AllowFullChatPermissionUserToDeleteAnyMessage)
	read.AllowGiphy = reconcile.KeepBool(cfg.AllowGiphy, read.AllowGiphy)
	read.AllowGiphyDisplay = reconcile.KeepBool(cfg.AllowGiphyDisplay, read.AllowGiphyDisplay)
	read.AllowGroupChatJoinLinks = reconcile.KeepBool(cfg.AllowGroupChatJoinLinks, read.AllowGroupChatJoinLinks)
	read.AllowImmersiveReader = reconcile.KeepBool(cfg.AllowImmersiveReader, read.AllowImmersiveReader)
	read.AllowMemes = reconcile.KeepBool(cfg.AllowMemes, read.AllowMemes)
	read.AllowOwnerDeleteMessage = reconcile.KeepBool(cfg.AllowOwnerDeleteMessage, read.AllowOwnerDeleteMessage)
	read.AllowPasteInternetImage = reconcile.KeepBool(cfg.AllowPasteInternetImage, read.AllowPasteInternetImage)
	read.AllowPriorityMessages = reconcile.KeepBool(cfg.AllowPriorityMessages, read.AllowPriorityMessages)
	read.AllowProactiveSummaries = reconcile.KeepBool(cfg.AllowProactiveSummaries, read.AllowProactiveSummaries)
	read.AllowRemoveUser = reconcile.KeepBool(cfg.AllowRemoveUser, read.AllowRemoveUser)
	read.AllowSecurityEndUserReporting = reconcile.KeepBool(cfg.AllowSecurityEndUserReporting, read.AllowSecurityEndUserReporting)
	read.AllowSmartCompose = reconcile.KeepBool(cfg.AllowSmartCompose, read.AllowSmartCompose)
	read.AllowSmartReply = reconcile.KeepBool(cfg.AllowSmartReply, read.AllowSmartReply)
	read.AllowStickers = reconcile.KeepBool(cfg.AllowStickers, read.AllowStickers)
	read.AllowUrlPreviews = reconcile.KeepBool(cfg.AllowUrlPreviews, read.AllowUrlPreviews)
	read.AllowUserChat = reconcile.KeepBool(cfg.AllowUserChat, read.AllowUserChat)
	read.AllowUserDeleteChat = reconcile.KeepBool(cfg.AllowUserDeleteChat, read.AllowUserDeleteChat)
	read.AllowUserDeleteMessage = reconcile.KeepBool(cfg.AllowUserDeleteMessage, read.AllowUserDeleteMessage)
	read.AllowUserEditMessage = reconcile.KeepBool(cfg.AllowUserEditMessage, read.AllowUserEditMessage)
	read.AllowUserTranslation = reconcile.KeepBool(cfg.AllowUserTranslation, read.AllowUserTranslation)
	read.AllowVideoMessages = reconcile.KeepBool(cfg.AllowVideoMessages, read.AllowVideoMessages)
	read.AudioMessageEnabledType = reconcile.KeepStr(cfg.AudioMessageEnabledType, read.AudioMessageEnabledType)
	read.AutoShareFilesInExternalChats = reconcile.KeepStr(cfg.AutoShareFilesInExternalChats, read.AutoShareFilesInExternalChats)
	read.ChannelsInChatListEnabledType = reconcile.KeepStr(cfg.ChannelsInChatListEnabledType, read.ChannelsInChatListEnabledType)
	read.ChatPermissionRole = reconcile.KeepStr(cfg.ChatPermissionRole, read.ChatPermissionRole)
	read.CreateCustomEmojis = reconcile.KeepBool(cfg.CreateCustomEmojis, read.CreateCustomEmojis)
	read.DeleteCustomEmojis = reconcile.KeepBool(cfg.DeleteCustomEmojis, read.DeleteCustomEmojis)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.DesignerForBackgroundsAndImages = reconcile.KeepStr(cfg.DesignerForBackgroundsAndImages, read.DesignerForBackgroundsAndImages)
	read.GiphyRatingType = reconcile.KeepStr(cfg.GiphyRatingType, read.GiphyRatingType)
	read.InOrganizationChatControl = reconcile.KeepStr(cfg.InOrganizationChatControl, read.InOrganizationChatControl)
	read.ReadReceiptsEnabledType = reconcile.KeepStr(cfg.ReadReceiptsEnabledType, read.ReadReceiptsEnabledType)
	read.UseB2BInvitesToAddExternalUsers = reconcile.KeepBool(cfg.UseB2BInvitesToAddExternalUsers, read.UseB2BInvitesToAddExternalUsers)
	read.UsersCanDeleteBotMessages = reconcile.KeepBool(cfg.UsersCanDeleteBotMessages, read.UsersCanDeleteBotMessages)
}
