// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &mobilityPolicyResource{}
	_ resource.ResourceWithConfigure   = &mobilityPolicyResource{}
	_ resource.ResourceWithImportState = &mobilityPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &mobilityPolicyResource{}
)

type mobilityPolicyResource struct{ client *clients.Client }

// NewMobilityPolicyResource manages the MobilityPolicy object (New-MobilityPolicy / Get-MobilityPolicy / Set-MobilityPolicy / Remove-MobilityPolicy).
func NewMobilityPolicyResource() resource.Resource { return &mobilityPolicyResource{} }

type mobilityPolicyModel struct {
	ID                     types.String `tfsdk:"id"`
	Identity               types.String `tfsdk:"identity"`
	Description            types.String `tfsdk:"description"`
	IPAudioMobileMode      types.String `tfsdk:"ip_audio_mobile_mode"`
	IPVideoMobileMode      types.String `tfsdk:"ip_video_mobile_mode"`
	LinksInTeams           types.String `tfsdk:"links_in_teams"`
	MobileDialerPreference types.String `tfsdk:"mobile_dialer_preference"`
}

func (r *mobilityPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mobility_policy"
}

func (r *mobilityPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MobilityPolicy policy via New-CsTeamsMobilityPolicy / Get-CsTeamsMobilityPolicy / Set-CsTeamsMobilityPolicy / Remove-CsTeamsMobilityPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                 schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description":              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"ip_audio_mobile_mode":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -IPAudioMobileMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"ip_video_mobile_mode":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -IPVideoMobileMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"links_in_teams":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LinksInTeams parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"mobile_dialer_preference": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MobileDialerPreference parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *mobilityPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *mobilityPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mobilityPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config mobilityPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if plan.Identity.ValueString() == "Global" {
		sp := cs.SetCsTeamsMobilityPolicyParams{}
		sp.Identity = plan.Identity.ValueString()
		if !config.Description.IsNull() {
			sp.Description = plan.Description.ValueString()
		}
		if !config.IPAudioMobileMode.IsNull() {
			sp.IPAudioMobileMode = plan.IPAudioMobileMode.ValueString()
		}
		if !config.IPVideoMobileMode.IsNull() {
			sp.IPVideoMobileMode = plan.IPVideoMobileMode.ValueString()
		}
		if !config.LinksInTeams.IsNull() {
			sp.LinksInTeams = plan.LinksInTeams.ValueString()
		}
		if !config.MobileDialerPreference.IsNull() {
			sp.MobileDialerPreference = plan.MobileDialerPreference.ValueString()
		}
		if resp.Diagnostics.HasError() {
			return
		}
		if _, err := r.client.CS.SetCsTeamsMobilityPolicy(ctx, sp); err != nil {
			resp.Diagnostics.AddError("Set-MobilityPolicy failed", err.Error())
			return
		}
		cfg := plan
		ident := plan.Identity.ValueString()
		if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
			if !resp.Diagnostics.HasError() {
				resp.Diagnostics.AddError("MobilityPolicy not found", "identity Global does not exist and cannot be created")
			}
			return
		}
		r.reconcileState(&cfg, &plan)
		resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
		return
	}
	p := cs.NewCsTeamsMobilityPolicyParams{}
	if !config.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if !config.IPAudioMobileMode.IsNull() {
		p.IPAudioMobileMode = plan.IPAudioMobileMode.ValueString()
	}
	if !config.IPVideoMobileMode.IsNull() {
		p.IPVideoMobileMode = plan.IPVideoMobileMode.ValueString()
	}
	if !config.LinksInTeams.IsNull() {
		p.LinksInTeams = plan.LinksInTeams.ValueString()
	}
	if !config.MobileDialerPreference.IsNull() {
		p.MobileDialerPreference = plan.MobileDialerPreference.ValueString()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTeamsMobilityPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-MobilityPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-MobilityPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readMobilityPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mobilityPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mobilityPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mobilityPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mobilityPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsMobilityPolicyParams{}
	sp.Identity = id
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.IPAudioMobileMode.Equal(state.IPAudioMobileMode) {
		sp.IPAudioMobileMode = plan.IPAudioMobileMode.ValueString()
	}
	if !plan.IPVideoMobileMode.Equal(state.IPVideoMobileMode) {
		sp.IPVideoMobileMode = plan.IPVideoMobileMode.ValueString()
	}
	if !plan.LinksInTeams.Equal(state.LinksInTeams) {
		sp.LinksInTeams = plan.LinksInTeams.ValueString()
	}
	if !plan.MobileDialerPreference.Equal(state.MobileDialerPreference) {
		sp.MobileDialerPreference = plan.MobileDialerPreference.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsMobilityPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MobilityPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Description":            cfg.Description,
		"IPAudioMobileMode":      cfg.IPAudioMobileMode,
		"IPVideoMobileMode":      cfg.IPVideoMobileMode,
		"LinksInTeams":           cfg.LinksInTeams,
		"MobileDialerPreference": cfg.MobileDialerPreference,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mobilityPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state mobilityPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.identityOf(state) == "Global" {
		resp.Diagnostics.AddWarning("MobilityPolicy Global not deleted", "The Global MobilityPolicy is a built-in tenant singleton that cannot be removed. It has been dropped from Terraform state but remains unchanged in the tenant.")
		return
	}
	if _, err := r.client.CS.RemoveCsTeamsMobilityPolicy(ctx, cs.RemoveCsTeamsMobilityPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-MobilityPolicy failed", err.Error())
		}
	}
}

func (r *mobilityPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *mobilityPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan mobilityPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity != "Global" {
		return
	}
	res, err := r.client.CS.GetCsTeamsMobilityPolicy(ctx, cs.GetCsTeamsMobilityPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur mobilityPolicyModel
	readMobilityPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.Description.IsUnknown() {
		plan.Description = cur.Description
	}
	if plan.IPAudioMobileMode.IsUnknown() {
		plan.IPAudioMobileMode = cur.IPAudioMobileMode
	}
	if plan.IPVideoMobileMode.IsUnknown() {
		plan.IPVideoMobileMode = cur.IPVideoMobileMode
	}
	if plan.LinksInTeams.IsUnknown() {
		plan.LinksInTeams = cur.LinksInTeams
	}
	if plan.MobileDialerPreference.IsUnknown() {
		plan.MobileDialerPreference = cur.MobileDialerPreference
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *mobilityPolicyResource) identityOf(m mobilityPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *mobilityPolicyResource) refresh(ctx context.Context, identity string, m *mobilityPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsMobilityPolicy(ctx, cs.GetCsTeamsMobilityPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MobilityPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMobilityPolicy(ctx, obj, m)
	return true
}

func readMobilityPolicy(ctx context.Context, obj map[string]any, m *mobilityPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.IPAudioMobileMode = types.StringValue(getString(obj, "IPAudioMobileMode"))
	m.IPVideoMobileMode = types.StringValue(getString(obj, "IPVideoMobileMode"))
	m.LinksInTeams = types.StringValue(getString(obj, "LinksInTeams"))
	m.MobileDialerPreference = types.StringValue(getString(obj, "MobileDialerPreference"))
	_ = ctx
}

func (r *mobilityPolicyResource) reconcileState(cfg, read *mobilityPolicyModel) {
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.IPAudioMobileMode = reconcile.KeepStr(cfg.IPAudioMobileMode, read.IPAudioMobileMode)
	read.IPVideoMobileMode = reconcile.KeepStr(cfg.IPVideoMobileMode, read.IPVideoMobileMode)
	read.LinksInTeams = reconcile.KeepStr(cfg.LinksInTeams, read.LinksInTeams)
	read.MobileDialerPreference = reconcile.KeepStr(cfg.MobileDialerPreference, read.MobileDialerPreference)
}
