// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &notificationAndFeedsPolicyResource{}
	_ resource.ResourceWithConfigure   = &notificationAndFeedsPolicyResource{}
	_ resource.ResourceWithImportState = &notificationAndFeedsPolicyResource{}
)

type notificationAndFeedsPolicyResource struct{ client *clients.Client }

// NewNotificationAndFeedsPolicyResource manages the NotificationAndFeedsPolicy configuration (Get-NotificationAndFeedsPolicy / Set-NotificationAndFeedsPolicy); it adopts the existing object and is not deleted on destroy.
func NewNotificationAndFeedsPolicyResource() resource.Resource {
	return &notificationAndFeedsPolicyResource{}
}

type notificationAndFeedsPolicyModel struct {
	ID                        types.String `tfsdk:"id"`
	Identity                  types.String `tfsdk:"identity"`
	Description               types.String `tfsdk:"description"`
	SuggestedFeedsEnabledType types.String `tfsdk:"suggested_feeds_enabled_type"`
	TrendingFeedsEnabledType  types.String `tfsdk:"trending_feeds_enabled_type"`
}

func (r *notificationAndFeedsPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_and_feeds_policy"
}

func (r *notificationAndFeedsPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the NotificationAndFeedsPolicy configuration via Set-CsTeamsNotificationAndFeedsPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                     schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"suggested_feeds_enabled_type": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SuggestedFeedsEnabledType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"trending_feeds_enabled_type":  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TrendingFeedsEnabledType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *notificationAndFeedsPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *notificationAndFeedsPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan notificationAndFeedsPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsNotificationAndFeedsPolicyParams{}
	sp.Identity = plan.Identity.ValueString()
	if !plan.Description.IsUnknown() && !plan.Description.IsNull() {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.SuggestedFeedsEnabledType.IsUnknown() && !plan.SuggestedFeedsEnabledType.IsNull() {
		sp.SuggestedFeedsEnabledType = plan.SuggestedFeedsEnabledType.ValueString()
	}
	if !plan.TrendingFeedsEnabledType.IsUnknown() && !plan.TrendingFeedsEnabledType.IsNull() {
		sp.TrendingFeedsEnabledType = plan.TrendingFeedsEnabledType.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsNotificationAndFeedsPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-NotificationAndFeedsPolicy failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *notificationAndFeedsPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state notificationAndFeedsPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *notificationAndFeedsPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state notificationAndFeedsPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsNotificationAndFeedsPolicyParams{}
	sp.Identity = id
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.SuggestedFeedsEnabledType.Equal(state.SuggestedFeedsEnabledType) {
		sp.SuggestedFeedsEnabledType = plan.SuggestedFeedsEnabledType.ValueString()
	}
	if !plan.TrendingFeedsEnabledType.Equal(state.TrendingFeedsEnabledType) {
		sp.TrendingFeedsEnabledType = plan.TrendingFeedsEnabledType.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsNotificationAndFeedsPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-NotificationAndFeedsPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Description":               cfg.Description,
		"SuggestedFeedsEnabledType": cfg.SuggestedFeedsEnabledType,
		"TrendingFeedsEnabledType":  cfg.TrendingFeedsEnabledType,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *notificationAndFeedsPolicyResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("NotificationAndFeedsPolicy configuration not deleted", "This resource manages an existing NotificationAndFeedsPolicy configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *notificationAndFeedsPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *notificationAndFeedsPolicyResource) identityOf(m notificationAndFeedsPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *notificationAndFeedsPolicyResource) refresh(ctx context.Context, identity string, m *notificationAndFeedsPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsNotificationAndFeedsPolicy(ctx, cs.GetCsTeamsNotificationAndFeedsPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-NotificationAndFeedsPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readNotificationAndFeedsPolicy(ctx, obj, m)
	return true
}

func readNotificationAndFeedsPolicy(ctx context.Context, obj map[string]any, m *notificationAndFeedsPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.SuggestedFeedsEnabledType = types.StringValue(getString(obj, "SuggestedFeedsEnabledType"))
	m.TrendingFeedsEnabledType = types.StringValue(getString(obj, "TrendingFeedsEnabledType"))
	_ = ctx
}

func (r *notificationAndFeedsPolicyResource) reconcileState(cfg, read *notificationAndFeedsPolicyModel) {
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.SuggestedFeedsEnabledType = reconcile.KeepStr(cfg.SuggestedFeedsEnabledType, read.SuggestedFeedsEnabledType)
	read.TrendingFeedsEnabledType = reconcile.KeepStr(cfg.TrendingFeedsEnabledType, read.TrendingFeedsEnabledType)
}
