// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &onlineUserListDataSource{}
	_ datasource.DataSourceWithConfigure = &onlineUserListDataSource{}
)

type onlineUserListDataSource struct{ client *clients.Client }

// NewOnlineUserListDataSource lists every OnlineUser object (Get-OnlineUser).
func NewOnlineUserListDataSource() datasource.DataSource { return &onlineUserListDataSource{} }

type onlineUserListModel struct {
	Items []onlineUserModel `tfsdk:"online_users"`
}

func (d *onlineUserListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_online_users"
}

func (d *onlineUserListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every OnlineUser object (Get-OnlineUser).",
		Attributes: map[string]schema.Attribute{
			"online_users": schema.ListNestedAttribute{Computed: true, Description: "All OnlineUser objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"name":         schema.StringAttribute{Computed: true, Description: "Name of the object."},
				"display_name": schema.StringAttribute{Computed: true, Description: "Display name of the object."},
				"json":         schema.StringAttribute{Computed: true, Description: "The full object encoded as JSON; decode with jsondecode()."},
			}}},
		},
	}
}

func (d *onlineUserListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *onlineUserListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsOnlineUser(ctx, cs.GetCsOnlineUserParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-OnlineUser failed", err.Error())
		return
	}
	var data onlineUserListModel
	for _, obj := range res.Value {
		var e onlineUserModel
		readOnlineUser(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
