// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &onlineDialInConferencingTenantSettingsDataSource{}
	_ datasource.DataSourceWithConfigure = &onlineDialInConferencingTenantSettingsDataSource{}
)

type onlineDialInConferencingTenantSettingsDataSource struct{ client *clients.Client }

// NewOnlineDialInConferencingTenantSettingsDataSource looks up a OnlineDialInConferencingTenantSettings object (Get-OnlineDialInConferencingTenantSettings).
func NewOnlineDialInConferencingTenantSettingsDataSource() datasource.DataSource {
	return &onlineDialInConferencingTenantSettingsDataSource{}
}

func (d *onlineDialInConferencingTenantSettingsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_online_dial_in_conferencing_tenant_settings"
}

func (d *onlineDialInConferencingTenantSettingsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing OnlineDialInConferencingTenantSettings object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity": schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"allow_federated_users_to_dial_out_to_self":        schema.StringAttribute{Computed: true, Description: "Maps to the -AllowFederatedUsersToDialOutToSelf parameter."},
			"allow_federated_users_to_dial_out_to_third_party": schema.StringAttribute{Computed: true, Description: "Maps to the -AllowFederatedUsersToDialOutToThirdParty parameter."},
			"allow_pstn_only_meetings_by_default":              schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowPSTNOnlyMeetingsByDefault parameter."},
			"allowed_dial_out_external_domains":                schema.StringAttribute{Computed: true, Description: "Maps to the -AllowedDialOutExternalDomains parameter."},
			"automatically_migrate_user_meetings":              schema.BoolAttribute{Computed: true, Description: "Maps to the -AutomaticallyMigrateUserMeetings parameter."},
			"automatically_replace_acp_provider":               schema.BoolAttribute{Computed: true, Description: "Maps to the -AutomaticallyReplaceAcpProvider parameter."},
			"automatically_send_emails_to_users":               schema.BoolAttribute{Computed: true, Description: "Maps to the -AutomaticallySendEmailsToUsers parameter."},
			"dynamic_caller_id_mode":                           schema.StringAttribute{Computed: true, Description: "Maps to the -DynamicCallerIdMode parameter."},
			"enable_dial_out_join_confirmation":                schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableDialOutJoinConfirmation parameter."},
			"enable_entry_exit_notifications":                  schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableEntryExitNotifications parameter."},
			"enable_name_recording":                            schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableNameRecording parameter."},
			"entry_exit_announcements_type":                    schema.StringAttribute{Computed: true, Description: "Maps to the -EntryExitAnnouncementsType parameter."},
			"include_toll_free_number_in_meeting_invites":      schema.BoolAttribute{Computed: true, Description: "Maps to the -IncludeTollFreeNumberInMeetingInvites parameter."},
			"mask_pstn_numbers_type":                           schema.StringAttribute{Computed: true, Description: "Maps to the -MaskPstnNumbersType parameter."},
			"migrate_service_numbers_on_cross_forest_move":     schema.BoolAttribute{Computed: true, Description: "Maps to the -MigrateServiceNumbersOnCrossForestMove parameter."},
			"pin_length":                   schema.Int64Attribute{Computed: true, Description: "Maps to the -PinLength parameter."},
			"send_email_from_address":      schema.StringAttribute{Computed: true, Description: "Maps to the -SendEmailFromAddress parameter."},
			"send_email_from_display_name": schema.StringAttribute{Computed: true, Description: "Maps to the -SendEmailFromDisplayName parameter."},
			"send_email_from_override":     schema.BoolAttribute{Computed: true, Description: "Maps to the -SendEmailFromOverride parameter."},
			"use_unique_conference_ids":    schema.BoolAttribute{Computed: true, Description: "Maps to the -UseUniqueConferenceIds parameter."},
		},
	}
}

func (d *onlineDialInConferencingTenantSettingsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *onlineDialInConferencingTenantSettingsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data onlineDialInConferencingTenantSettingsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsOnlineDialInConferencingTenantSettings(ctx, cs.GetCsOnlineDialInConferencingTenantSettingsParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-OnlineDialInConferencingTenantSettings failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("OnlineDialInConferencingTenantSettings not found", "no OnlineDialInConferencingTenantSettings object for identity "+identity)
		return
	}
	readOnlineDialInConferencingTenantSettings(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
