// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &onlineDialInConferencingTenantSettingsResource{}
	_ resource.ResourceWithConfigure   = &onlineDialInConferencingTenantSettingsResource{}
	_ resource.ResourceWithImportState = &onlineDialInConferencingTenantSettingsResource{}
)

type onlineDialInConferencingTenantSettingsResource struct{ client *clients.Client }

// NewOnlineDialInConferencingTenantSettingsResource manages the OnlineDialInConferencingTenantSettings configuration (Get-OnlineDialInConferencingTenantSettings / Set-OnlineDialInConferencingTenantSettings); it adopts the existing object and is not deleted on destroy.
func NewOnlineDialInConferencingTenantSettingsResource() resource.Resource {
	return &onlineDialInConferencingTenantSettingsResource{}
}

type onlineDialInConferencingTenantSettingsModel struct {
	ID                                       types.String `tfsdk:"id"`
	Identity                                 types.String `tfsdk:"identity"`
	AllowFederatedUsersToDialOutToSelf       types.String `tfsdk:"allow_federated_users_to_dial_out_to_self"`
	AllowFederatedUsersToDialOutToThirdParty types.String `tfsdk:"allow_federated_users_to_dial_out_to_third_party"`
	AllowPSTNOnlyMeetingsByDefault           types.Bool   `tfsdk:"allow_pstn_only_meetings_by_default"`
	AllowedDialOutExternalDomains            types.String `tfsdk:"allowed_dial_out_external_domains"`
	AutomaticallyMigrateUserMeetings         types.Bool   `tfsdk:"automatically_migrate_user_meetings"`
	AutomaticallyReplaceAcpProvider          types.Bool   `tfsdk:"automatically_replace_acp_provider"`
	AutomaticallySendEmailsToUsers           types.Bool   `tfsdk:"automatically_send_emails_to_users"`
	DynamicCallerIdMode                      types.String `tfsdk:"dynamic_caller_id_mode"`
	EnableDialOutJoinConfirmation            types.Bool   `tfsdk:"enable_dial_out_join_confirmation"`
	EnableEntryExitNotifications             types.Bool   `tfsdk:"enable_entry_exit_notifications"`
	EnableNameRecording                      types.Bool   `tfsdk:"enable_name_recording"`
	EntryExitAnnouncementsType               types.String `tfsdk:"entry_exit_announcements_type"`
	IncludeTollFreeNumberInMeetingInvites    types.Bool   `tfsdk:"include_toll_free_number_in_meeting_invites"`
	MaskPstnNumbersType                      types.String `tfsdk:"mask_pstn_numbers_type"`
	MigrateServiceNumbersOnCrossForestMove   types.Bool   `tfsdk:"migrate_service_numbers_on_cross_forest_move"`
	PinLength                                types.Int64  `tfsdk:"pin_length"`
	SendEmailFromAddress                     types.String `tfsdk:"send_email_from_address"`
	SendEmailFromDisplayName                 types.String `tfsdk:"send_email_from_display_name"`
	SendEmailFromOverride                    types.Bool   `tfsdk:"send_email_from_override"`
	UseUniqueConferenceIds                   types.Bool   `tfsdk:"use_unique_conference_ids"`
}

func (r *onlineDialInConferencingTenantSettingsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_online_dial_in_conferencing_tenant_settings"
}

func (r *onlineDialInConferencingTenantSettingsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the OnlineDialInConferencingTenantSettings configuration via Set-CsOnlineDialInConferencingTenantSettings.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"allow_federated_users_to_dial_out_to_self":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowFederatedUsersToDialOutToSelf parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"allow_federated_users_to_dial_out_to_third_party": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowFederatedUsersToDialOutToThirdParty parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"allow_pstn_only_meetings_by_default":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowPSTNOnlyMeetingsByDefault parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allowed_dial_out_external_domains":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowedDialOutExternalDomains parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"automatically_migrate_user_meetings":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutomaticallyMigrateUserMeetings parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"automatically_replace_acp_provider":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutomaticallyReplaceAcpProvider parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"automatically_send_emails_to_users":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutomaticallySendEmailsToUsers parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"dynamic_caller_id_mode":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DynamicCallerIdMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enable_dial_out_join_confirmation":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableDialOutJoinConfirmation parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_entry_exit_notifications":                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableEntryExitNotifications parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_name_recording":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableNameRecording parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"entry_exit_announcements_type":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EntryExitAnnouncementsType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"include_toll_free_number_in_meeting_invites":      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IncludeTollFreeNumberInMeetingInvites parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"mask_pstn_numbers_type":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MaskPstnNumbersType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"migrate_service_numbers_on_cross_forest_move":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -MigrateServiceNumbersOnCrossForestMove parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"pin_length":                   schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -PinLength parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"send_email_from_address":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SendEmailFromAddress parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"send_email_from_display_name": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SendEmailFromDisplayName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"send_email_from_override":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SendEmailFromOverride parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"use_unique_conference_ids":    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UseUniqueConferenceIds parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *onlineDialInConferencingTenantSettingsResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *onlineDialInConferencingTenantSettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan onlineDialInConferencingTenantSettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsOnlineDialInConferencingTenantSettingsParams{}
	sp.Identity = plan.Identity.ValueString()
	if !plan.AllowFederatedUsersToDialOutToSelf.IsUnknown() && !plan.AllowFederatedUsersToDialOutToSelf.IsNull() {
		sp.AllowFederatedUsersToDialOutToSelf = plan.AllowFederatedUsersToDialOutToSelf.ValueString()
	}
	if !plan.AllowFederatedUsersToDialOutToThirdParty.IsUnknown() && !plan.AllowFederatedUsersToDialOutToThirdParty.IsNull() {
		sp.AllowFederatedUsersToDialOutToThirdParty = plan.AllowFederatedUsersToDialOutToThirdParty.ValueString()
	}
	if !plan.AllowPSTNOnlyMeetingsByDefault.IsUnknown() && !plan.AllowPSTNOnlyMeetingsByDefault.IsNull() {
		sp.AllowPSTNOnlyMeetingsByDefault = plan.AllowPSTNOnlyMeetingsByDefault.ValueBoolPointer()
	}
	if v := plan.AllowedDialOutExternalDomains.ValueString(); v != "" {
		sp.AllowedDialOutExternalDomains = v
	}
	if !plan.AutomaticallyMigrateUserMeetings.IsUnknown() && !plan.AutomaticallyMigrateUserMeetings.IsNull() {
		sp.AutomaticallyMigrateUserMeetings = plan.AutomaticallyMigrateUserMeetings.ValueBoolPointer()
	}
	if !plan.AutomaticallyReplaceAcpProvider.IsUnknown() && !plan.AutomaticallyReplaceAcpProvider.IsNull() {
		sp.AutomaticallyReplaceAcpProvider = plan.AutomaticallyReplaceAcpProvider.ValueBoolPointer()
	}
	if !plan.AutomaticallySendEmailsToUsers.IsUnknown() && !plan.AutomaticallySendEmailsToUsers.IsNull() {
		sp.AutomaticallySendEmailsToUsers = plan.AutomaticallySendEmailsToUsers.ValueBoolPointer()
	}
	if !plan.DynamicCallerIdMode.IsUnknown() && !plan.DynamicCallerIdMode.IsNull() {
		sp.DynamicCallerIdMode = plan.DynamicCallerIdMode.ValueString()
	}
	if !plan.EnableDialOutJoinConfirmation.IsUnknown() && !plan.EnableDialOutJoinConfirmation.IsNull() {
		sp.EnableDialOutJoinConfirmation = plan.EnableDialOutJoinConfirmation.ValueBoolPointer()
	}
	if !plan.EnableEntryExitNotifications.IsUnknown() && !plan.EnableEntryExitNotifications.IsNull() {
		sp.EnableEntryExitNotifications = plan.EnableEntryExitNotifications.ValueBoolPointer()
	}
	if !plan.EnableNameRecording.IsUnknown() && !plan.EnableNameRecording.IsNull() {
		sp.EnableNameRecording = plan.EnableNameRecording.ValueBoolPointer()
	}
	if !plan.EntryExitAnnouncementsType.IsUnknown() && !plan.EntryExitAnnouncementsType.IsNull() {
		sp.EntryExitAnnouncementsType = plan.EntryExitAnnouncementsType.ValueString()
	}
	if !plan.IncludeTollFreeNumberInMeetingInvites.IsUnknown() && !plan.IncludeTollFreeNumberInMeetingInvites.IsNull() {
		sp.IncludeTollFreeNumberInMeetingInvites = plan.IncludeTollFreeNumberInMeetingInvites.ValueBoolPointer()
	}
	if !plan.MaskPstnNumbersType.IsUnknown() && !plan.MaskPstnNumbersType.IsNull() {
		sp.MaskPstnNumbersType = plan.MaskPstnNumbersType.ValueString()
	}
	if !plan.MigrateServiceNumbersOnCrossForestMove.IsUnknown() && !plan.MigrateServiceNumbersOnCrossForestMove.IsNull() {
		sp.MigrateServiceNumbersOnCrossForestMove = plan.MigrateServiceNumbersOnCrossForestMove.ValueBoolPointer()
	}
	if !plan.PinLength.IsUnknown() && !plan.PinLength.IsNull() {
		sp.PinLength = plan.PinLength.ValueInt64Pointer()
	}
	if !plan.SendEmailFromAddress.IsUnknown() && !plan.SendEmailFromAddress.IsNull() {
		sp.SendEmailFromAddress = plan.SendEmailFromAddress.ValueString()
	}
	if !plan.SendEmailFromDisplayName.IsUnknown() && !plan.SendEmailFromDisplayName.IsNull() {
		sp.SendEmailFromDisplayName = plan.SendEmailFromDisplayName.ValueString()
	}
	if !plan.SendEmailFromOverride.IsUnknown() && !plan.SendEmailFromOverride.IsNull() {
		sp.SendEmailFromOverride = plan.SendEmailFromOverride.ValueBoolPointer()
	}
	if !plan.UseUniqueConferenceIds.IsUnknown() && !plan.UseUniqueConferenceIds.IsNull() {
		sp.UseUniqueConferenceIds = plan.UseUniqueConferenceIds.ValueBoolPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsOnlineDialInConferencingTenantSettings(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-OnlineDialInConferencingTenantSettings failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *onlineDialInConferencingTenantSettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state onlineDialInConferencingTenantSettingsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *onlineDialInConferencingTenantSettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state onlineDialInConferencingTenantSettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsOnlineDialInConferencingTenantSettingsParams{}
	sp.Identity = id
	if !plan.AllowFederatedUsersToDialOutToSelf.Equal(state.AllowFederatedUsersToDialOutToSelf) {
		sp.AllowFederatedUsersToDialOutToSelf = plan.AllowFederatedUsersToDialOutToSelf.ValueString()
	}
	if !plan.AllowFederatedUsersToDialOutToThirdParty.Equal(state.AllowFederatedUsersToDialOutToThirdParty) {
		sp.AllowFederatedUsersToDialOutToThirdParty = plan.AllowFederatedUsersToDialOutToThirdParty.ValueString()
	}
	if !plan.AllowPSTNOnlyMeetingsByDefault.Equal(state.AllowPSTNOnlyMeetingsByDefault) {
		sp.AllowPSTNOnlyMeetingsByDefault = plan.AllowPSTNOnlyMeetingsByDefault.ValueBoolPointer()
	}
	if v := plan.AllowedDialOutExternalDomains.ValueString(); v != "" {
		sp.AllowedDialOutExternalDomains = v
	}
	if !plan.AutomaticallyMigrateUserMeetings.Equal(state.AutomaticallyMigrateUserMeetings) {
		sp.AutomaticallyMigrateUserMeetings = plan.AutomaticallyMigrateUserMeetings.ValueBoolPointer()
	}
	if !plan.AutomaticallyReplaceAcpProvider.Equal(state.AutomaticallyReplaceAcpProvider) {
		sp.AutomaticallyReplaceAcpProvider = plan.AutomaticallyReplaceAcpProvider.ValueBoolPointer()
	}
	if !plan.AutomaticallySendEmailsToUsers.Equal(state.AutomaticallySendEmailsToUsers) {
		sp.AutomaticallySendEmailsToUsers = plan.AutomaticallySendEmailsToUsers.ValueBoolPointer()
	}
	if !plan.DynamicCallerIdMode.Equal(state.DynamicCallerIdMode) {
		sp.DynamicCallerIdMode = plan.DynamicCallerIdMode.ValueString()
	}
	if !plan.EnableDialOutJoinConfirmation.Equal(state.EnableDialOutJoinConfirmation) {
		sp.EnableDialOutJoinConfirmation = plan.EnableDialOutJoinConfirmation.ValueBoolPointer()
	}
	if !plan.EnableEntryExitNotifications.Equal(state.EnableEntryExitNotifications) {
		sp.EnableEntryExitNotifications = plan.EnableEntryExitNotifications.ValueBoolPointer()
	}
	if !plan.EnableNameRecording.Equal(state.EnableNameRecording) {
		sp.EnableNameRecording = plan.EnableNameRecording.ValueBoolPointer()
	}
	if !plan.EntryExitAnnouncementsType.Equal(state.EntryExitAnnouncementsType) {
		sp.EntryExitAnnouncementsType = plan.EntryExitAnnouncementsType.ValueString()
	}
	if !plan.IncludeTollFreeNumberInMeetingInvites.Equal(state.IncludeTollFreeNumberInMeetingInvites) {
		sp.IncludeTollFreeNumberInMeetingInvites = plan.IncludeTollFreeNumberInMeetingInvites.ValueBoolPointer()
	}
	if !plan.MaskPstnNumbersType.Equal(state.MaskPstnNumbersType) {
		sp.MaskPstnNumbersType = plan.MaskPstnNumbersType.ValueString()
	}
	if !plan.MigrateServiceNumbersOnCrossForestMove.Equal(state.MigrateServiceNumbersOnCrossForestMove) {
		sp.MigrateServiceNumbersOnCrossForestMove = plan.MigrateServiceNumbersOnCrossForestMove.ValueBoolPointer()
	}
	if !plan.PinLength.Equal(state.PinLength) {
		sp.PinLength = plan.PinLength.ValueInt64Pointer()
	}
	if !plan.SendEmailFromAddress.Equal(state.SendEmailFromAddress) {
		sp.SendEmailFromAddress = plan.SendEmailFromAddress.ValueString()
	}
	if !plan.SendEmailFromDisplayName.Equal(state.SendEmailFromDisplayName) {
		sp.SendEmailFromDisplayName = plan.SendEmailFromDisplayName.ValueString()
	}
	if !plan.SendEmailFromOverride.Equal(state.SendEmailFromOverride) {
		sp.SendEmailFromOverride = plan.SendEmailFromOverride.ValueBoolPointer()
	}
	if !plan.UseUniqueConferenceIds.Equal(state.UseUniqueConferenceIds) {
		sp.UseUniqueConferenceIds = plan.UseUniqueConferenceIds.ValueBoolPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsOnlineDialInConferencingTenantSettings(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-OnlineDialInConferencingTenantSettings failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AllowFederatedUsersToDialOutToSelf":       cfg.AllowFederatedUsersToDialOutToSelf,
		"AllowFederatedUsersToDialOutToThirdParty": cfg.AllowFederatedUsersToDialOutToThirdParty,
		"AllowedDialOutExternalDomains":            cfg.AllowedDialOutExternalDomains,
		"DynamicCallerIdMode":                      cfg.DynamicCallerIdMode,
		"EntryExitAnnouncementsType":               cfg.EntryExitAnnouncementsType,
		"MaskPstnNumbersType":                      cfg.MaskPstnNumbersType,
		"SendEmailFromAddress":                     cfg.SendEmailFromAddress,
		"SendEmailFromDisplayName":                 cfg.SendEmailFromDisplayName,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *onlineDialInConferencingTenantSettingsResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("OnlineDialInConferencingTenantSettings configuration not deleted", "This resource manages an existing OnlineDialInConferencingTenantSettings configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *onlineDialInConferencingTenantSettingsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *onlineDialInConferencingTenantSettingsResource) identityOf(m onlineDialInConferencingTenantSettingsModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *onlineDialInConferencingTenantSettingsResource) refresh(ctx context.Context, identity string, m *onlineDialInConferencingTenantSettingsModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsOnlineDialInConferencingTenantSettings(ctx, cs.GetCsOnlineDialInConferencingTenantSettingsParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-OnlineDialInConferencingTenantSettings failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readOnlineDialInConferencingTenantSettings(ctx, obj, m)
	return true
}

func readOnlineDialInConferencingTenantSettings(ctx context.Context, obj map[string]any, m *onlineDialInConferencingTenantSettingsModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AllowFederatedUsersToDialOutToSelf = types.StringValue(getString(obj, "AllowFederatedUsersToDialOutToSelf"))
	m.AllowFederatedUsersToDialOutToThirdParty = types.StringValue(getString(obj, "AllowFederatedUsersToDialOutToThirdParty"))
	m.AllowPSTNOnlyMeetingsByDefault = types.BoolValue(getBool(obj, "AllowPSTNOnlyMeetingsByDefault"))
	m.AllowedDialOutExternalDomains = types.StringValue(getString(obj, "AllowedDialOutExternalDomains"))
	m.AutomaticallyMigrateUserMeetings = types.BoolValue(getBool(obj, "AutomaticallyMigrateUserMeetings"))
	m.AutomaticallyReplaceAcpProvider = types.BoolValue(getBool(obj, "AutomaticallyReplaceAcpProvider"))
	m.AutomaticallySendEmailsToUsers = types.BoolValue(getBool(obj, "AutomaticallySendEmailsToUsers"))
	m.DynamicCallerIdMode = types.StringValue(getString(obj, "DynamicCallerIdMode"))
	m.EnableDialOutJoinConfirmation = types.BoolValue(getBool(obj, "EnableDialOutJoinConfirmation"))
	m.EnableEntryExitNotifications = types.BoolValue(getBool(obj, "EnableEntryExitNotifications"))
	m.EnableNameRecording = types.BoolValue(getBool(obj, "EnableNameRecording"))
	m.EntryExitAnnouncementsType = types.StringValue(getString(obj, "EntryExitAnnouncementsType"))
	m.IncludeTollFreeNumberInMeetingInvites = types.BoolValue(getBool(obj, "IncludeTollFreeNumberInMeetingInvites"))
	m.MaskPstnNumbersType = types.StringValue(getString(obj, "MaskPstnNumbersType"))
	m.MigrateServiceNumbersOnCrossForestMove = types.BoolValue(getBool(obj, "MigrateServiceNumbersOnCrossForestMove"))
	m.PinLength = types.Int64Value(getInt(obj, "PinLength"))
	m.SendEmailFromAddress = types.StringValue(getString(obj, "SendEmailFromAddress"))
	m.SendEmailFromDisplayName = types.StringValue(getString(obj, "SendEmailFromDisplayName"))
	m.SendEmailFromOverride = types.BoolValue(getBool(obj, "SendEmailFromOverride"))
	m.UseUniqueConferenceIds = types.BoolValue(getBool(obj, "UseUniqueConferenceIds"))
	_ = ctx
}

func (r *onlineDialInConferencingTenantSettingsResource) reconcileState(cfg, read *onlineDialInConferencingTenantSettingsModel) {
	read.AllowFederatedUsersToDialOutToSelf = reconcile.KeepStr(cfg.AllowFederatedUsersToDialOutToSelf, read.AllowFederatedUsersToDialOutToSelf)
	read.AllowFederatedUsersToDialOutToThirdParty = reconcile.KeepStr(cfg.AllowFederatedUsersToDialOutToThirdParty, read.AllowFederatedUsersToDialOutToThirdParty)
	read.AllowPSTNOnlyMeetingsByDefault = reconcile.KeepBool(cfg.AllowPSTNOnlyMeetingsByDefault, read.AllowPSTNOnlyMeetingsByDefault)
	read.AllowedDialOutExternalDomains = reconcile.KeepStr(cfg.AllowedDialOutExternalDomains, read.AllowedDialOutExternalDomains)
	read.AutomaticallyMigrateUserMeetings = reconcile.KeepBool(cfg.AutomaticallyMigrateUserMeetings, read.AutomaticallyMigrateUserMeetings)
	read.AutomaticallyReplaceAcpProvider = reconcile.KeepBool(cfg.AutomaticallyReplaceAcpProvider, read.AutomaticallyReplaceAcpProvider)
	read.AutomaticallySendEmailsToUsers = reconcile.KeepBool(cfg.AutomaticallySendEmailsToUsers, read.AutomaticallySendEmailsToUsers)
	read.DynamicCallerIdMode = reconcile.KeepStr(cfg.DynamicCallerIdMode, read.DynamicCallerIdMode)
	read.EnableDialOutJoinConfirmation = reconcile.KeepBool(cfg.EnableDialOutJoinConfirmation, read.EnableDialOutJoinConfirmation)
	read.EnableEntryExitNotifications = reconcile.KeepBool(cfg.EnableEntryExitNotifications, read.EnableEntryExitNotifications)
	read.EnableNameRecording = reconcile.KeepBool(cfg.EnableNameRecording, read.EnableNameRecording)
	read.EntryExitAnnouncementsType = reconcile.KeepStr(cfg.EntryExitAnnouncementsType, read.EntryExitAnnouncementsType)
	read.IncludeTollFreeNumberInMeetingInvites = reconcile.KeepBool(cfg.IncludeTollFreeNumberInMeetingInvites, read.IncludeTollFreeNumberInMeetingInvites)
	read.MaskPstnNumbersType = reconcile.KeepStr(cfg.MaskPstnNumbersType, read.MaskPstnNumbersType)
	read.MigrateServiceNumbersOnCrossForestMove = reconcile.KeepBool(cfg.MigrateServiceNumbersOnCrossForestMove, read.MigrateServiceNumbersOnCrossForestMove)
	read.PinLength = reconcile.KeepInt64(cfg.PinLength, read.PinLength)
	read.SendEmailFromAddress = reconcile.KeepStr(cfg.SendEmailFromAddress, read.SendEmailFromAddress)
	read.SendEmailFromDisplayName = reconcile.KeepStr(cfg.SendEmailFromDisplayName, read.SendEmailFromDisplayName)
	read.SendEmailFromOverride = reconcile.KeepBool(cfg.SendEmailFromOverride, read.SendEmailFromOverride)
	read.UseUniqueConferenceIds = reconcile.KeepBool(cfg.UseUniqueConferenceIds, read.UseUniqueConferenceIds)
}
