// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &onlineVoiceRoutingPolicyResource{}
	_ resource.ResourceWithConfigure   = &onlineVoiceRoutingPolicyResource{}
	_ resource.ResourceWithImportState = &onlineVoiceRoutingPolicyResource{}
)

type onlineVoiceRoutingPolicyResource struct{ client *clients.Client }

// NewOnlineVoiceRoutingPolicyResource manages the OnlineVoiceRoutingPolicy object (New-OnlineVoiceRoutingPolicy / Get-OnlineVoiceRoutingPolicy / Set-OnlineVoiceRoutingPolicy / Remove-OnlineVoiceRoutingPolicy).
func NewOnlineVoiceRoutingPolicyResource() resource.Resource {
	return &onlineVoiceRoutingPolicyResource{}
}

type onlineVoiceRoutingPolicyModel struct {
	ID               types.String `tfsdk:"id"`
	Identity         types.String `tfsdk:"identity"`
	Description      types.String `tfsdk:"description"`
	OnlinePstnUsages types.String `tfsdk:"online_pstn_usages"`
	RouteType        types.String `tfsdk:"route_type"`
}

func (r *onlineVoiceRoutingPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_online_voice_routing_policy"
}

func (r *onlineVoiceRoutingPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the OnlineVoiceRoutingPolicy policy via New-CsOnlineVoiceRoutingPolicy / Get-CsOnlineVoiceRoutingPolicy / Set-CsOnlineVoiceRoutingPolicy / Remove-CsOnlineVoiceRoutingPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":           schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"online_pstn_usages": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -OnlinePstnUsages parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"route_type":         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RouteType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *onlineVoiceRoutingPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *onlineVoiceRoutingPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan onlineVoiceRoutingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := cs.NewCsOnlineVoiceRoutingPolicyParams{}
	if !plan.Description.IsUnknown() && !plan.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if v := plan.OnlinePstnUsages.ValueString(); v != "" {
		p.OnlinePstnUsages = v
	}
	if !plan.RouteType.IsUnknown() && !plan.RouteType.IsNull() {
		p.RouteType = plan.RouteType.ValueString()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsOnlineVoiceRoutingPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-OnlineVoiceRoutingPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-OnlineVoiceRoutingPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readOnlineVoiceRoutingPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *onlineVoiceRoutingPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state onlineVoiceRoutingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *onlineVoiceRoutingPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state onlineVoiceRoutingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsOnlineVoiceRoutingPolicyParams{}
	sp.Identity = id
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if v := plan.OnlinePstnUsages.ValueString(); v != "" {
		sp.OnlinePstnUsages = v
	}
	if !plan.RouteType.Equal(state.RouteType) {
		sp.RouteType = plan.RouteType.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsOnlineVoiceRoutingPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-OnlineVoiceRoutingPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Description":      cfg.Description,
		"OnlinePstnUsages": cfg.OnlinePstnUsages,
		"RouteType":        cfg.RouteType,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *onlineVoiceRoutingPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state onlineVoiceRoutingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.RemoveCsOnlineVoiceRoutingPolicy(ctx, cs.RemoveCsOnlineVoiceRoutingPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-OnlineVoiceRoutingPolicy failed", err.Error())
		}
	}
}

func (r *onlineVoiceRoutingPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *onlineVoiceRoutingPolicyResource) identityOf(m onlineVoiceRoutingPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *onlineVoiceRoutingPolicyResource) refresh(ctx context.Context, identity string, m *onlineVoiceRoutingPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsOnlineVoiceRoutingPolicy(ctx, cs.GetCsOnlineVoiceRoutingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-OnlineVoiceRoutingPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readOnlineVoiceRoutingPolicy(ctx, obj, m)
	return true
}

func readOnlineVoiceRoutingPolicy(ctx context.Context, obj map[string]any, m *onlineVoiceRoutingPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.OnlinePstnUsages = types.StringValue(getString(obj, "OnlinePstnUsages"))
	m.RouteType = types.StringValue(getString(obj, "RouteType"))
	_ = ctx
}

func (r *onlineVoiceRoutingPolicyResource) reconcileState(cfg, read *onlineVoiceRoutingPolicyModel) {
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.OnlinePstnUsages = reconcile.KeepStr(cfg.OnlinePstnUsages, read.OnlinePstnUsages)
	read.RouteType = reconcile.KeepStr(cfg.RouteType, read.RouteType)
}
