// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &roomVideoTeleConferencingPolicyResource{}
	_ resource.ResourceWithConfigure   = &roomVideoTeleConferencingPolicyResource{}
	_ resource.ResourceWithImportState = &roomVideoTeleConferencingPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &roomVideoTeleConferencingPolicyResource{}
)

type roomVideoTeleConferencingPolicyResource struct{ client *clients.Client }

// NewRoomVideoTeleConferencingPolicyResource manages the RoomVideoTeleConferencingPolicy object (New-RoomVideoTeleConferencingPolicy / Get-RoomVideoTeleConferencingPolicy / Set-RoomVideoTeleConferencingPolicy / Remove-RoomVideoTeleConferencingPolicy).
func NewRoomVideoTeleConferencingPolicyResource() resource.Resource {
	return &roomVideoTeleConferencingPolicyResource{}
}

type roomVideoTeleConferencingPolicyModel struct {
	ID                   types.String `tfsdk:"id"`
	Identity             types.String `tfsdk:"identity"`
	AreaCode             types.String `tfsdk:"area_code"`
	Description          types.String `tfsdk:"description"`
	Enabled              types.Bool   `tfsdk:"enabled"`
	PlaceExternalCalls   types.String `tfsdk:"place_external_calls"`
	PlaceInternalCalls   types.String `tfsdk:"place_internal_calls"`
	ReceiveExternalCalls types.String `tfsdk:"receive_external_calls"`
	ReceiveInternalCalls types.String `tfsdk:"receive_internal_calls"`
}

func (r *roomVideoTeleConferencingPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_room_video_tele_conferencing_policy"
}

func (r *roomVideoTeleConferencingPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the RoomVideoTeleConferencingPolicy policy via New-CsTeamsRoomVideoTeleConferencingPolicy / Get-CsTeamsRoomVideoTeleConferencingPolicy / Set-CsTeamsRoomVideoTeleConferencingPolicy / Remove-CsTeamsRoomVideoTeleConferencingPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":               schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"area_code":              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AreaCode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"place_external_calls":   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PlaceExternalCalls parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"place_internal_calls":   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PlaceInternalCalls parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"receive_external_calls": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ReceiveExternalCalls parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"receive_internal_calls": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ReceiveInternalCalls parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *roomVideoTeleConferencingPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *roomVideoTeleConferencingPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan roomVideoTeleConferencingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config roomVideoTeleConferencingPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if plan.Identity.ValueString() == "Global" {
		sp := cs.SetCsTeamsRoomVideoTeleConferencingPolicyParams{}
		sp.Identity = plan.Identity.ValueString()
		if !config.AreaCode.IsNull() {
			sp.AreaCode = plan.AreaCode.ValueString()
		}
		if !config.Description.IsNull() {
			sp.Description = plan.Description.ValueString()
		}
		if !config.Enabled.IsNull() {
			sp.Enabled = plan.Enabled.ValueBoolPointer()
		}
		if !config.PlaceExternalCalls.IsNull() {
			sp.PlaceExternalCalls = plan.PlaceExternalCalls.ValueString()
		}
		if !config.PlaceInternalCalls.IsNull() {
			sp.PlaceInternalCalls = plan.PlaceInternalCalls.ValueString()
		}
		if !config.ReceiveExternalCalls.IsNull() {
			sp.ReceiveExternalCalls = plan.ReceiveExternalCalls.ValueString()
		}
		if !config.ReceiveInternalCalls.IsNull() {
			sp.ReceiveInternalCalls = plan.ReceiveInternalCalls.ValueString()
		}
		if resp.Diagnostics.HasError() {
			return
		}
		if _, err := r.client.CS.SetCsTeamsRoomVideoTeleConferencingPolicy(ctx, sp); err != nil {
			resp.Diagnostics.AddError("Set-RoomVideoTeleConferencingPolicy failed", err.Error())
			return
		}
		cfg := plan
		ident := plan.Identity.ValueString()
		if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
			if !resp.Diagnostics.HasError() {
				resp.Diagnostics.AddError("RoomVideoTeleConferencingPolicy not found", "identity Global does not exist and cannot be created")
			}
			return
		}
		r.reconcileState(&cfg, &plan)
		resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
		return
	}
	p := cs.NewCsTeamsRoomVideoTeleConferencingPolicyParams{}
	if !config.AreaCode.IsNull() {
		p.AreaCode = plan.AreaCode.ValueString()
	}
	if !config.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if !config.Enabled.IsNull() {
		p.Enabled = plan.Enabled.ValueBoolPointer()
	}
	if !config.PlaceExternalCalls.IsNull() {
		p.PlaceExternalCalls = plan.PlaceExternalCalls.ValueString()
	}
	if !config.PlaceInternalCalls.IsNull() {
		p.PlaceInternalCalls = plan.PlaceInternalCalls.ValueString()
	}
	if !config.ReceiveExternalCalls.IsNull() {
		p.ReceiveExternalCalls = plan.ReceiveExternalCalls.ValueString()
	}
	if !config.ReceiveInternalCalls.IsNull() {
		p.ReceiveInternalCalls = plan.ReceiveInternalCalls.ValueString()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTeamsRoomVideoTeleConferencingPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-RoomVideoTeleConferencingPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-RoomVideoTeleConferencingPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readRoomVideoTeleConferencingPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *roomVideoTeleConferencingPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state roomVideoTeleConferencingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *roomVideoTeleConferencingPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state roomVideoTeleConferencingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsRoomVideoTeleConferencingPolicyParams{}
	sp.Identity = id
	if !plan.AreaCode.Equal(state.AreaCode) {
		sp.AreaCode = plan.AreaCode.ValueString()
	}
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.Enabled.Equal(state.Enabled) {
		sp.Enabled = plan.Enabled.ValueBoolPointer()
	}
	if !plan.PlaceExternalCalls.Equal(state.PlaceExternalCalls) {
		sp.PlaceExternalCalls = plan.PlaceExternalCalls.ValueString()
	}
	if !plan.PlaceInternalCalls.Equal(state.PlaceInternalCalls) {
		sp.PlaceInternalCalls = plan.PlaceInternalCalls.ValueString()
	}
	if !plan.ReceiveExternalCalls.Equal(state.ReceiveExternalCalls) {
		sp.ReceiveExternalCalls = plan.ReceiveExternalCalls.ValueString()
	}
	if !plan.ReceiveInternalCalls.Equal(state.ReceiveInternalCalls) {
		sp.ReceiveInternalCalls = plan.ReceiveInternalCalls.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsRoomVideoTeleConferencingPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-RoomVideoTeleConferencingPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AreaCode":             cfg.AreaCode,
		"Description":          cfg.Description,
		"PlaceExternalCalls":   cfg.PlaceExternalCalls,
		"PlaceInternalCalls":   cfg.PlaceInternalCalls,
		"ReceiveExternalCalls": cfg.ReceiveExternalCalls,
		"ReceiveInternalCalls": cfg.ReceiveInternalCalls,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *roomVideoTeleConferencingPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state roomVideoTeleConferencingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.identityOf(state) == "Global" {
		resp.Diagnostics.AddWarning("RoomVideoTeleConferencingPolicy Global not deleted", "The Global RoomVideoTeleConferencingPolicy is a built-in tenant singleton that cannot be removed. It has been dropped from Terraform state but remains unchanged in the tenant.")
		return
	}
	if _, err := r.client.CS.RemoveCsTeamsRoomVideoTeleConferencingPolicy(ctx, cs.RemoveCsTeamsRoomVideoTeleConferencingPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-RoomVideoTeleConferencingPolicy failed", err.Error())
		}
	}
}

func (r *roomVideoTeleConferencingPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *roomVideoTeleConferencingPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan roomVideoTeleConferencingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity != "Global" {
		return
	}
	res, err := r.client.CS.GetCsTeamsRoomVideoTeleConferencingPolicy(ctx, cs.GetCsTeamsRoomVideoTeleConferencingPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur roomVideoTeleConferencingPolicyModel
	readRoomVideoTeleConferencingPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AreaCode.IsUnknown() {
		plan.AreaCode = cur.AreaCode
	}
	if plan.Description.IsUnknown() {
		plan.Description = cur.Description
	}
	if plan.Enabled.IsUnknown() {
		plan.Enabled = cur.Enabled
	}
	if plan.PlaceExternalCalls.IsUnknown() {
		plan.PlaceExternalCalls = cur.PlaceExternalCalls
	}
	if plan.PlaceInternalCalls.IsUnknown() {
		plan.PlaceInternalCalls = cur.PlaceInternalCalls
	}
	if plan.ReceiveExternalCalls.IsUnknown() {
		plan.ReceiveExternalCalls = cur.ReceiveExternalCalls
	}
	if plan.ReceiveInternalCalls.IsUnknown() {
		plan.ReceiveInternalCalls = cur.ReceiveInternalCalls
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *roomVideoTeleConferencingPolicyResource) identityOf(m roomVideoTeleConferencingPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *roomVideoTeleConferencingPolicyResource) refresh(ctx context.Context, identity string, m *roomVideoTeleConferencingPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsRoomVideoTeleConferencingPolicy(ctx, cs.GetCsTeamsRoomVideoTeleConferencingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-RoomVideoTeleConferencingPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readRoomVideoTeleConferencingPolicy(ctx, obj, m)
	return true
}

func readRoomVideoTeleConferencingPolicy(ctx context.Context, obj map[string]any, m *roomVideoTeleConferencingPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AreaCode = types.StringValue(getString(obj, "AreaCode"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.PlaceExternalCalls = types.StringValue(getString(obj, "PlaceExternalCalls"))
	m.PlaceInternalCalls = types.StringValue(getString(obj, "PlaceInternalCalls"))
	m.ReceiveExternalCalls = types.StringValue(getString(obj, "ReceiveExternalCalls"))
	m.ReceiveInternalCalls = types.StringValue(getString(obj, "ReceiveInternalCalls"))
	_ = ctx
}

func (r *roomVideoTeleConferencingPolicyResource) reconcileState(cfg, read *roomVideoTeleConferencingPolicyModel) {
	read.AreaCode = reconcile.KeepStr(cfg.AreaCode, read.AreaCode)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.PlaceExternalCalls = reconcile.KeepStr(cfg.PlaceExternalCalls, read.PlaceExternalCalls)
	read.PlaceInternalCalls = reconcile.KeepStr(cfg.PlaceInternalCalls, read.PlaceInternalCalls)
	read.ReceiveExternalCalls = reconcile.KeepStr(cfg.ReceiveExternalCalls, read.ReceiveExternalCalls)
	read.ReceiveInternalCalls = reconcile.KeepStr(cfg.ReceiveInternalCalls, read.ReceiveInternalCalls)
}
