// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &settingsCustomAppDataSource{}
	_ datasource.DataSourceWithConfigure = &settingsCustomAppDataSource{}
)

type settingsCustomAppDataSource struct{ client *clients.Client }

// NewSettingsCustomAppDataSource looks up a SettingsCustomApp object (Get-SettingsCustomApp).
func NewSettingsCustomAppDataSource() datasource.DataSource { return &settingsCustomAppDataSource{} }

func (d *settingsCustomAppDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_settings_custom_app"
}

func (d *settingsCustomAppDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing SettingsCustomApp object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"is_sideloaded_apps_interaction_enabled": schema.BoolAttribute{Computed: true, Description: "Maps to the -isSideloadedAppsInteractionEnabled parameter."},
		},
	}
}

func (d *settingsCustomAppDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *settingsCustomAppDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data settingsCustomAppModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := d.client.CS.GetCsTeamsSettingsCustomApp(ctx, cs.GetCsTeamsSettingsCustomAppParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-SettingsCustomApp failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("SettingsCustomApp not found", "no SettingsCustomApp object for identity "+identity)
		return
	}
	readSettingsCustomApp(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
