// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &shiftsAppPolicyResource{}
	_ resource.ResourceWithConfigure   = &shiftsAppPolicyResource{}
	_ resource.ResourceWithImportState = &shiftsAppPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &shiftsAppPolicyResource{}
)

type shiftsAppPolicyResource struct{ client *clients.Client }

// NewShiftsAppPolicyResource manages the ShiftsAppPolicy configuration (Get-ShiftsAppPolicy / Set-ShiftsAppPolicy); it adopts the existing object and is not deleted on destroy.
func NewShiftsAppPolicyResource() resource.Resource { return &shiftsAppPolicyResource{} }

type shiftsAppPolicyModel struct {
	ID                              types.String `tfsdk:"id"`
	Identity                        types.String `tfsdk:"identity"`
	AllowTimeClockLocationDetection types.Bool   `tfsdk:"allow_time_clock_location_detection"`
}

func (r *shiftsAppPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_shifts_app_policy"
}

func (r *shiftsAppPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the ShiftsAppPolicy configuration via Set-CsTeamsShiftsAppPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                                  schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                            schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"allow_time_clock_location_detection": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowTimeClockLocationDetection parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *shiftsAppPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *shiftsAppPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan shiftsAppPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config shiftsAppPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsShiftsAppPolicyParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.AllowTimeClockLocationDetection.IsNull() {
		sp.AllowTimeClockLocationDetection = plan.AllowTimeClockLocationDetection.ValueBoolPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsShiftsAppPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ShiftsAppPolicy failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *shiftsAppPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state shiftsAppPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *shiftsAppPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state shiftsAppPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsShiftsAppPolicyParams{}
	sp.Identity = id
	if !plan.AllowTimeClockLocationDetection.Equal(state.AllowTimeClockLocationDetection) {
		sp.AllowTimeClockLocationDetection = plan.AllowTimeClockLocationDetection.ValueBoolPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsShiftsAppPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ShiftsAppPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *shiftsAppPolicyResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("ShiftsAppPolicy configuration not deleted", "This resource manages an existing ShiftsAppPolicy configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *shiftsAppPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *shiftsAppPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan shiftsAppPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.CS.GetCsTeamsShiftsAppPolicy(ctx, cs.GetCsTeamsShiftsAppPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur shiftsAppPolicyModel
	readShiftsAppPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AllowTimeClockLocationDetection.IsUnknown() {
		plan.AllowTimeClockLocationDetection = cur.AllowTimeClockLocationDetection
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *shiftsAppPolicyResource) identityOf(m shiftsAppPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *shiftsAppPolicyResource) refresh(ctx context.Context, identity string, m *shiftsAppPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsShiftsAppPolicy(ctx, cs.GetCsTeamsShiftsAppPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ShiftsAppPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readShiftsAppPolicy(ctx, obj, m)
	return true
}

func readShiftsAppPolicy(ctx context.Context, obj map[string]any, m *shiftsAppPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AllowTimeClockLocationDetection = types.BoolValue(getBool(obj, "AllowTimeClockLocationDetection"))
	_ = ctx
}

func (r *shiftsAppPolicyResource) reconcileState(cfg, read *shiftsAppPolicyModel) {
	read.AllowTimeClockLocationDetection = reconcile.KeepBool(cfg.AllowTimeClockLocationDetection, read.AllowTimeClockLocationDetection)
}
