// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &shiftsPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &shiftsPolicyListDataSource{}
)

type shiftsPolicyListDataSource struct{ client *clients.Client }

// NewShiftsPolicyListDataSource lists every ShiftsPolicy object (Get-ShiftsPolicy).
func NewShiftsPolicyListDataSource() datasource.DataSource { return &shiftsPolicyListDataSource{} }

type shiftsPolicyListModel struct {
	Items []shiftsPolicyModel `tfsdk:"shifts_policies"`
}

func (d *shiftsPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_shifts_policies"
}

func (d *shiftsPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ShiftsPolicy object (Get-ShiftsPolicy).",
		Attributes: map[string]schema.Attribute{
			"shifts_policies": schema.ListNestedAttribute{Computed: true, Description: "All ShiftsPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                                schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                          schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"access_grace_period_minutes":       schema.Int64Attribute{Computed: true, Description: "Maps to the -AccessGracePeriodMinutes parameter."},
				"access_type":                       schema.StringAttribute{Computed: true, Description: "Maps to the -AccessType parameter."},
				"enable_schedule_owner_permissions": schema.BoolAttribute{Computed: true, Description: "Maps to the -EnableScheduleOwnerPermissions parameter."},
				"shift_notice_frequency":            schema.StringAttribute{Computed: true, Description: "Maps to the -ShiftNoticeFrequency parameter."},
				"shift_notice_message_custom":       schema.StringAttribute{Computed: true, Description: "Maps to the -ShiftNoticeMessageCustom parameter."},
				"shift_notice_message_type":         schema.StringAttribute{Computed: true, Description: "Maps to the -ShiftNoticeMessageType parameter."},
			}}},
		},
	}
}

func (d *shiftsPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *shiftsPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTeamsShiftsPolicy(ctx, cs.GetCsTeamsShiftsPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ShiftsPolicy failed", err.Error())
		return
	}
	var data shiftsPolicyListModel
	for _, obj := range res.Value {
		var e shiftsPolicyModel
		readShiftsPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
