// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &targetingPolicyResource{}
	_ resource.ResourceWithConfigure   = &targetingPolicyResource{}
	_ resource.ResourceWithImportState = &targetingPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &targetingPolicyResource{}
)

type targetingPolicyResource struct{ client *clients.Client }

// NewTargetingPolicyResource manages the TargetingPolicy configuration (Get-TargetingPolicy / Set-TargetingPolicy); it adopts the existing object and is not deleted on destroy.
func NewTargetingPolicyResource() resource.Resource { return &targetingPolicyResource{} }

type targetingPolicyModel struct {
	ID                                 types.String `tfsdk:"id"`
	Identity                           types.String `tfsdk:"identity"`
	CustomTagsMode                     types.String `tfsdk:"custom_tags_mode"`
	Description                        types.String `tfsdk:"description"`
	ManageTagsPermissionMode           types.String `tfsdk:"manage_tags_permission_mode"`
	ShiftBackedTagsMode                types.String `tfsdk:"shift_backed_tags_mode"`
	SuggestedPresetTags                types.String `tfsdk:"suggested_preset_tags"`
	TeamOwnersEditWhoCanManageTagsMode types.String `tfsdk:"team_owners_edit_who_can_manage_tags_mode"`
}

func (r *targetingPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_targeting_policy"
}

func (r *targetingPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the TargetingPolicy configuration via Set-CsTeamsTargetingPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                    schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"custom_tags_mode":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomTagsMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"manage_tags_permission_mode": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ManageTagsPermissionMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"shift_backed_tags_mode":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ShiftBackedTagsMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"suggested_preset_tags":       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SuggestedPresetTags parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"team_owners_edit_who_can_manage_tags_mode": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamOwnersEditWhoCanManageTagsMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *targetingPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *targetingPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan targetingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config targetingPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTeamsTargetingPolicyParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.CustomTagsMode.IsNull() {
		sp.CustomTagsMode = plan.CustomTagsMode.ValueString()
	}
	if !config.Description.IsNull() {
		sp.Description = plan.Description.ValueString()
	}
	if !config.ManageTagsPermissionMode.IsNull() {
		sp.ManageTagsPermissionMode = plan.ManageTagsPermissionMode.ValueString()
	}
	if !config.ShiftBackedTagsMode.IsNull() {
		sp.ShiftBackedTagsMode = plan.ShiftBackedTagsMode.ValueString()
	}
	if !config.SuggestedPresetTags.IsNull() {
		sp.SuggestedPresetTags = plan.SuggestedPresetTags.ValueString()
	}
	if !config.TeamOwnersEditWhoCanManageTagsMode.IsNull() {
		sp.TeamOwnersEditWhoCanManageTagsMode = plan.TeamOwnersEditWhoCanManageTagsMode.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsTargetingPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TargetingPolicy failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *targetingPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state targetingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *targetingPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state targetingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsTargetingPolicyParams{}
	sp.Identity = id
	if !plan.CustomTagsMode.Equal(state.CustomTagsMode) {
		sp.CustomTagsMode = plan.CustomTagsMode.ValueString()
	}
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.ManageTagsPermissionMode.Equal(state.ManageTagsPermissionMode) {
		sp.ManageTagsPermissionMode = plan.ManageTagsPermissionMode.ValueString()
	}
	if !plan.ShiftBackedTagsMode.Equal(state.ShiftBackedTagsMode) {
		sp.ShiftBackedTagsMode = plan.ShiftBackedTagsMode.ValueString()
	}
	if !plan.SuggestedPresetTags.Equal(state.SuggestedPresetTags) {
		sp.SuggestedPresetTags = plan.SuggestedPresetTags.ValueString()
	}
	if !plan.TeamOwnersEditWhoCanManageTagsMode.Equal(state.TeamOwnersEditWhoCanManageTagsMode) {
		sp.TeamOwnersEditWhoCanManageTagsMode = plan.TeamOwnersEditWhoCanManageTagsMode.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsTargetingPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TargetingPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"CustomTagsMode":                     cfg.CustomTagsMode,
		"Description":                        cfg.Description,
		"ManageTagsPermissionMode":           cfg.ManageTagsPermissionMode,
		"ShiftBackedTagsMode":                cfg.ShiftBackedTagsMode,
		"SuggestedPresetTags":                cfg.SuggestedPresetTags,
		"TeamOwnersEditWhoCanManageTagsMode": cfg.TeamOwnersEditWhoCanManageTagsMode,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *targetingPolicyResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("TargetingPolicy configuration not deleted", "This resource manages an existing TargetingPolicy configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *targetingPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *targetingPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan targetingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.CS.GetCsTeamsTargetingPolicy(ctx, cs.GetCsTeamsTargetingPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur targetingPolicyModel
	readTargetingPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.CustomTagsMode.IsUnknown() {
		plan.CustomTagsMode = cur.CustomTagsMode
	}
	if plan.Description.IsUnknown() {
		plan.Description = cur.Description
	}
	if plan.ManageTagsPermissionMode.IsUnknown() {
		plan.ManageTagsPermissionMode = cur.ManageTagsPermissionMode
	}
	if plan.ShiftBackedTagsMode.IsUnknown() {
		plan.ShiftBackedTagsMode = cur.ShiftBackedTagsMode
	}
	if plan.SuggestedPresetTags.IsUnknown() {
		plan.SuggestedPresetTags = cur.SuggestedPresetTags
	}
	if plan.TeamOwnersEditWhoCanManageTagsMode.IsUnknown() {
		plan.TeamOwnersEditWhoCanManageTagsMode = cur.TeamOwnersEditWhoCanManageTagsMode
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *targetingPolicyResource) identityOf(m targetingPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *targetingPolicyResource) refresh(ctx context.Context, identity string, m *targetingPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsTargetingPolicy(ctx, cs.GetCsTeamsTargetingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-TargetingPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readTargetingPolicy(ctx, obj, m)
	return true
}

func readTargetingPolicy(ctx context.Context, obj map[string]any, m *targetingPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.CustomTagsMode = types.StringValue(getString(obj, "CustomTagsMode"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.ManageTagsPermissionMode = types.StringValue(getString(obj, "ManageTagsPermissionMode"))
	m.ShiftBackedTagsMode = types.StringValue(getString(obj, "ShiftBackedTagsMode"))
	m.SuggestedPresetTags = types.StringValue(getString(obj, "SuggestedPresetTags"))
	m.TeamOwnersEditWhoCanManageTagsMode = types.StringValue(getString(obj, "TeamOwnersEditWhoCanManageTagsMode"))
	_ = ctx
}

func (r *targetingPolicyResource) reconcileState(cfg, read *targetingPolicyModel) {
	read.CustomTagsMode = reconcile.KeepStr(cfg.CustomTagsMode, read.CustomTagsMode)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.ManageTagsPermissionMode = reconcile.KeepStr(cfg.ManageTagsPermissionMode, read.ManageTagsPermissionMode)
	read.ShiftBackedTagsMode = reconcile.KeepStr(cfg.ShiftBackedTagsMode, read.ShiftBackedTagsMode)
	read.SuggestedPresetTags = reconcile.KeepStr(cfg.SuggestedPresetTags, read.SuggestedPresetTags)
	read.TeamOwnersEditWhoCanManageTagsMode = reconcile.KeepStr(cfg.TeamOwnersEditWhoCanManageTagsMode, read.TeamOwnersEditWhoCanManageTagsMode)
}
