// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &targetingPolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &targetingPolicyDataSource{}
)

type targetingPolicyDataSource struct{ client *clients.Client }

// NewTargetingPolicyDataSource looks up a TargetingPolicy object (Get-TargetingPolicy).
func NewTargetingPolicyDataSource() datasource.DataSource { return &targetingPolicyDataSource{} }

func (d *targetingPolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_targeting_policy"
}

func (d *targetingPolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing TargetingPolicy object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"custom_tags_mode":            schema.StringAttribute{Computed: true, Description: "Maps to the -CustomTagsMode parameter."},
			"description":                 schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"manage_tags_permission_mode": schema.StringAttribute{Computed: true, Description: "Maps to the -ManageTagsPermissionMode parameter."},
			"shift_backed_tags_mode":      schema.StringAttribute{Computed: true, Description: "Maps to the -ShiftBackedTagsMode parameter."},
			"suggested_preset_tags":       schema.StringAttribute{Computed: true, Description: "Maps to the -SuggestedPresetTags parameter."},
			"team_owners_edit_who_can_manage_tags_mode": schema.StringAttribute{Computed: true, Description: "Maps to the -TeamOwnersEditWhoCanManageTagsMode parameter."},
		},
	}
}

func (d *targetingPolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *targetingPolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data targetingPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.CS.GetCsTeamsTargetingPolicy(ctx, cs.GetCsTeamsTargetingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-TargetingPolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("TargetingPolicy not found", "no TargetingPolicy object for identity "+identity)
		return
	}
	readTargetingPolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
