// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &tenantFederationConfigurationResource{}
	_ resource.ResourceWithConfigure   = &tenantFederationConfigurationResource{}
	_ resource.ResourceWithImportState = &tenantFederationConfigurationResource{}
)

type tenantFederationConfigurationResource struct{ client *clients.Client }

// NewTenantFederationConfigurationResource manages the TenantFederationConfiguration configuration (Get-TenantFederationConfiguration / Set-TenantFederationConfiguration); it adopts the existing object and is not deleted on destroy.
func NewTenantFederationConfigurationResource() resource.Resource {
	return &tenantFederationConfigurationResource{}
}

type tenantFederationConfigurationModel struct {
	ID                                                  types.String `tfsdk:"id"`
	Identity                                            types.String `tfsdk:"identity"`
	AllowFederatedUsers                                 types.Bool   `tfsdk:"allow_federated_users"`
	AllowTeamsConsumer                                  types.Bool   `tfsdk:"allow_teams_consumer"`
	AllowTeamsConsumerInbound                           types.Bool   `tfsdk:"allow_teams_consumer_inbound"`
	AllowedDomains                                      types.String `tfsdk:"allowed_domains"`
	AllowedDomainsAsAList                               types.String `tfsdk:"allowed_domains_as_a_list"`
	AllowedTrialTenantDomains                           types.String `tfsdk:"allowed_trial_tenant_domains"`
	BlockAllSubdomains                                  types.Bool   `tfsdk:"block_all_subdomains"`
	BlockedDomains                                      types.String `tfsdk:"blocked_domains"`
	EnableExternalAccessRestrictionsForChatParticipants types.Bool   `tfsdk:"enable_external_access_restrictions_for_chat_participants"`
	EnableMutualFederationForChatParticipants           types.Bool   `tfsdk:"enable_mutual_federation_for_chat_participants"`
	ExternalAccessWithTrialTenants                      types.String `tfsdk:"external_access_with_trial_tenants"`
	RestrictTeamsConsumerToExternalUserProfiles         types.Bool   `tfsdk:"restrict_teams_consumer_to_external_user_profiles"`
	SecurityTeamAllowBlockListDelegation                types.String `tfsdk:"security_team_allow_block_list_delegation"`
	SharedSipAddressSpace                               types.Bool   `tfsdk:"shared_sip_address_space"`
	TreatDiscoveredPartnersAsUnverified                 types.Bool   `tfsdk:"treat_discovered_partners_as_unverified"`
}

func (r *tenantFederationConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_federation_configuration"
}

func (r *tenantFederationConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the TenantFederationConfiguration configuration via Set-CsTenantFederationConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                     schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"allow_federated_users":        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowFederatedUsers parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_teams_consumer":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowTeamsConsumer parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_teams_consumer_inbound": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowTeamsConsumerInbound parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allowed_domains":              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowedDomains parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"allowed_domains_as_a_list":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowedDomainsAsAList parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"allowed_trial_tenant_domains": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowedTrialTenantDomains parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"block_all_subdomains":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -BlockAllSubdomains parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"blocked_domains":              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -BlockedDomains parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enable_external_access_restrictions_for_chat_participants": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableExternalAccessRestrictionsForChatParticipants parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_mutual_federation_for_chat_participants":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableMutualFederationForChatParticipants parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"external_access_with_trial_tenants":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExternalAccessWithTrialTenants parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"restrict_teams_consumer_to_external_user_profiles":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RestrictTeamsConsumerToExternalUserProfiles parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"security_team_allow_block_list_delegation":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SecurityTeamAllowBlockListDelegation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"shared_sip_address_space":                                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SharedSipAddressSpace parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"treat_discovered_partners_as_unverified":                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -TreatDiscoveredPartnersAsUnverified parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *tenantFederationConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *tenantFederationConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan tenantFederationConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := cs.SetCsTenantFederationConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if !plan.AllowFederatedUsers.IsUnknown() && !plan.AllowFederatedUsers.IsNull() {
		sp.AllowFederatedUsers = plan.AllowFederatedUsers.ValueBoolPointer()
	}
	if !plan.AllowTeamsConsumer.IsUnknown() && !plan.AllowTeamsConsumer.IsNull() {
		sp.AllowTeamsConsumer = plan.AllowTeamsConsumer.ValueBoolPointer()
	}
	if !plan.AllowTeamsConsumerInbound.IsUnknown() && !plan.AllowTeamsConsumerInbound.IsNull() {
		sp.AllowTeamsConsumerInbound = plan.AllowTeamsConsumerInbound.ValueBoolPointer()
	}
	if v := plan.AllowedDomains.ValueString(); v != "" {
		sp.AllowedDomains = v
	}
	if v := plan.AllowedDomainsAsAList.ValueString(); v != "" {
		sp.AllowedDomainsAsAList = v
	}
	if v := plan.AllowedTrialTenantDomains.ValueString(); v != "" {
		sp.AllowedTrialTenantDomains = v
	}
	if !plan.BlockAllSubdomains.IsUnknown() && !plan.BlockAllSubdomains.IsNull() {
		sp.BlockAllSubdomains = plan.BlockAllSubdomains.ValueBoolPointer()
	}
	if v := plan.BlockedDomains.ValueString(); v != "" {
		sp.BlockedDomains = v
	}
	if !plan.EnableExternalAccessRestrictionsForChatParticipants.IsUnknown() && !plan.EnableExternalAccessRestrictionsForChatParticipants.IsNull() {
		sp.EnableExternalAccessRestrictionsForChatParticipants = plan.EnableExternalAccessRestrictionsForChatParticipants.ValueBoolPointer()
	}
	if !plan.EnableMutualFederationForChatParticipants.IsUnknown() && !plan.EnableMutualFederationForChatParticipants.IsNull() {
		sp.EnableMutualFederationForChatParticipants = plan.EnableMutualFederationForChatParticipants.ValueBoolPointer()
	}
	if !plan.ExternalAccessWithTrialTenants.IsUnknown() && !plan.ExternalAccessWithTrialTenants.IsNull() {
		sp.ExternalAccessWithTrialTenants = plan.ExternalAccessWithTrialTenants.ValueString()
	}
	if !plan.RestrictTeamsConsumerToExternalUserProfiles.IsUnknown() && !plan.RestrictTeamsConsumerToExternalUserProfiles.IsNull() {
		sp.RestrictTeamsConsumerToExternalUserProfiles = plan.RestrictTeamsConsumerToExternalUserProfiles.ValueBoolPointer()
	}
	if !plan.SecurityTeamAllowBlockListDelegation.IsUnknown() && !plan.SecurityTeamAllowBlockListDelegation.IsNull() {
		sp.SecurityTeamAllowBlockListDelegation = plan.SecurityTeamAllowBlockListDelegation.ValueString()
	}
	if !plan.SharedSipAddressSpace.IsUnknown() && !plan.SharedSipAddressSpace.IsNull() {
		sp.SharedSipAddressSpace = plan.SharedSipAddressSpace.ValueBoolPointer()
	}
	if !plan.TreatDiscoveredPartnersAsUnverified.IsUnknown() && !plan.TreatDiscoveredPartnersAsUnverified.IsNull() {
		sp.TreatDiscoveredPartnersAsUnverified = plan.TreatDiscoveredPartnersAsUnverified.ValueBoolPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTenantFederationConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TenantFederationConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantFederationConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state tenantFederationConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *tenantFederationConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state tenantFederationConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTenantFederationConfigurationParams{}
	sp.Identity = id
	if !plan.AllowFederatedUsers.Equal(state.AllowFederatedUsers) {
		sp.AllowFederatedUsers = plan.AllowFederatedUsers.ValueBoolPointer()
	}
	if !plan.AllowTeamsConsumer.Equal(state.AllowTeamsConsumer) {
		sp.AllowTeamsConsumer = plan.AllowTeamsConsumer.ValueBoolPointer()
	}
	if !plan.AllowTeamsConsumerInbound.Equal(state.AllowTeamsConsumerInbound) {
		sp.AllowTeamsConsumerInbound = plan.AllowTeamsConsumerInbound.ValueBoolPointer()
	}
	if v := plan.AllowedDomains.ValueString(); v != "" {
		sp.AllowedDomains = v
	}
	if v := plan.AllowedDomainsAsAList.ValueString(); v != "" {
		sp.AllowedDomainsAsAList = v
	}
	if v := plan.AllowedTrialTenantDomains.ValueString(); v != "" {
		sp.AllowedTrialTenantDomains = v
	}
	if !plan.BlockAllSubdomains.Equal(state.BlockAllSubdomains) {
		sp.BlockAllSubdomains = plan.BlockAllSubdomains.ValueBoolPointer()
	}
	if v := plan.BlockedDomains.ValueString(); v != "" {
		sp.BlockedDomains = v
	}
	if !plan.EnableExternalAccessRestrictionsForChatParticipants.Equal(state.EnableExternalAccessRestrictionsForChatParticipants) {
		sp.EnableExternalAccessRestrictionsForChatParticipants = plan.EnableExternalAccessRestrictionsForChatParticipants.ValueBoolPointer()
	}
	if !plan.EnableMutualFederationForChatParticipants.Equal(state.EnableMutualFederationForChatParticipants) {
		sp.EnableMutualFederationForChatParticipants = plan.EnableMutualFederationForChatParticipants.ValueBoolPointer()
	}
	if !plan.ExternalAccessWithTrialTenants.Equal(state.ExternalAccessWithTrialTenants) {
		sp.ExternalAccessWithTrialTenants = plan.ExternalAccessWithTrialTenants.ValueString()
	}
	if !plan.RestrictTeamsConsumerToExternalUserProfiles.Equal(state.RestrictTeamsConsumerToExternalUserProfiles) {
		sp.RestrictTeamsConsumerToExternalUserProfiles = plan.RestrictTeamsConsumerToExternalUserProfiles.ValueBoolPointer()
	}
	if !plan.SecurityTeamAllowBlockListDelegation.Equal(state.SecurityTeamAllowBlockListDelegation) {
		sp.SecurityTeamAllowBlockListDelegation = plan.SecurityTeamAllowBlockListDelegation.ValueString()
	}
	if !plan.SharedSipAddressSpace.Equal(state.SharedSipAddressSpace) {
		sp.SharedSipAddressSpace = plan.SharedSipAddressSpace.ValueBoolPointer()
	}
	if !plan.TreatDiscoveredPartnersAsUnverified.Equal(state.TreatDiscoveredPartnersAsUnverified) {
		sp.TreatDiscoveredPartnersAsUnverified = plan.TreatDiscoveredPartnersAsUnverified.ValueBoolPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTenantFederationConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TenantFederationConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AllowedDomains":                       cfg.AllowedDomains,
		"AllowedDomainsAsAList":                cfg.AllowedDomainsAsAList,
		"AllowedTrialTenantDomains":            cfg.AllowedTrialTenantDomains,
		"BlockedDomains":                       cfg.BlockedDomains,
		"ExternalAccessWithTrialTenants":       cfg.ExternalAccessWithTrialTenants,
		"SecurityTeamAllowBlockListDelegation": cfg.SecurityTeamAllowBlockListDelegation,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantFederationConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("TenantFederationConfiguration configuration not deleted", "This resource manages an existing TenantFederationConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *tenantFederationConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *tenantFederationConfigurationResource) identityOf(m tenantFederationConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *tenantFederationConfigurationResource) refresh(ctx context.Context, identity string, m *tenantFederationConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTenantFederationConfiguration(ctx, cs.GetCsTenantFederationConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-TenantFederationConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readTenantFederationConfiguration(ctx, obj, m)
	return true
}

func readTenantFederationConfiguration(ctx context.Context, obj map[string]any, m *tenantFederationConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AllowFederatedUsers = types.BoolValue(getBool(obj, "AllowFederatedUsers"))
	m.AllowTeamsConsumer = types.BoolValue(getBool(obj, "AllowTeamsConsumer"))
	m.AllowTeamsConsumerInbound = types.BoolValue(getBool(obj, "AllowTeamsConsumerInbound"))
	m.AllowedDomains = types.StringValue(getString(obj, "AllowedDomains"))
	m.AllowedDomainsAsAList = types.StringValue(getString(obj, "AllowedDomainsAsAList"))
	m.AllowedTrialTenantDomains = types.StringValue(getString(obj, "AllowedTrialTenantDomains"))
	m.BlockAllSubdomains = types.BoolValue(getBool(obj, "BlockAllSubdomains"))
	m.BlockedDomains = types.StringValue(getString(obj, "BlockedDomains"))
	m.EnableExternalAccessRestrictionsForChatParticipants = types.BoolValue(getBool(obj, "EnableExternalAccessRestrictionsForChatParticipants"))
	m.EnableMutualFederationForChatParticipants = types.BoolValue(getBool(obj, "EnableMutualFederationForChatParticipants"))
	m.ExternalAccessWithTrialTenants = types.StringValue(getString(obj, "ExternalAccessWithTrialTenants"))
	m.RestrictTeamsConsumerToExternalUserProfiles = types.BoolValue(getBool(obj, "RestrictTeamsConsumerToExternalUserProfiles"))
	m.SecurityTeamAllowBlockListDelegation = types.StringValue(getString(obj, "SecurityTeamAllowBlockListDelegation"))
	m.SharedSipAddressSpace = types.BoolValue(getBool(obj, "SharedSipAddressSpace"))
	m.TreatDiscoveredPartnersAsUnverified = types.BoolValue(getBool(obj, "TreatDiscoveredPartnersAsUnverified"))
	_ = ctx
}

func (r *tenantFederationConfigurationResource) reconcileState(cfg, read *tenantFederationConfigurationModel) {
	read.AllowFederatedUsers = reconcile.KeepBool(cfg.AllowFederatedUsers, read.AllowFederatedUsers)
	read.AllowTeamsConsumer = reconcile.KeepBool(cfg.AllowTeamsConsumer, read.AllowTeamsConsumer)
	read.AllowTeamsConsumerInbound = reconcile.KeepBool(cfg.AllowTeamsConsumerInbound, read.AllowTeamsConsumerInbound)
	read.AllowedDomains = reconcile.KeepStr(cfg.AllowedDomains, read.AllowedDomains)
	read.AllowedDomainsAsAList = reconcile.KeepStr(cfg.AllowedDomainsAsAList, read.AllowedDomainsAsAList)
	read.AllowedTrialTenantDomains = reconcile.KeepStr(cfg.AllowedTrialTenantDomains, read.AllowedTrialTenantDomains)
	read.BlockAllSubdomains = reconcile.KeepBool(cfg.BlockAllSubdomains, read.BlockAllSubdomains)
	read.BlockedDomains = reconcile.KeepStr(cfg.BlockedDomains, read.BlockedDomains)
	read.EnableExternalAccessRestrictionsForChatParticipants = reconcile.KeepBool(cfg.EnableExternalAccessRestrictionsForChatParticipants, read.EnableExternalAccessRestrictionsForChatParticipants)
	read.EnableMutualFederationForChatParticipants = reconcile.KeepBool(cfg.EnableMutualFederationForChatParticipants, read.EnableMutualFederationForChatParticipants)
	read.ExternalAccessWithTrialTenants = reconcile.KeepStr(cfg.ExternalAccessWithTrialTenants, read.ExternalAccessWithTrialTenants)
	read.RestrictTeamsConsumerToExternalUserProfiles = reconcile.KeepBool(cfg.RestrictTeamsConsumerToExternalUserProfiles, read.RestrictTeamsConsumerToExternalUserProfiles)
	read.SecurityTeamAllowBlockListDelegation = reconcile.KeepStr(cfg.SecurityTeamAllowBlockListDelegation, read.SecurityTeamAllowBlockListDelegation)
	read.SharedSipAddressSpace = reconcile.KeepBool(cfg.SharedSipAddressSpace, read.SharedSipAddressSpace)
	read.TreatDiscoveredPartnersAsUnverified = reconcile.KeepBool(cfg.TreatDiscoveredPartnersAsUnverified, read.TreatDiscoveredPartnersAsUnverified)
}
