// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &tenantTrustedIPAddressResource{}
	_ resource.ResourceWithConfigure   = &tenantTrustedIPAddressResource{}
	_ resource.ResourceWithImportState = &tenantTrustedIPAddressResource{}
)

type tenantTrustedIPAddressResource struct{ client *clients.Client }

// NewTenantTrustedIPAddressResource manages the TenantTrustedIPAddress object (New-TenantTrustedIPAddress / Get-TenantTrustedIPAddress / Set-TenantTrustedIPAddress / Remove-TenantTrustedIPAddress).
func NewTenantTrustedIPAddressResource() resource.Resource { return &tenantTrustedIPAddressResource{} }

type tenantTrustedIPAddressModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	Description types.String `tfsdk:"description"`
	IPAddress   types.String `tfsdk:"ip_address"`
	MaskBits    types.Int64  `tfsdk:"mask_bits"`
}

func (r *tenantTrustedIPAddressResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_trusted_ip_address"
}

func (r *tenantTrustedIPAddressResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the TenantTrustedIPAddress policy via New-CsTenantTrustedIPAddress / Get-CsTenantTrustedIPAddress / Set-CsTenantTrustedIPAddress / Remove-CsTenantTrustedIPAddress.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":    schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"ip_address":  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -IPAddress parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"mask_bits":   schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -MaskBits parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *tenantTrustedIPAddressResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *tenantTrustedIPAddressResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan tenantTrustedIPAddressModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := cs.NewCsTenantTrustedIPAddressParams{}
	if !plan.Description.IsUnknown() && !plan.Description.IsNull() {
		p.Description = plan.Description.ValueString()
	}
	if !plan.IPAddress.IsUnknown() && !plan.IPAddress.IsNull() {
		p.IPAddress = plan.IPAddress.ValueString()
	}
	if !plan.MaskBits.IsUnknown() && !plan.MaskBits.IsNull() {
		p.MaskBits = plan.MaskBits.ValueInt64Pointer()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTenantTrustedIPAddress(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-TenantTrustedIPAddress failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-TenantTrustedIPAddress returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readTenantTrustedIPAddress(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantTrustedIPAddressResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state tenantTrustedIPAddressModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *tenantTrustedIPAddressResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state tenantTrustedIPAddressModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTenantTrustedIPAddressParams{}
	sp.Identity = id
	if !plan.Description.Equal(state.Description) {
		sp.Description = plan.Description.ValueString()
	}
	if !plan.MaskBits.Equal(state.MaskBits) {
		sp.MaskBits = plan.MaskBits.ValueInt64Pointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTenantTrustedIPAddress(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TenantTrustedIPAddress failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Description": cfg.Description,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantTrustedIPAddressResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state tenantTrustedIPAddressModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.RemoveCsTenantTrustedIPAddress(ctx, cs.RemoveCsTenantTrustedIPAddressParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-TenantTrustedIPAddress failed", err.Error())
		}
	}
}

func (r *tenantTrustedIPAddressResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *tenantTrustedIPAddressResource) identityOf(m tenantTrustedIPAddressModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *tenantTrustedIPAddressResource) refresh(ctx context.Context, identity string, m *tenantTrustedIPAddressModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTenantTrustedIPAddress(ctx, cs.GetCsTenantTrustedIPAddressParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-TenantTrustedIPAddress failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readTenantTrustedIPAddress(ctx, obj, m)
	return true
}

func readTenantTrustedIPAddress(ctx context.Context, obj map[string]any, m *tenantTrustedIPAddressModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.IPAddress = types.StringValue(getString(obj, "IPAddress"))
	m.MaskBits = types.Int64Value(getInt(obj, "MaskBits"))
	_ = ctx
}

func (r *tenantTrustedIPAddressResource) reconcileState(cfg, read *tenantTrustedIPAddressModel) {
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.IPAddress = reconcile.KeepStr(cfg.IPAddress, read.IPAddress)
	read.MaskBits = reconcile.KeepInt64(cfg.MaskBits, read.MaskBits)
}
