// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &tenantListDataSource{}
	_ datasource.DataSourceWithConfigure = &tenantListDataSource{}
)

type tenantListDataSource struct{ client *clients.Client }

// NewTenantListDataSource lists every Tenant object (Get-Tenant).
func NewTenantListDataSource() datasource.DataSource { return &tenantListDataSource{} }

type tenantListModel struct {
	Items []tenantModel `tfsdk:"tenants"`
}

func (d *tenantListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenants"
}

func (d *tenantListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every Tenant object (Get-Tenant).",
		Attributes: map[string]schema.Attribute{
			"tenants": schema.ListNestedAttribute{Computed: true, Description: "All Tenant objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"name":         schema.StringAttribute{Computed: true, Description: "Name of the object."},
				"display_name": schema.StringAttribute{Computed: true, Description: "Display name of the object."},
				"json":         schema.StringAttribute{Computed: true, Description: "The full object encoded as JSON; decode with jsondecode()."},
			}}},
		},
	}
}

func (d *tenantListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *tenantListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTenant(ctx, cs.GetCsTenantParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-Tenant failed", err.Error())
		return
	}
	var data tenantListModel
	for _, obj := range res.Value {
		var e tenantModel
		readTenant(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
