// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
)

var (
	_ datasource.DataSource              = &upgradePolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &upgradePolicyListDataSource{}
)

type upgradePolicyListDataSource struct{ client *clients.Client }

// NewUpgradePolicyListDataSource lists every UpgradePolicy object (Get-UpgradePolicy).
func NewUpgradePolicyListDataSource() datasource.DataSource { return &upgradePolicyListDataSource{} }

type upgradePolicyListModel struct {
	Items []upgradePolicyModel `tfsdk:"upgrade_policies"`
}

func (d *upgradePolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_upgrade_policies"
}

func (d *upgradePolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every UpgradePolicy object (Get-UpgradePolicy).",
		Attributes: map[string]schema.Attribute{
			"upgrade_policies": schema.ListNestedAttribute{Computed: true, Description: "All UpgradePolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"name":         schema.StringAttribute{Computed: true, Description: "Name of the object."},
				"display_name": schema.StringAttribute{Computed: true, Description: "Display name of the object."},
				"json":         schema.StringAttribute{Computed: true, Description: "The full object encoded as JSON; decode with jsondecode()."},
			}}},
		},
	}
}

func (d *upgradePolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *upgradePolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.CS.GetCsTeamsUpgradePolicy(ctx, cs.GetCsTeamsUpgradePolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-UpgradePolicy failed", err.Error())
		return
	}
	var data upgradePolicyListModel
	for _, obj := range res.Value {
		var e upgradePolicyModel
		readUpgradePolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
