// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-teams/cs"
	"github.com/terraprovider/terraform-provider-teams/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &vdiPolicyResource{}
	_ resource.ResourceWithConfigure   = &vdiPolicyResource{}
	_ resource.ResourceWithImportState = &vdiPolicyResource{}
	_ resource.ResourceWithModifyPlan  = &vdiPolicyResource{}
)

type vdiPolicyResource struct{ client *clients.Client }

// NewVdiPolicyResource manages the VdiPolicy object (New-VdiPolicy / Get-VdiPolicy / Set-VdiPolicy / Remove-VdiPolicy).
func NewVdiPolicyResource() resource.Resource { return &vdiPolicyResource{} }

type vdiPolicyModel struct {
	ID                                  types.String `tfsdk:"id"`
	Identity                            types.String `tfsdk:"identity"`
	DisableAudioVideoInCallsAndMeetings types.Bool   `tfsdk:"disable_audio_video_in_calls_and_meetings"`
	DisableCallsAndMeetings             types.Bool   `tfsdk:"disable_calls_and_meetings"`
	VDI2Optimization                    types.String `tfsdk:"vdi2_optimization"`
}

func (r *vdiPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vdi_policy"
}

func (r *vdiPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the VdiPolicy policy via New-CsTeamsVdiPolicy / Get-CsTeamsVdiPolicy / Set-CsTeamsVdiPolicy / Remove-CsTeamsVdiPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"disable_audio_video_in_calls_and_meetings": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DisableAudioVideoInCallsAndMeetings parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"disable_calls_and_meetings":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DisableCallsAndMeetings parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"vdi2_optimization":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -VDI2Optimization parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *vdiPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *vdiPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan vdiPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config vdiPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if plan.Identity.ValueString() == "Global" {
		sp := cs.SetCsTeamsVdiPolicyParams{}
		sp.Identity = plan.Identity.ValueString()
		if !config.DisableAudioVideoInCallsAndMeetings.IsNull() {
			sp.DisableAudioVideoInCallsAndMeetings = plan.DisableAudioVideoInCallsAndMeetings.ValueBoolPointer()
		}
		if !config.DisableCallsAndMeetings.IsNull() {
			sp.DisableCallsAndMeetings = plan.DisableCallsAndMeetings.ValueBoolPointer()
		}
		if !config.VDI2Optimization.IsNull() {
			sp.VDI2Optimization = plan.VDI2Optimization.ValueString()
		}
		if resp.Diagnostics.HasError() {
			return
		}
		if _, err := r.client.CS.SetCsTeamsVdiPolicy(ctx, sp); err != nil {
			resp.Diagnostics.AddError("Set-VdiPolicy failed", err.Error())
			return
		}
		cfg := plan
		ident := plan.Identity.ValueString()
		if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
			if !resp.Diagnostics.HasError() {
				resp.Diagnostics.AddError("VdiPolicy not found", "identity Global does not exist and cannot be created")
			}
			return
		}
		r.reconcileState(&cfg, &plan)
		resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
		return
	}
	p := cs.NewCsTeamsVdiPolicyParams{}
	if !config.DisableAudioVideoInCallsAndMeetings.IsNull() {
		p.DisableAudioVideoInCallsAndMeetings = plan.DisableAudioVideoInCallsAndMeetings.ValueBoolPointer()
	}
	if !config.DisableCallsAndMeetings.IsNull() {
		p.DisableCallsAndMeetings = plan.DisableCallsAndMeetings.ValueBoolPointer()
	}
	if !config.VDI2Optimization.IsNull() {
		p.VDI2Optimization = plan.VDI2Optimization.ValueString()
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CS.NewCsTeamsVdiPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-VdiPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-VdiPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readVdiPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *vdiPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state vdiPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *vdiPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state vdiPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := cs.SetCsTeamsVdiPolicyParams{}
	sp.Identity = id
	if !plan.DisableAudioVideoInCallsAndMeetings.Equal(state.DisableAudioVideoInCallsAndMeetings) {
		sp.DisableAudioVideoInCallsAndMeetings = plan.DisableAudioVideoInCallsAndMeetings.ValueBoolPointer()
	}
	if !plan.DisableCallsAndMeetings.Equal(state.DisableCallsAndMeetings) {
		sp.DisableCallsAndMeetings = plan.DisableCallsAndMeetings.ValueBoolPointer()
	}
	if !plan.VDI2Optimization.Equal(state.VDI2Optimization) {
		sp.VDI2Optimization = plan.VDI2Optimization.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.CS.SetCsTeamsVdiPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-VdiPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"VDI2Optimization": cfg.VDI2Optimization,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *vdiPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state vdiPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.identityOf(state) == "Global" {
		resp.Diagnostics.AddWarning("VdiPolicy Global not deleted", "The Global VdiPolicy is a built-in tenant singleton that cannot be removed. It has been dropped from Terraform state but remains unchanged in the tenant.")
		return
	}
	if _, err := r.client.CS.RemoveCsTeamsVdiPolicy(ctx, cs.RemoveCsTeamsVdiPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-VdiPolicy failed", err.Error())
		}
	}
}

func (r *vdiPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *vdiPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan vdiPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity != "Global" {
		return
	}
	res, err := r.client.CS.GetCsTeamsVdiPolicy(ctx, cs.GetCsTeamsVdiPolicyParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur vdiPolicyModel
	readVdiPolicy(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.DisableAudioVideoInCallsAndMeetings.IsUnknown() {
		plan.DisableAudioVideoInCallsAndMeetings = cur.DisableAudioVideoInCallsAndMeetings
	}
	if plan.DisableCallsAndMeetings.IsUnknown() {
		plan.DisableCallsAndMeetings = cur.DisableCallsAndMeetings
	}
	if plan.VDI2Optimization.IsUnknown() {
		plan.VDI2Optimization = cur.VDI2Optimization
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *vdiPolicyResource) identityOf(m vdiPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *vdiPolicyResource) refresh(ctx context.Context, identity string, m *vdiPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.CS.GetCsTeamsVdiPolicy(ctx, cs.GetCsTeamsVdiPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-VdiPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readVdiPolicy(ctx, obj, m)
	return true
}

func readVdiPolicy(ctx context.Context, obj map[string]any, m *vdiPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.DisableAudioVideoInCallsAndMeetings = types.BoolValue(getBool(obj, "DisableAudioVideoInCallsAndMeetings"))
	m.DisableCallsAndMeetings = types.BoolValue(getBool(obj, "DisableCallsAndMeetings"))
	m.VDI2Optimization = types.StringValue(getString(obj, "VDI2Optimization"))
	_ = ctx
}

func (r *vdiPolicyResource) reconcileState(cfg, read *vdiPolicyModel) {
	read.DisableAudioVideoInCallsAndMeetings = reconcile.KeepBool(cfg.DisableAudioVideoInCallsAndMeetings, read.DisableAudioVideoInCallsAndMeetings)
	read.DisableCallsAndMeetings = reconcile.KeepBool(cfg.DisableCallsAndMeetings, read.DisableCallsAndMeetings)
	read.VDI2Optimization = reconcile.KeepStr(cfg.VDI2Optimization, read.VDI2Optimization)
}
